### ISSUE TITLE
Please add leaflet.draw to CDNJS

### ISSUE THREAD

**Issue by diwu1989** [Leaflet/Leaflet.draw#106]
Would be very useful to have leaflet draw on cdnjs, thanks.

**Comment by ddproxy** [comment]
Leaflet draw is now automatically available on cdnjs.

**Comment by d3netxer** [comment]
can someone give an example of a map with draw using cdnjs?

**Comment by d3netxer** [comment]
actually I was able to do it by updating an example by d3noob

http://bl.ocks.org/d3netxer/0067027199f1d618680e7d7a3f1b754f
