### ISSUE TITLE
Add Popup on a map

### ISSUE THREAD

**Issue by vladimirbuskin** [Leaflet/Leaflet.draw#118]
Adding L.Popup to a map as draw feature good/bad idea?
- click to draw popup button
- place popup where we want it, prompt for a text, click ok
- popup on a map

i am adding that functionality in my app do you think that could be part of the draw plugin?

![popup](https://f.cloud.github.com/assets/421298/313596/1d428adc-97b3-11e2-90c5-60cad1b081c2.png)

**Comment by ssontag55** [comment]
@vladimirbuskin  anyway to get this?  Nice idea

**Comment by vladimirbuskin** [comment]
Hello, just placed in a repository
https://github.com/vladimirbuskin/Leaflet.draw.popup
i am actually using that at work

**Comment by ssontag55** [comment]
@vladimirbuskin very cool, thanks much!
