### ISSUE TITLE
Making GeoJSON layers 'editable'

### ISSUE THREAD

**Issue by batpad** [Leaflet/Leaflet.draw#13]
My use-case is an application that receives a GeoJSON feed of features, renders them on the map, and then the user can edit these features.  I guess this is more of a question / looking for advice on best practice, sorry if this is not the best place to post, I could not find a mailing list, etc. so I'm assuming this is okay :-)

I currently accomplish this by using code that looks roughly like this:

``` javascript
$.getJSON(url, {}, function(feed) {
    var features = feed.features;
    features.forEach(function(feature) {
        var geometry = L.GeoJSON.geometryToLayer(feature.geometry);
        geometry.on("click", function(e) {
            e.target.editing.enable();
        });
        geometry.addTo(someLayerOnMap);
    });
});
```

This works, but is awkward, and I would much rather use a [GeoJSON layer](http://leaflet.cloudmade.com/reference.html#geojson) . However, I tried hooking into the onEachFeature callback to the layer to try and enable editing of features there, but had no luck.

Just wondering if there's something really basic I'm missing - I'm also really happy to work on this aspect / try to generalize editing of GeoJSON layers a bit if that's possible if anyone has any ideas. Thank you so much for a wonderful tool.

**Comment by maladon** [comment]
If leaflet core has the ability to edit shapes, why do we need leaflet draw?

Also, by doing `geometry.addTo(someLayerOnMap);` one can add the layer to the leaflet draw and then leaflet.draw can handle editing it. Doing it the way jacobtoye suggested makes an editable shape, but leaflet.draw doesn't seem to know about it.

**Comment by PAVANKUSHVAHA** [comment]
I try this to draw 
  var t = new L.FeatureGroup();
             map.addLayer(t);

        $.getJSON("js/draw/neighborhoods.json",function(Data){
        var geojsonlayer = L.geoJson(Data,
        { 
         onEachFeature: function (feature, layer) {
                    alert(feature.properties.prop0);
                    var myLayer = layer;
                  t.addLayer(myLayer);
                }
        });
        map.addLayer(t);
        });
and this to allow leaflet.draw to edit  

        var drawControl = new L.Control.Draw({
            draw: false,
            edit: {
                featureGroup: t,
                remove: false,
                edit: true
           }
        });

        map.addControl(drawControl);
        map.on('draw:edited', function (e) {
        var layers = e.layers;
        layers.eachLayer(function (layer) {
            console.log(layer)
        });
    });
This is able to draw but not able to edit using leaflet.draw toolbar,
kindly solve this issue .
