### ISSUE TITLE
Limit the polys that may be drawn

### ISSUE THREAD

**Issue by ozzmos** [Leaflet/Leaflet.draw#15]
An option to limit the polys that may be drawn

**Comment by mariushop** [comment]
+1

**Comment by SirenHound** [comment]
When I need to do things like this I make the shape a property of the map, and check if it exists... remove it or prevent further shapes of that class being drawn etc.

**Comment by kiang** [comment]
There's a workaround here:
http://rowanwinsemius.id.au/blog/limiting-leaflet-draw-to-drawing-a-single-feature/

But it would be great if there have an option to control the limitation.

**Comment by sirpresage** [comment]
Had the same problem, i needed only one circle so on map.on(L.Draw.Event.CREATED) i just called drawnItems.clearLayers();.

This way the old circle drawn disappear when creating a new one.
