### ISSUE TITLE
how to programmatically create a marker ?

### ISSUE THREAD

**Issue by delister** [Leaflet/Leaflet.draw#159]
Tell me is it possible to programmatically create a marker ?

P.S. Translated by google translate.

**Comment by maizhenying09** [comment]
thanks！

**Comment by haoxl3** [comment]
@jacobtoye 
hello, Do you know how to programmatically add other attributes to the added rectangle, such as line color, custom id, etc.
I tried to do so, but failed
```javascript
let option = {
      shapeOptions: {
		color: '#FF0000'
      },
     bounds: [51.49, -0.1], [51.48, -0.06],
     id: 20
}
L.rectangle(option).addTo(drawnItems);
```
