### ISSUE TITLE
Multiple types of markers?  Or how to create custom toolbar?

### ISSUE THREAD

**Issue by Jakobud** [Leaflet/Leaflet.draw#160]
There needs to be a way to create multiple types of markers on the map.  Is there a way to do this programmatically right now?

I know that probably the most complicated part of this is making the UI for it.  So alternatively, is it possible for someone to create their own custom toolbar?  The doc's don't say anything about the actual methods that are called when you click the toolbar to start dragging a marker (or drawing) to the map.

**Comment by tridip-bba** [comment]
can anyone provide full code in jsfiddle working version

**Comment by alaingilbert** [comment]
@Oliv05 Is there any way to know what type of marker was placed ?
ie:
```js
map.on('draw:created', function (e) {
  var layer = e.layer;
  console.log(layer instanceof L.Draw.Water);
});
```
