### ISSUE TITLE
Can't draw polygons/polylines

### ISSUE THREAD

**Issue by jarandaf** [Leaflet/Leaflet.draw#163]
I am experiencing some issues while trying to draw polygons or polylines. It's a pretty strange behaviour.

This is the relevant part of my code I am using:

``` javascript
var map = L.map('map').setView([41.400425,2.190095], 13);
        L.tileLayer('http://{s}.tiles.mapbox.com/v3/{user}.{map}/{z}/{x}/{y}.png', {
            user: 'jaranda',
            map: myMap.style.dark
        }).addTo(map);

        // Initialize the FeatureGroup to store editable layers
        var drawnItems = new L.FeatureGroup();
        map.addLayer(drawnItems);

        // Initialize the draw control and pass it the FeatureGroup of editable layers
        var drawControl = new L.Control.Draw({
            edit: {
                featureGroup: drawnItems
            }
        });
        map.addControl(drawControl);

        map.on('draw:drawstart', function (layerType) {
            console.log(layerType);
        });
```

I've checked I am actually capturing the click event in the draw panel for both polylines and polygons and it is the case. The problem is that then, by placing the mouse over the map, the "cross" is not being displayed and I am not able to draw anything. It works for other features (rectangle, circle, marker).

The same code works on other machines with the same "environment". I am using Google Chrome Version 28.0.1500.71 for Ubuntu x64.

Any clues on what might be going on?

Thanks!

**Comment by cesarandreslopez** [comment]
Same issue here @jarandaf and @jdubwelch . Polyline and Polygon won't draw.

**Comment by ddproxy** [comment]
Could you provide your current code as a fiddle?

**Comment by aelnajard** [comment]
Did you find what was wrong with it?
