### ISSUE TITLE
Edit GeoJSON objects

### ISSUE THREAD

**Issue by JuFrolov** [Leaflet/Leaflet.draw#187]
Can edit GeoJSON objects added to the map by this method?

**Comment by lcat** [comment]
@knutole it work, but how delete a new L.geoJson()

**Comment by knutole** [comment]
@lcat you could try:
```javascript
// add layer
var layer = L.geoJson();
map.addLayer(layer);

// remove layer
map.removeLayer(layer);

```

**Comment by jonasroessum** [comment]
@jacobtoye 
I have a problem with getting draw to edit my geoJson layer. `leafletLayer.getLayers()[0]` doesn't seem to be any different than `L.geoJson(geojson, options);` With both, I get `Uncaught Error: options.featureGroup must be a L.FeatureGroup` The geoJson is drawn all fine, but I can't make it editable. I load the geoJson from a database and load it onto a new L.geoJson layer and push it to an array. I have a `<select>` from where a layer can be chosen for editing.
```

        $('.js-layer-select').on('change', function() {

            if(drawControl) map.removeControl(drawControl);

            console.log(layerSelectArray[$(this).val()]);

            drawControl = new L.Control.Draw({
                edit: {
                    featureGroup: layerSelectArray[$(this).val()]
                }
            });

            map.addControl(drawControl);


        });
```

How do I make the geoJson layer editable?

**Comment by teaforthecat** [comment]
@jacobtoye Hi,  I do you have something like this elsewhere ?
```
var editableLayers = new L.FeatureGroup([geo_layer]);
map.addLayer(editableLayers);
```

**Comment by jonasroessum** [comment]
@teaforthecat No, I add the geoJson like this:

```
for(var i in dbLayers) { 

    // dbLayers is an array of geoJson FeatureCollection objects.

    var layer = dbLayers[i];

    // GeoJson is stored in a DB, so the geoJson has to be parsed.

    layer.geojson = JSON.parse(layer.geojson);

    var options = {

        pointToLayer: function(feature, latlng) {

            if(feature.properties['marker-icon']) { 
                return L.marker(latlng, {icon: new L.Icon({ 
                    iconUrl: `images/${feature.properties['marker-icon']}.png`,
                    iconAnchor: [16, 16],
                    iconSize: [32, 32],  
                })});
            }

            else return L.marker(latlng, {icon: new L.Icon({ iconUrl: 'images/marker-icon.png' })});                         
            
        }

    };

    var leafletLayer = L.geoJson(layer.geojson, options);

    geoJSONArray.push(leafletLayer);
    geoJSONLayers[layer.layerName] = leafletLayer;
    layerSelectArray[layer.layerId] = leafletLayer.getLayers()[0];

}   

```

**Comment by DenisCarriere** [comment]
@jacobtoye Thanks for the tip, your example really helped out.

Using Leaflet 1.0.X

I might as well also share my source code that worked for me:


```javascript
//=featureEach => module from @turf/meta
//=geojson => user defined

featureEach(geojson, feature => {
  const layer = L.geoJSON(feature).getLayers()[0]
  editableLayers.addLayer(layer)
})

**Comment by AntoniBCN** [comment]
Using proj4leaflet it doesn't work. I got the following error when click on Edit button, but polygon is drawned ok.

> TypeError: latlng is null proj4leaflet.js:40:36

Any idea?

**Comment by fatih0057** [comment]
Hello there

It's been a long time, but now I need it

geojson edit and please can you share the full code to save the drawings made in geojson.

Thanks in advance forever.
