### ISSUE TITLE
editstart/editstop events don't work

### ISSUE THREAD

**Issue by temanmd** [Leaflet/Leaflet.draw#190]
I've this code (coffee):

``` coffeescript
map.on "draw:drawstart", (e) ->
    console.log('drawstart happened')
map.on "draw:drawstop", (e) ->
    console.log('drawstop happened')
map.on "draw:editstart", (e) ->
    console.log('editstart happened')
map.on "draw:editstop", (e) ->
    console.log('editstop happened')
```

And when one clicking some draw-buttons (polygon, circle etc.), then the corresponding  lines are showing in js-console, but not when clicking some edit-buttons (edit or delete).

Same event's body code, but defferent behavior (works and doesn't works).

**Comment by ramblerswebs** [comment]
I am having trouble getting these events to work.
I tried the jsfiddle above http://jsfiddle.net/jacobtoye/CCLmP/2/
but it no longer works
