### ISSUE TITLE
Markers are still draggable after draw:editstop if the markers were highlighted during editing

### ISSUE THREAD

**Issue by markgibbons25** [Leaflet/Leaflet.draw#199]
I have a hover event on my markers which changes the marker icon to a "highlight" icon.

**Comment by fxkr** [comment]
Yay, I just ran into this as well.

I was trying to change the markers icon on draw:edited to reflect that the marker was changed but the change hasn't been confirmed by the server yet (and change it back once I get a reply from the server).

In other words, unlike markgibbons I wanted to change the icon *after* Leaflet.Draw is done with it. Unfortunately, Leaflet.draw undecorates the marker only after the draw:edited callback is done. I can make it work with `setTimeout(function() { ... .setIcon(...) ... }, 0)`, but... what a hack.

This really should have been documented.
