### ISSUE TITLE
Add touch support

### ISSUE THREAD

**Issue by jacobtoye** [Leaflet/Leaflet.draw#2]
Methodology of drawing doesn't work at all for touch browsers :|
- Polylines and ploygons: it is too hard to click on the close marker.
- Rectangles and Markers:drawn by mousedown -> mousemove -> mouseup, this won't work on touch devices.

**Comment by tablackmore** [comment]
i had a project last year that required editing of points, lines and polygons on multiple devices. I forked the repo and slimed it to its core functionality that could work with both touch and mouse. I got it working and deployed in my project. I was planning slowly adding back the functionality I removed (such as tool tips) in a way that would give the developer more control, but ran out of time.

**Comment by olivierdalang** [comment]
@michaelguild13 @tablackmore
> If there is enough demand, I'll get back to working on this

I'm here for the demand ;) I'm currently working on a slum mapping project, and we could definitely use this !! Unfortunately I'm not enough of a javascript/leaflet guru to help much on the code, but I'd be glad to help testing.

**Comment by michaelguild13** [comment]
Alright, I'll pick it back up :)

**Comment by olivierdalang** [comment]
@michaelguild13 that's great news ! Is your master branch already usable ? if so, I'll switch to it and live test your work

**Comment by joealbertvp** [comment]
Hey I'm here for the demand too =)... could you explain the status/plan for this issue?

**Comment by michaelguild13** [comment]
I'll start accepting bugs and fix them.

**Comment by scherler** [comment]
Hi all,

I am as well evaluating ATM our options for bringing the draw features into Leaflet as touch ready. The biggest question now seems: who to fork? ;) Further I agree with people saying that the handling of the drawing would need to be adopted for "touch".

Problematic points I see in current approach in touch and under UX perspective:

* drawing of circle and rectangle are working different then drawing of polygon or polyline (UX)
* to hit the points in touch is pure luck since they are way too small (UX)
* edit hook icons in toolbar are as well way to small for touch devices (UX)

Our UX guy came up with the idea of drag and drop of the different forms on the plan, switching to edit mode on the the form and then have save/cancel as context menu. The context menu in circle would not add much more then the common one, but e.g. the one for polygon would offer to add a point.

Our team can offer some time to fix outstanding issues and especially testing in a real case environment. First interest is that the touch events are fully supported the UX stuff is in a second level. Please let me know what (which fork) I need to use to review current stand and estimate when we could implement the full touch capability.

**Comment by michaelguild13** [comment]
my fork is pretty active, feel free to review and check it out.

On Thu, Feb 19, 2015 at 7:31 AM, Thorsten Scherler <notifications@github.com
> wrote:

> Hi all,
>
> I am as well evaluating ATM our options for bringing the draw features
> into Leaflet as touch ready. The biggest question now seems: who to fork?
> ;) Further I agree with people saying that the handling of the drawing
> would need to be adopted for "touch".
>
> Problematic points I see in current approach in touch and under UX
> perspective:
>
>    - drawing of circle and rectangle are working different then drawing
>    of polygon or polyline (UX)
>    - to hit the points in touch is pure luck since they are way too small
>    (UX)
>    - edit hook icons in toolbar are as well way to small for touch
>    devices (UX)
>
> Our UX guy came up with the idea of drag and drop of the different forms
> on the plan, switching to edit mode on the the form and then have
> save/cancel as context menu. The context menu in circle would not add much
> more then the common one, but e.g. the one for polygon would offer to add a
> point.
>
> Our team can offer some time to fix outstanding issues and especially
> testing in a real case environment. First interest is that the touch events
> are fully supported the UX stuff is in a second level. Please let me know
> what (which fork) I need to use to review current stand and estimate when
> we could implement the full touch capability.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Leaflet/Leaflet.draw/issues/2#issuecomment-75060668>.
>



-- 
Michael Guild
571.338.9782
michaelguild13@gmail.com

**Comment by scherler** [comment]
@michaelguild13  I just switched to your fork and yeah basically it works, but triggering the different forms is close to pure luck, however I think there we could use bigger symbols and we would be good as gold.

**Comment by michaelguild13** [comment]
agreed :). So are you taking over or do people still want me to work on
this?

On Fri, Feb 20, 2015 at 5:19 AM, Thorsten Scherler <notifications@github.com
> wrote:

> @michaelguild13 <https://github.com/michaelguild13> I just switched to
> your fork and yeah basically it works, but triggering the different forms
> is close to pure luck, however I think there we could use bigger symbols
> and we would be good as gold.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Leaflet/Leaflet.draw/issues/2#issuecomment-75229907>.
>



-- 
Michael Guild
571.338.9782
michaelguild13@gmail.com

**Comment by michaelguild13** [comment]
Ok guys, I just updated my repo with upstream and I am back to working on this hardcore. I noticed that the methods for closing the polyline has changed, so that's the first thing I am going to fix.

I will start to accept bugs on my fork. :) Cheers.

**Comment by mvl22** [comment]
This may be of interest:

http://blogs.msdn.com/b/ie/archive/2015/02/24/pointer-events-w3c-recommendation-interoperable-touch-and-removing-the-dreaded-300ms-tap-delay.aspx

**Comment by scherler** [comment]
Hi Micheal,

I did a while ago:

-    "leaflet-draw": "^0.2.3",
+    "leaflet-draw": "michaelguild13/Leaflet.draw",

so far is working fine but a bit problematic is that sometimes you move the map while you are moving the single points in edit mode.

Further I have limited our usage of the lib on editing polygon only, no drawing at all. We are dropping rectangle (but under the hood they are actual polygons) shapes on the map and control the edit/save in the popup. However since we use your fork directly I will let you know about any issues we may see.

**Comment by michaelguild13** [comment]
Well, crap hahaha. Why didn't you do a pull request for me? :) You would've
saved me sometime on merging in upstream hahahaha.
Any bugs you find, please report it on my repo and I will be getting to
them tonight and tomorrow morning. Thanks! :)

On Fri, Feb 27, 2015 at 2:39 AM, Thorsten Scherler <notifications@github.com
> wrote:

> Hi Micheal,
>
> I did a while ago:
>
>    - "leaflet-draw": "^0.2.3",
>    - "leaflet-draw": "michaelguild13/Leaflet.draw",
>
> so far is working fine but a bit problematic is that sometimes you move
> the map while you are moving the single points in edit mode.
>
> Further I have limited our usage of the lib on editing polygon only, no
> drawing at all. We are dropping rectangle (but under the hood they are
> actual polygons) shapes on the map and control the edit/save in the popup.
> However since we use your fork directly I will let you know about any
> issues we may see.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Leaflet/Leaflet.draw/issues/2#issuecomment-76363508>.
>



-- 
Michael Guild
571.338.9782
michaelguild13@gmail.com

**Comment by wavded** [comment]
@michaelguild13 thanks for your work on this.. it's appreciated.

**Comment by michaelguild13** [comment]
It's a community effort. One of the reasons I prefer to work on open-source products :)

**Comment by mrmin24** [comment]
@michaelguild13 
Hi,

Firstly, great work on the touch support. 

I noticed that if I use the touch support and try and "click" on a spot where there is already a polygon drawn on the map, the touch indicator does not show. The point is however registered. I think it is a z-index problem. 

Not sure whether it is fixable on my side?

Thanks again

**Comment by mrmin24** [comment]
@michaelguild13 

Hi Again,

more testing showed that I was a bit wrong. The touch event is not "ALWAYS" recognised when on top of another polygon/circle, but when it is the marker is shown. This happens even when I try and draw over the polygon I just drew with touch.

**Comment by dud3** [comment]
@michaelguild13 @tablackmore @mrmin24 do we have any live example of this feature ?

**Comment by mrmin24** [comment]
@dud3 Not from my side, sorry. It works well though and is pretty much the same as using a mouse.

**Comment by mrmin24** [comment]
@dud3 maybe here http://mapmaker.education.nationalgeographic.com/

**Comment by michaelguild13** [comment]
Yep, that's the live example.

On Thu, Apr 9, 2015 at 9:03 AM, mrmin24 <notifications@github.com> wrote:

> @dud3 <https://github.com/dud3> maybe here
> http://mapmaker.education.nationalgeographic.com/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Leaflet/Leaflet.draw/issues/2#issuecomment-91256444>.
>



-- 
Michael Guild
571.338.9782
michaelguild13@gmail.com

**Comment by dud3** [comment]
Thanks a lot Guys.
One more quick question: does the "add pin" work for anyone, I have the following configuration on mobile:
* Chrome 41.0.2272.96
* Android 5.0.2;
* JS v8 4.1.0.21

But for some reason the feature just doesn't work ;(.

Thanks a lot.

**Comment by ValGeolives** [comment]
Hi @michaelguild13, first thanks for your awesome job!

I'm working with your repo and i'have this error when i start edit mode in a brower: 

![error](https://cloud.githubusercontent.com/assets/11160861/7468994/fabc2928-f30e-11e4-858d-38415d000f4c.png)

It still work but this error appear when i click on the map after enabling edit.

I try with the @jacobtoye repo and the error disappear. Do you have any idea? 

Thx and sorry for my english.

**Comment by DrPandemic** [comment]
Thank you for all your work @michaelguild13, your fork saved me!
I found something interresting while playing with it on iPad. While drawing a new polygon, I was unable to easily add "points" to this polygon if I was clicking on a zone with multiple layers under it. I think I had 3 or 4 layers.
To fix it I simply reduce the number of layers that I was using.

**Comment by michaelguild13** [comment]
Thanks Jean! I've been meaning to update this lib with the one on ng's
mapmaker but haven't found the time. I'll do my best to fix that this week.
Sorry to everyone working with the old version.

On Monday, August 24, 2015, Jean-Samuel Aubry-Guzzi <
notifications@github.com> wrote:

> Thank you for all your work @michaelguild13
> <https://github.com/michaelguild13>, your fork saved me!
> I found something interresting while playing with it on iPad. While
> drawing a new polygon, I was unable to easily add "points" to this polygon
> if I was clicking on a zone with multiple layers under it. I think I had 3
> or 4 layers.
> To fix it I simply reduce the number of layers that I was using.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Leaflet/Leaflet.draw/issues/2#issuecomment-134468274>.
>


-- 
Michael Guild
571.338.9782
michaelguild13@gmail.com

**Comment by MeiRct** [comment]
@michaelguild13 Can you please list the changes that should come with the updated version?
@jacobtoye Are you still on this project, or we should follow another one?

**Comment by michaelguild13** [comment]
@MeiRct , right now I am trying to get the code that I built for the mapmaker project so I can update this repo with the latest. But I currently no longer work for natgeo so there's that. For now, I am just going to go though this chat and trouble shoot what I can.

**Comment by sellonen** [comment]
@michaelguild13 I've been using your code for a while now, thank you a lot. However, windows phones sometimes send 'touchcancel' and 'touchleave' events, causing on error in the Leaflet function L.DomEvent.AddPointerListener ( https://github.com/Leaflet/Leaflet/blob/stable/src/dom/DomEvent.Pointer.js#L20 )

I could overcome this by editing that function directly in Leaflet, but I'd rather not do it, not least because of the changes coming up in leaflet-1.0. Could we somehow treat touchcancel and touchleave as touchend events directly in Leaflet.draw? That way I wouldn't have to create a fork of my own for Leaflet.

**Comment by michaelguild13** [comment]
If your report a bug, I'll do a fix for it.

On Monday, September 14, 2015, sellonen <notifications@github.com> wrote:

> @michaelguild13 <https://github.com/michaelguild13> I've been using your
> code for a while now, thank you a lot. However, windows phones sometimes
> send 'touchcancel' and 'touchleave' events, causing on error in the Leaflet
> function L.DomEvent.AddPointerListener (
> https://github.com/Leaflet/Leaflet/blob/stable/src/dom/DomEvent.Pointer.js#L20
> )
>
> I could overcome this by editing that function directly in Leaflet, but
> I'd rather not do it, not least because of the changes coming up in
> leaflet-1.0. Could we somehow treat touchcancel and touchleave as touchend
> events directly in Leaflet.draw? That way I wouldn't have to create a fork
> of my own for Leaflet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Leaflet/Leaflet.draw/issues/2#issuecomment-140045549>.
>


-- 
Michael Guild
571.338.9782
michaelguild13@gmail.com

**Comment by sellonen** [comment]
Do you mean "raise an issue"? I'm probably a bit noob with github, but there is no "issues" section in your fork of Leaflet.draw.

**Comment by michaelguild13** [comment]
haha, you're right...weird...
ok, I'll look into this tomorrow evening.

On Mon, Sep 14, 2015 at 7:43 AM, sellonen <notifications@github.com> wrote:

> Do you mean "raise an issue"? I'm probably a bit noob with github, but
> there is no "issues" section in your fork of Leaflet.draw.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Leaflet/Leaflet.draw/issues/2#issuecomment-140046736>.
>



-- 
Michael Guild
571.338.9782
michaelguild13@gmail.com

**Comment by alexkb** [comment]
@michaelguild13 any chance of getting that issue queue going for your fork? P.S. Great work on getting touch support.

**Comment by michaelguild13** [comment]
@sellonen , What's your fix for the windows phone?
@alexkb , Sadly, I don't have a windows phone to test with and I also don't have a good emulator setup to catch the events.

To play it safe, might change the code up so touchleave or touchcancel are treated the same as touchend.

L.DomEvent.on(this._container, 'touchcancel', this._onTouchEnd, this);
L.DomEvent.on(this._container, 'touchleave', this._onTouchEnd, this);

**Comment by sellonen** [comment]
Hi, because I have never really looked at the code of Leaflet.Draw and didn't feel comfortable editing it, I resorted to making small modifications to Leaflet itself. Here's what worked: https://github.com/sellonen/Leaflet/commit/0f7760bf417317666b0d62fd945e6eff914a768d 

Let me know if an update to your Leaflet.Draw renders my hack unnecessary.

**Comment by alexkb** [comment]
@michaelguild13 I don't have a windows phone either. My point about the issue queue was so we could ask other questions relating to your fork, instead of asking them all in this one thread! :)

**Comment by sellonen** [comment]
I can test Windows phone 8 if you publish a demo. And I agree, this discussion should take place somewhere else...

**Comment by michaelguild13** [comment]
Ok, so I am an idiot and didn't realize that I had issues setting turned off on this repo. Anyhoo,
Everyone, please report issues here https://github.com/michaelguild13/Leaflet.draw/issues.

Also, if you want to work with me on this, please feel free to do pull requests.

**Comment by omeid** [comment]
@michaelguild13 What is the end goal of the fork? are you intending to create a pull request at some stage?

**Comment by alexkb** [comment]
@michaelguild13 you're no idiot in my book, you've done some great work making an already good library work on a trending platform (mobile) and you should commended!

**Comment by omeid** [comment]
Just saw #285, never mind. :) Good work by the way!

**Comment by michaelguild13** [comment]
@omeid , I tried doing a pull request a few years ago and they didn't want to accept it, stating that they wanted me to create another class for only touch instead of integrating it as I have.

If they want it, I am more than happy for them to take it.

Also, I haven't been that active on this due to working more in react as of late.

**Comment by seedgabo** [comment]
is this folk working  the latest version of leaflet  right now?

**Comment by michaelguild13** [comment]
Most likely not. I've given up supporting this fork since I've been busy on other projects.
I think their latest version took some of the code from this fork and merged it in...I think... No promises :P

**Comment by kajeagentspi** [comment]
This issue still exists on version 1.0.4. Thankfully @michaelguild13 fork still works but with warnings though.
