### ISSUE TITLE
keyboard shortcuts

### ISSUE THREAD

**Issue by frankrowe** [Leaflet/Leaflet.draw#224]
What are maintainer's thoughts on adding keyboard shortcuts as an option? For example, pressing "m" with map focused would activate the add marker tool, "l" for line, etc.

I have already implemented this in another app and it works quite well for adding lots of markers quickly.

**Comment by jonasroessum** [comment]
@jacobtoye 

> Once I get around to doing the work to programatically allow enabling/disabling of the different modes it will be a lot easier for third party apps to add in things like keyboard shortcuts.

Is this something you are working on?

**Comment by ddproxy** [comment]
@jonasroessum This has not been worked on yet. If you have any suggestions for improving or working through this feature I'd like to hear them.
