### ISSUE TITLE
Support for 0.8-dev

### ISSUE THREAD

**Issue by snkashis** [Leaflet/Leaflet.draw#257]
Anyone else here running with 0.8-dev yet?

I prepped a branch to begin work on fixing editing (points are not appearing since editing is undefined)...., and taking care of the map not existing when drawstart or draw-stop is called..which throws `Uncaught TypeError: Cannot call method '_fireMouseEvent' of null` from inside of L.Marker

https://github.com/snkashis/Leaflet.draw/tree/0.8_testing

**Comment by reinvantveer** [comment]
Thanks a bunch for the last hint!

**Comment by rcrodrigues** [comment]
Thanks @cocomo !

**Comment by ddproxy** [comment]
Closing as L1.0 is available
