### ISSUE TITLE
Customizing Toolbar

### ISSUE THREAD

**Issue by WillRijo** [Leaflet/Leaflet.draw#265]
Hi there,

I want to create a toolbar with different options of markers (ex. A marker for restaurant, a gas stations, hospital). 

Right now I only have available one marker button, how do I create different buttons for the same "type" without messing too much your code?

**Comment by rwwagner90** [comment]
@jacobtoye how can I include additional custom buttons, without blowing away all the other buttons? I have a toolbar with polyline, polygon, rectangle, and circle, but I just want to add one extra button to the end. I tried the method you describe, but it removes all the other buttons. Did I do something wrong?
```js
draw = {
      polyline: {
        metric: true,
        shapeOptions: {
          renderer: renderer,
          color: color,
          weight: 5,
          fillOpacity: 0
        }
      },
      polygon: {
        allowIntersection: false,
        showArea: true,
        drawError: {
          color: '#b00b00',
          timeout: 1000
        },
        shapeOptions: {
          renderer: renderer,
          color: color,
          weight: 5,
          fillOpacity: 0
        }
      },
      rectangle: {
        shapeOptions: {
          renderer: renderer,
          color: color,
          weight: 5,
          fillOpacity: 0
        }
      },
      circle: {
        shapeOptions: {
          renderer: renderer,
          color: color,
          weight: 5,
          fillOpacity: 0
        }
      },
      marker: false
    };
    edit = {
      featureGroup: editFeatureGroup,
      buffer: {
        replace_polylines: false,
        separate_buffer: true,
        buffer_style: {
          renderer: renderer,
          color: color,
          weight: 5,
          fillOpacity: 0,
          dashArray: '5, 20'
        }
      }
    };
    //Add the controls to the map
    var drawControlSettings = {
      position: position,
      draw: draw,
      edit: edit
    };
    L.DrawToolbar.include({
      getModeHandlers: function(map) {
        return [
          {
            enabled: true,
            handler: new L.Draw.Marker(map, {icon: new L.Icon.Default()}),
            title: 'Place restaurant marker'
          },
          {
            enabled: true,
            handler: new L.Draw.Marker(map, {icon: new L.Icon.Default()}),
            title: 'Place gas station marker'
          },
          {
            enabled: true,
            handler: new L.Draw.Marker(map, {icon: new L.Icon.Default()}),
            title: 'Place hospital marker'
          }
        ];
      }
    });
    var drawControl = new L.Control.Draw(drawControlSettings);
    this.set('drawControl', drawControl);

    map.addControl(drawControl);
```

**Comment by rwwagner90** [comment]
Never mind, just had to add the rest of the entries to the method. If anyone else was wondering:
```js
L.DrawToolbar.include({
      getModeHandlers: function(map) {
        return [
          {
            enabled: this.options.polyline,
            handler: new L.Draw.Polyline(map, this.options.polyline),
            title: L.drawLocal.draw.toolbar.buttons.polyline
          },
          {
            enabled: this.options.polygon,
            handler: new L.Draw.Polygon(map, this.options.polygon),
            title: L.drawLocal.draw.toolbar.buttons.polygon
          },
          {
            enabled: this.options.rectangle,
            handler: new L.Draw.Rectangle(map, this.options.rectangle),
            title: L.drawLocal.draw.toolbar.buttons.rectangle
          },
          {
            enabled: this.options.circle,
            handler: new L.Draw.Circle(map, this.options.circle),
            title: L.drawLocal.draw.toolbar.buttons.circle
          },
          {
            enabled: this.options.marker,
            handler: new L.Draw.Marker(map, this.options.marker),
            title: L.drawLocal.draw.toolbar.buttons.marker
          },
          {
            enabled: true,
            handler: new L.Draw.Marker(map, {icon: new L.Icon.Default()}),
            title: 'Place restaurant marker'
          },
          {
            enabled: true,
            handler: new L.Draw.Marker(map, {icon: new L.Icon.Default()}),
            title: 'Place gas station marker'
          },
          {
            enabled: true,
            handler: new L.Draw.Marker(map, {icon: new L.Icon.Default()}),
            title: 'Place hospital marker'
          }
        ];
      }
    });
```

**Comment by rwwagner90** [comment]
So, new question, how do I create a custom handler for this new button I have added?

**Comment by ilya-mim** [comment]
Hi
I would like to add one more polygon tool and change it type. I try to extend L.Draw.Polyline
```
L.Draw.PolygonAAA = new L.Draw.Polygon.extend({
      initialize: function (map, options) {
          this.type = 'aaa';
          L.Draw.Polygon.prototype.initialize.call(this, map, options);
      }
});

L.DrawToolbar.include({
    getModeHandlers: function (map) {
        return [
            {
                enabled: true,
                handler: new L.Draw.PolygonAAA(map, {}),
                title: 'Polygon AAA'
            }            
        ];
    }
});
```
but have an error. What's wrong?

**Comment by rwwagner90** [comment]
@ilya-mim one issue is you need to put every option in your getModeHandlers. Just putting the one will just give you one, it doesn't automatically give the defaults. Could you tell me what sort of error you are getting?

**Comment by ilya-mim** [comment]
@rwwagner90 really I put all options in my program but the error is in this code snippet. 
I've created a jsfiddle [http://jsfiddle.net/41kqdt6x/](http://jsfiddle.net/41kqdt6x/). You could see the error in console. How I understand the error because options object is not extended.

**Comment by rwwagner90** [comment]
@ilya-mim I think you needed to just make a copy of the polygon code. What is the intended behavior of this second polygon button? I worked on your fiddle a bit, and got it to at least show up. http://jsfiddle.net/41kqdt6x/4/

**Comment by ilya-mim** [comment]
@rwwagner90 thanks for help. I modified fiddle [http://jsfiddle.net/41kqdt6x/5/](http://jsfiddle.net/41kqdt6x/5/).
I want to have in my app several polygon buttons. Each button for specific types of object such as water or square. I am going to use layeType in draw:created event handler to understand which tool user used.

**Comment by rwwagner90** [comment]
@ilya-mim do you still need help with this?

**Comment by AbdelBa** [comment]
@rwwagner90 I do !
I'm trying to accomplish the same thing as @ilya-mim, I have multiple types of shapes (water, grass, ...) to draw. How do I add a button for each type ?

@ilya-mim's fiddle is not working, could you help ?

**Comment by rwwagner90** [comment]
@AbdelBa did you try my code from above? It shows how to do it.

**Comment by AbdelBa** [comment]
@rwwagner90 It works, thank you.

But once the shape is drawn it disappear from the map unless I add
```javascript
map.on('draw:created', function (e) {
    var type = e.layerType,
      layer = e.layer;

    if (type === 'marker') {
    }

    map.addLayer(layer);
  });
```

**Comment by rwwagner90** [comment]
@AbdelBa That if statement appears to be doing nothing. You can just do:

```js
map.on('draw:created', function (e) {
    map.addLayer(e.layer);
  });
```

**Comment by AbdelBa** [comment]
@rwwagner90 I know :) Copied that from the [doc](https://github.com/Leaflet/Leaflet.draw#drawcreated)

**Comment by dvsoukup** [comment]
Hello!

I know this is a somewhat old thread, but I'm having some problems when customizing the draw toolbar.  I followed some of the instruction in here so far.  I've got it working about 95%, but I'm having a problem with some of the event handlers for two of my buttons.

This works.  I can finish creating shapes when repeat mode is on by clicking "Done":
![capture](https://cloud.githubusercontent.com/assets/13948463/14893890/fa062b00-0d25-11e6-8695-8243b8976bf5.JPG)

And this works.  I can choose finish, or  delete last, or done creating, and it works as expected:
![capture1](https://cloud.githubusercontent.com/assets/13948463/14893967/3b5a848e-0d26-11e6-94a7-73675368763c.JPG)

However, two of my buttons fail to work.  The top two polygons don't correctly fire the events.  It appears the "action" button bar expands out for the THIRD polygon button, when they should expand out for the button I clicked.  in this case, I clicked on the green polygon button, and none of the buttons work:
![capture2](https://cloud.githubusercontent.com/assets/13948463/14893999/5e5e9c68-0d26-11e6-9be7-925180d8eec0.JPG)

I've tried digging through the event handler logic but it's rather extensive and complex.  I didn't want to spend hours on end trying to figure out what I need to implement to get the desired results here.  Any ideas?  Here is my current functionality to over-ride some classes to establish the custom toolbar:

``` javascript
$(function () {

    //change the draw created event to pass in a featureTypeCode
    L.Draw.Feature.prototype._fireCreatedEvent = function (layer) {
        if (this.featureTypeCode) {
            this._map.fire('draw:created', { layer: layer, layerType: this.type, featureTypeCode: this.featureTypeCode });
        } else {
            this._map.fire('draw:created', { layer: layer, layerType: this.type });
        }

    }

    L.Draw.Polygon.prototype._getTooltipText = function () {
        var text, subtext, tooltipObj;
        switch (this.featureTypeCode) {
            case 'siteProperty':
                tooltipObj = L.drawLocal.draw.handlers.polygon.siteProperty.tooltip;
                break;
            case 'building':
                tooltipObj = L.drawLocal.draw.handlers.polygon.building.tooltip;
                break;
            case 'structure':
                tooltipObj = L.drawLocal.draw.handlers.polygon.structure.tooltip;
                break;
            default:
                tooltipObj = L.drawLocal.draw.handlers.polygon.tooltip;
        }
        if (this._markers.length === 0) {
            text = tooltipObj.start;
        } else if (this._markers.length < 3) {
            text = tooltipObj.cont;
        } else {
            text = tooltipObj.end;
            subtext = this._getMeasurementString();
        }

        return {
            text: text,
            subtext: subtext
        };
    }

    L.Draw.PolygonSiteProperty = L.Draw.Polygon.extend({
        options: {
            repeatMode: true
        },
        initialize: function (map, options) {
            this.type = 'polygon';
            this.featureTypeCode = 'siteProperty';
            L.Draw.Feature.prototype.initialize.call(this, map, options);
        }
    });
    L.Draw.PolygonBuilding = L.Draw.Polygon.extend({
        options: {
            repeatMode: true
        },
        initialize: function (map, options) {
            this.type = 'polygon';
            this.featureTypeCode = 'building';
            L.Draw.Feature.prototype.initialize.call(this, map, options);
        }
    });

    L.Draw.PolygonStructure = L.Draw.Polygon.extend({
        options: {
            repeatMode: true
        },
        initialize: function (map, options) {
            this.type = 'polygon';
            this.featureTypeCode = 'structure';
            L.Draw.Feature.prototype.initialize.call(this, map, options);
        }
    });

    L.Draw.RectangleSiteBoundary = L.Draw.Rectangle.extend({
        options: {
            repeatMode: true
        },
        initialize: function (map, options) {
            this.type = 'rectangle';
            this.featureTypeCode = 'siteBoundary';
            this._initialLabelText = L.drawLocal.draw.handlers.rectangle.siteBoundary.tooltip.start;

            L.Draw.SimpleShape.prototype.initialize.call(this, map, options);
        }
    });

    L.Toolbar.prototype._initModeHandler = function (handler, container, buttonIndex, classNamePredix, buttonTitle) {
    var type = handler.type;
    var target = type;
    if (typeof handler.featureTypeCode != 'undefined') {
        target = type + '-' + handler.featureTypeCode;
    }
    this._modes[type] = {};

    this._modes[type].handler = handler;

    this._modes[type].button = this._createButton({
        type: type,
        title: buttonTitle,
        className: classNamePredix + '-' + target,
        container: container,
        callback: this._modes[type].handler.enable,
        context: this._modes[type].handler
    });
    this._modes[type].buttonIndex = buttonIndex;

    this._modes[type].handler
        .on('enabled', this._handlerActivated, this)
        .on('disabled', this._handlerDeactivated, this);
    }

    L.drawLocal = {
        draw: {
            toolbar: {
                actions: {
                    title: 'a test',
                    text: 'Done creating'
                },
                finish: {
                    title: 'Finish drawing',
                    text: 'Finish'
                },
                undo: {
                    title: 'Delete last point drawn',
                    text: 'Delete last point'
                },
                buttons: {
                    polyline: 'Draw a polyline',
                    polygon: {
                        siteProperty: 'Create a site property',
                        building: 'Create a building',
                        structure: 'Create a structure'
                    },
                    rectangle: {
                        siteBoundary: 'Create a site boundary'
                    },
                    circle: 'Draw a circle',
                    marker: 'Draw a marker'
                }
            },
            handlers: {
                circle: {
                    tooltip: {
                        start: 'Click and drag to draw circle.'
                    },
                    radius: 'Radius'
                },
                marker: {
                    tooltip: {
                        start: 'Click map to place a site marker.'
                    }
                },
                polygon: {
                    siteProperty: {
                        tooltip: {
                            start: 'Click to start drawing a site property',
                            cont: 'Click to continue drawing a site property',
                            end: 'Click first point to close this site property'
                        }
                    },
                    building: {
                        tooltip: {
                            start: 'Click to start drawing a building',
                            cont: 'Click to continue drawing a building',
                            end: 'Click first point to close this building'
                        }
                    },
                    structure: {
                        tooltip: {
                            start: 'Click to start drawing a structure',
                            cont: 'Click to continue drawing a structure',
                            end: 'Click first point to close this structure'
                        }
                    }
                },
                polyline: {
                    error: '<strong>Error:</strong> shape edges cannot cross!',
                    tooltip: {
                        start: 'Click to start drawing line',
                        cont: 'Click to continue drawing line',
                        end: 'Click last point to finish line'
                    }
                },
                rectangle: {
                    siteBoundary: {
                        tooltip: {
                            start: 'Click and drag to create a site boundary'
                        }
                    }
                },
                simpleshape: {
                    tooltip: {
                        end: 'Release mouse to finish drawing.'
                    }
                }
            }
        },
        edit: {
            toolbar: {
                actions: {
                    save: {
                        title: 'Save changes.',
                        text: 'Save'
                    },
                    cancel: {
                        title: 'Cancel editing, discards all changes.',
                        text: 'Cancel'
                    }
                },
                buttons: {
                    edit: 'Edit layers.',
                    editDisabled: 'No layers to edit.',
                    remove: 'Delete layers.',
                    removeDisabled: 'No layers to delete.'
                }
            },
            handlers: {
                edit: {
                    tooltip: {
                        text: 'Drag handles, or marker to edit feature.',
                        subtext: 'Click cancel to undo changes.'
                    }
                },
                remove: {
                    tooltip: {
                        text: 'Click on a feature to remove'
                    }
                }
            }
        }
    };

    L.DrawToolbar.include({

        options: {
            polyline: {},
            polygon: {
                siteProperty: {},
                building: {},
                structure: {}
            },
            rectangle: {
                siteBoundary: {}
            },
            circle: {},
            marker: {}
        },
        	initialize: function (options) {
		// Ensure that the options are merged correctly since L.extend is only shallow
		for (var type in this.options) {
			if (this.options.hasOwnProperty(type)) {
				if (options[type]) {
					options[type] = L.extend({}, this.options[type], options[type]);
				}
			}
		}

		this._toolbarClass = 'leaflet-draw-draw';
		L.Toolbar.prototype.initialize.call(this, options);
	},
        getModeHandlers: function (map) {
            return [
                //{
                //    enabled: this.options.polyline,
                //    handler: new L.Draw.Polyline(map, this.options.polyline),
                //    title: L.drawLocal.draw.toolbar.buttons.polyline
                //},
                {
                    enabled: this.options.polygon.siteProperty,
                    handler: new L.Draw.PolygonSiteProperty(map, this.options.polygon.siteProperty),
                    title: L.drawLocal.draw.toolbar.buttons.polygon.siteProperty
                },
                {
                    enabled: this.options.polygon.building,
                    handler: new L.Draw.PolygonBuilding(map, this.options.polygon.building),
                    title: L.drawLocal.draw.toolbar.buttons.polygon.building
                },
                {
                    enabled: this.options.polygon.structure,
                    handler: new L.Draw.PolygonStructure(map, this.options.polygon.structure),
                    title: L.drawLocal.draw.toolbar.buttons.polygon.structure
                },
                {
                    enabled: this.options.rectangle.siteBoundary,
                    handler: new L.Draw.RectangleSiteBoundary(map, this.options.rectangle.siteBoundary),
                    title: L.drawLocal.draw.toolbar.buttons.rectangle.siteBoundary
                },
                //{
                //    enabled: this.options.circle,
                //    handler: new L.Draw.Circle(map, this.options.circle),
                //    title: L.drawLocal.draw.toolbar.buttons.circle
                //},
                {
                    enabled: this.options.marker,
                    handler: new L.Draw.Marker(map, this.options.marker),
                    title: L.drawLocal.draw.toolbar.buttons.marker
                }
            ];
        },

        // Get the actions part of the toolbar
        getActions: function (handler) {
            return [
                {
                    enabled: handler.completeShape,
                    title: L.drawLocal.draw.toolbar.finish.title,
                    text: L.drawLocal.draw.toolbar.finish.text,
                    callback: handler.completeShape,
                    context: handler
                },
                {
                    enabled: handler.deleteLastVertex,
                    title: L.drawLocal.draw.toolbar.undo.title,
                    text: L.drawLocal.draw.toolbar.undo.text,
                    callback: handler.deleteLastVertex,
                    context: handler
                },
                {
                    title: L.drawLocal.draw.toolbar.actions.title,
                    text: L.drawLocal.draw.toolbar.actions.text,
                    callback: this.disable,
                    context: this
                }
            ];
        },

        setOptions: function (options) {
            L.setOptions(this, options);

            for (var type in this._modes) {
                if (this._modes.hasOwnProperty(type) && options.hasOwnProperty(type)) {
                    this._modes[type].handler.setOptions(options[type]);
                }
            }
        }
    });

}());
```

**Comment by ddproxy** [comment]
http://jsfiddle.net/ddproxy/3buzhfmn/1/

I got it partway to what you are working with, my first guess (without scouring code - I'll get to it later today) is the buttons are not binding properly somewhere.

**Comment by dvsoukup** [comment]
@ddproxy I forked that fiddle and included the css which applies the coloring and references the correct shapes from the .png

http://jsfiddle.net/dvsoukup/bpehjpvr/

There is other code too, but it wouldn't have anything to do with this issue.  Definitely an event issue.

Do note that the changes I'd done here are to have a finer level of granularity than just "polygon" or "rectangle", etc.  Not sure if the current implementation of this is the most optimal or most elegant... but it seems to work so far! (other than the event issue of course...).
Your help is greatly appreciated!

**Comment by ddproxy** [comment]
Is there any missing logic to explain why the elements are not being applied/added to the map? - Again I haven't dived into the code much yet so I may just be missing one-line to properly apply the layers to the map.

**Comment by dvsoukup** [comment]
Ahhh, yes.  Need to inclue the edit layers and the on created event when a shape is drawn.  
I added relevant code to bottom.  Shapes will now show up.
http://jsfiddle.net/dvsoukup/neg5h493/

**Comment by dvsoukup** [comment]
@ddproxy did you ever find some time to check out the event timing issue?  No worries if not.  It's not your problem ;)

**Comment by ddproxy** [comment]
@dvsoukup I'm sorry I've been pulled in different directions lately... I'll take a look at this later today ;)

**Comment by dvsoukup** [comment]
Well I looked a bit more into the issue.  Still haven't fully resolved it, but I see part of the problem.  Here in this function, buttons are getting created.  They're placed in the this._modes object.  Well, if I have the same "type" of button, (ie 3 polygons...), then on the first iteration it's creating a property of "polygon" and all of it's relevant properties.  Then on subsequent iterations, it's simply overwriting that same property... since really these are all polygons.  That's one of the reason's why the action bar shows up on the last shape of the same kind (ie, if you have 3 polygon buttons, the action bar will display on the last polygon button when you click on any of the polygon buttons...).  Still haven't figured out the event logic though.  I feel like it's heading towards an issue of the event handler logic is using incorrect button indexes when you go to do something on the action bar.

```javascript
L.Toolbar
function (handler, container, buttonIndex, classNamePredix, buttonTitle) {
	    var type = handler.type;

		this._modes[type] = {};

		this._modes[type].handler = handler;

		this._modes[type].button = this._createButton({
			type: type,
			title: buttonTitle,
			className: classNamePredix + '-' + type,
			container: container,
			callback: this._modes[type].handler.enable,
			context: this._modes[type].handler
		});

		this._modes[type].buttonIndex = buttonIndex;

		this._modes[type].handler
			.on('enabled', this._handlerActivated, this)
			.on('disabled', this._handlerDeactivated, this);
	}
```

**Comment by dvsoukup** [comment]
Ok well it seems I figured out my problem.  Realizing what I wrote above, I made me think about how I was building my custom classes.  What I really needed to do is specify the correct "type" within the new classes, such as this:
```javascript
    /*Class for new polygon shape */
    L.Draw.PolygonSiteProperty = L.Draw.Polygon.extend({
        options: {
            repeatMode: true
        },
        initialize: function (map, options) {
            this.type = 'siteProperty';
            this.featureTypeCode = 'siteProperty';
            L.Draw.Feature.prototype.initialize.call(this, map, options);
        }
    });
```
Before, I was having the type property set to "polygon" for all three of my unique polygons.  This was in turn breaking the event logic and the action bar when created on the toolbar.  Specifying the unique type in the class solved all my issues!

**Comment by bhaskarvk** [comment]
Could someone please summarize the whole thread by putting up a working fiddle ? I am lost in the comments thread.

**Comment by anyayunli** [comment]
none of those jsfiddle works for me, did we have a breaking change in recent release ?

**Comment by hellma314** [comment]
So I would have a solution to offer by adding a new html element, styled as leaflet-draw button, to the dom. Attach any function to the onclick event you like. As icon, I am using Font Awesome (_L.DomUtil.create("a", "fa fa-check-square");_) , but I guess you find other ways to style it.

```

var customButtonControl = L.control({position:"topleft"});

customButtonControl.onAdd = function () {
    var aButton = L.DomUtil.create("a", "fa fa-check-square");
    aButton.setAttribute("title","Give the element a custom title")
    var divLeafletDrawTool = L.DomUtil.create("div", " leaflet-bar leaflet-draw-toolbar-top");
    var divLeafletDrawSection = L.DomUtil.create("div", "leaflet-draw-section");
    var divButton = L.DomUtil.create("div", "leaflet-draw leaflet-control");
    divButton.setAttribute("id", "drawButton");
    divButton.onclick = customFunction();
    divLeafletDrawTool.append(aButton);
    divLeafletDrawSection.append(divLeafletDrawTool);
    divButton.append(divLeafletDrawSection);
    divButton
    return divButton;
}

function customFunction () {
    console.log("Yeehaw, custom stuff!");
}

customButtonControl.addTo(mapData.map);
```

**Comment by darkl1ght** [comment]
> 
> 
> You need to actually place the whole code block including the `L.DrawToolbar.extend({`.
> 
> I've created a jsfiddle (http://jsfiddle.net/jacobtoye/xgdV4/2/) which should help you get started. I've include and example on how to extend the base Draw.Marker handler to change the type and have custom tooltip text.

Hi @jacobtoye , I have looked at your JSFiddle. However, there is something called 

`L.Draw.MarkerA = L.Draw.Marker.extend({...`

That is giving error,"_Property 'SimpleShapeA' does not exist on type 'typeof Draw_'" How to deal with that?

PS I am using Angular 9 to test all of this. And I am doing this on image, rather than on map.

Any help is appreciated.
Thanks in Advanced.
Ayush

here is my code.
```
    let url = this.imageLocation;

    const img = new Image();
    img.src = url;
    const w = img.width;
    const h = img.height;

    const mymap = L.map('mapid', {
      minZoom: 1,
      maxZoom: 5,
      center: [0, 0],
      zoom: 2,
      crs: L.CRS.Simple
    });

    const southWest = mymap.unproject([0, h], mymap.getMaxZoom());
    const northEast = mymap.unproject([w, 0], mymap.getMaxZoom());
    const bounds = new L.LatLngBounds(southWest, northEast);

    L.imageOverlay(url, bounds).addTo(mymap);

    mymap.setMaxBounds(bounds);

    const editableLayers = new L.FeatureGroup();
    mymap.addLayer(editableLayers);


    L.Draw.SimpleShapeA = L.Draw.SimpleShape.extend({  //<-------------- this is where the error comes
      initialize: function (map, options) {
        this.type = 'measurement';
        this.featureTypeCode = 'measurement'
        L.Draw.Feature.prototype.initialize.call(this, map, options);
      },
      options: {
        repeatMode: true
      },
      addHooks: function () {
        L.Draw.Marker.prototype.addHooks.call(this);

        if (this._map) {
          this._tooltip.updateContent({ text: 'Click map to place restaurant.' });
        }
      }
    });


    L.DrawToolbar.include({
      getModeHandlers: function (map: any) {
        return [
          {
            enabled: this.options.polyline,
            handler: new L.Draw.Polyline(map, this.options.polyline),
            title: L.drawLocal.draw.toolbar.buttons.polyline
          },
          {
            enabled: this.options.polygon,
            handler: new L.Draw.Polygon(map, this.options.polygon),
            title: L.drawLocal.draw.toolbar.buttons.polygon
          },
          {
            enabled: this.options.rectangle,
            handler: new L.Draw.Rectangle(map, this.options.rectangle),
            title: L.drawLocal.draw.toolbar.buttons.rectangle
          },
          {
            enabled: this.options.circle,
            handler: new L.Draw.Circle(map, this.options.circle),
            title: L.drawLocal.draw.toolbar.buttons.circle
          },
          {
            enabled: this.options.marker,
            handler: new L.Draw.Marker(map, this.options.marker),
            title: L.drawLocal.draw.toolbar.buttons.marker
          },
          {
            enabled: true,
            handler: new SimpleShapeA (map, { icon: new L.Icon.Default() }),  //  <---------- And so I cant use this here. :(
            title: 'Measurement'
          }
        ];
      }
    });

    const drawControl = new L.Control.Draw({
      edit: {
        featureGroup: editableLayers
      }
    }).addTo(mymap);

    mymap.addControl(drawControl);
```

**Comment by madchester** [comment]
Is there a way to add a custom function without using the Draw features?

Sample code
`L.Draw.SimpleShapeA = customFunction(){
// eg. open modal 
}`

if I use this it catches error "Cannot read property '_leaflet_id' of undefined" when adding the controls for the leaflet.

**Comment by jarekucinski** [comment]
d

> > You need to actually place the whole code block including the `L.DrawToolbar.extend({`.
> > I've created a jsfiddle (http://jsfiddle.net/jacobtoye/xgdV4/2/) which should help you get started. I've include and example on how to extend the base Draw.Marker handler to change the type and have custom tooltip text.
> 
> Hi @jacobtoye , I have looked at your JSFiddle. However, there is something called
> 
> `L.Draw.MarkerA = L.Draw.Marker.extend({...`
> 
> That is giving error,"_Property 'SimpleShapeA' does not exist on type 'typeof Draw_'" How to deal with that?
> 
> PS I am using Angular 9 to test all of this. And I am doing this on image, rather than on map.
> 
> Any help is appreciated.
> Thanks in Advanced.
> Ayush
> 
> here is my code.
> 
> ```
>     let url = this.imageLocation;
> 
>     const img = new Image();
>     img.src = url;
>     const w = img.width;
>     const h = img.height;
> 
>     const mymap = L.map('mapid', {
>       minZoom: 1,
>       maxZoom: 5,
>       center: [0, 0],
>       zoom: 2,
>       crs: L.CRS.Simple
>     });
> 
>     const southWest = mymap.unproject([0, h], mymap.getMaxZoom());
>     const northEast = mymap.unproject([w, 0], mymap.getMaxZoom());
>     const bounds = new L.LatLngBounds(southWest, northEast);
> 
>     L.imageOverlay(url, bounds).addTo(mymap);
> 
>     mymap.setMaxBounds(bounds);
> 
>     const editableLayers = new L.FeatureGroup();
>     mymap.addLayer(editableLayers);
> 
> 
>     L.Draw.SimpleShapeA = L.Draw.SimpleShape.extend({  //<-------------- this is where the error comes
>       initialize: function (map, options) {
>         this.type = 'measurement';
>         this.featureTypeCode = 'measurement'
>         L.Draw.Feature.prototype.initialize.call(this, map, options);
>       },
>       options: {
>         repeatMode: true
>       },
>       addHooks: function () {
>         L.Draw.Marker.prototype.addHooks.call(this);
> 
>         if (this._map) {
>           this._tooltip.updateContent({ text: 'Click map to place restaurant.' });
>         }
>       }
>     });
> 
> 
>     L.DrawToolbar.include({
>       getModeHandlers: function (map: any) {
>         return [
>           {
>             enabled: this.options.polyline,
>             handler: new L.Draw.Polyline(map, this.options.polyline),
>             title: L.drawLocal.draw.toolbar.buttons.polyline
>           },
>           {
>             enabled: this.options.polygon,
>             handler: new L.Draw.Polygon(map, this.options.polygon),
>             title: L.drawLocal.draw.toolbar.buttons.polygon
>           },
>           {
>             enabled: this.options.rectangle,
>             handler: new L.Draw.Rectangle(map, this.options.rectangle),
>             title: L.drawLocal.draw.toolbar.buttons.rectangle
>           },
>           {
>             enabled: this.options.circle,
>             handler: new L.Draw.Circle(map, this.options.circle),
>             title: L.drawLocal.draw.toolbar.buttons.circle
>           },
>           {
>             enabled: this.options.marker,
>             handler: new L.Draw.Marker(map, this.options.marker),
>             title: L.drawLocal.draw.toolbar.buttons.marker
>           },
>           {
>             enabled: true,
>             handler: new SimpleShapeA (map, { icon: new L.Icon.Default() }),  //  <---------- And so I cant use this here. :(
>             title: 'Measurement'
>           }
>         ];
>       }
>     });
> 
>     const drawControl = new L.Control.Draw({
>       edit: {
>         featureGroup: editableLayers
>       }
>     }).addTo(mymap);
> 
>     mymap.addControl(drawControl);
> ```

You should change this line with coment //  <---------- And so I cant use this here. :( to:
`handler: new L.Draw.SimpleShapeA(map, { icon: new L.Icon.Default() }),  `

**Comment by 3xp0n3n7** [comment]
![fire](https://user-images.githubusercontent.com/129877326/229837512-82e44bbb-7505-4b9a-a2b2-9cdc1dbbefd7.png)
