### ISSUE TITLE
Cannot draw shapes in IE 10 and 11 on Windows 8

### ISSUE THREAD

**Issue by patrickarlt** [Leaflet/Leaflet.draw#273]
I am having trouble getting the [demo](http://leaflet.github.io/Leaflet.draw/) working on IE 10 and 11.

I am using a MacBook Pro Retina and VMWare Fusion to run IE 10 and 11. I cannot draw circles or polygons. `msMaxTouchPoints` is being reported as 8.

Is this related to all the other touch issues on here? Should Leaflet.draw work on Windows 8? I realize there are a lot of new complications with pointer events and mixing touch and mouse input that it looks like leaflet draw isn't handling.

**Comment by mike-unearth** [comment]
For anyone else like me who is stuck on an older version of Leaflet, I fixed this by overwriting Leaflet's touch feature detection with Modernizr's:

`L.Browser.touch = Modernizr.touchevents;`
