### ISSUE TITLE
Manually add GeoJSON layers to leaflet.draw

### ISSUE THREAD

**Issue by dwilhelm89** [Leaflet/Leaflet.draw#276]
Using Leaflet.draw on it's own works very well. 
However, I was trying to add some GeoJSON features to the map, which somehow seems to break the editing functionality.

The [jsfiddle](http://jsfiddle.net/V4Fft/) shows, that the code is working until I add a layer to the editable FeatureGroup.

Is there another way to do that?

**Comment by codeofsumit** [comment]
can anyone confirm that this works for leaflet 1.0 Beta 2 and Leaflet Draw master-leaflet ?
I'm having trouble getting geoJson layer editable with the latest (beta) builds.

**Comment by khousuylong** [comment]
Yeah, it works on Leaflet-1.0.3
