### ISSUE TITLE
Question on attaching data values to geometry object creation

### ISSUE THREAD

**Issue by peterb-2795** [Leaflet/Leaflet.draw#287]
Is there a simple means to be able to attach one or more data-elements or extend the options list such that values can be carried through from (for example) a programmatically instanced geometry input a la..
     L.Draw.Polyline(map,{shapeOptions: options}).enable();     etc

such that when the geometry creation is completed and the draw:created event is raised, we are able to check for our associated values that have been carried through from our create request.

My current solution to this problem is somewhat hacky in that I maintain a structure with module level scope that is revisited when a draw:created event is fired.  It would be much cleaner if it was possible to hand name/values into the  request to create an object and then to be able to 'get' those values from the completed geometry object.

Best regards,

**Comment by smeijer** [comment]
@jacobtoye , do you have an example on such use case? I have found a situation where I need to know which button is responsible for creating the feature. I have a couple of buttons now, each targeting other layers and rest-endpoints.

**Comment by smeijer** [comment]
This is how I've solved it currently. Still doesn't feel right, does it?

```js
var draw = new L.Control.Draw({
  draw: {
    marker: { } // my options here
  }
}).addTo(map);

var handler = draw._toolbars.draw._modes.marker.handler;
var isSelf = false;

handler.on({
  'enabled': function() {
    isSelf = true;
  },
  'disabled': function() {
    isSelf = false;
  }
});

map.on({
  'draw:created': function(event) {
    if (! isSelf)
      return;

    var layer = event.layer;
    // ...
  }
});
```
