### ISSUE TITLE
add notes/text capability

### ISSUE THREAD

**Issue by enunciat** [Leaflet/Leaflet.draw#290]
Just wondering if there's any interest in the capability to add notes to maps. Or at least labels for the shapes in Draw.

**Comment by enunciat** [comment]
Any other support for this feature?

**Comment by jacobtoye** [comment]
See https://github.com/manleyjster/Leaflet.Illustrate it extends Leaflet.draw to add support for text based notation (among other features)

**Comment by enunciat** [comment]
thanks
