### ISSUE TITLE
Leaflet edit mode keep colors

### ISSUE THREAD

**Issue by manuelcore** [Leaflet/Leaflet.draw#295]
I am using Leaflet.draw I am only drawing polygons with different colors. When I enter Edit mode all polygons revert to a single color (no fill, as seen herehttps://github.com/Leaflet/Leaflet.draw/blob/master/src/edit/handler/EditToolbar.Edit.js#L9 ):

"// Make sure that Polylines are not filled if (!(layer instanceof L.Circle) && !(layer instanceof L.Polygon) && !(layer instanceof L.Rectangle)) { pathOptions.fill = false; }"

I can not find how to keep (or modify) the colors while edit mode is on because the polygons sometimes overlap and are really hard to see when they all have the same color. Thank you!

Edited: L.EditToolbar.prototype.options.edit.selectedPathOptions.color can be used to modify the edit color for all polygons, I would like to set/keep individual colors.

**Comment by mikila85** [comment]
whats up with this?
currently:
edit: {
                    featureGroup: aoisEditGroup,
                    remove: false,
                    edit:false,
                    selectedPathOptions: { // this property should be one level up
                        color: '#000',
                        fillColor: '#000'
                    }
                }

not working...

**Comment by jbccollins** [comment]
@smeijer Thanks! This was super annoying for me and while your solution seems like it makes use of unintended behavior it works!

**Comment by BooDeer** [comment]
@smeijer Thank you! It's weird that it's still like that this whole time 😅 it was a real chore changing colors in leaflet draw
