### ISSUE TITLE
Notification of draw/edit/delete cancellation

### ISSUE THREAD

**Issue by RobertWarren** [Leaflet/Leaflet.draw#297]
In the application I am currently working on, when the map is loaded event listeners are added for click events. 

I'm listening for draw:drawstart, draw:editstart and draw:deletestart events on the L.map instance and removing my click event handler when one of the events listed above is triggered. 

It appears that Leaflet.draw does not provide event types I can use to listen for the cancellation of a draw/edit/delete operation (e.g. clicking <a class="" href="#" title="Cancel drawing">Cancel</a>), since draw:drawstop, draw:editstop and draw:deletestop do not fire on cancellation.  I need to be able to respond to these actions so I can add a new event listener for map click events.

Is there the possibility of adding draw:drawcancel, draw:editcancel, draw:deletecancel events in future releases? Or could you provide suggestions on how I could get started implementing this myself? 

Thanks in advance. Keep up the great work.

**Comment by edprince** [comment]
How did you find the stop event?
