### ISSUE TITLE
Trigger event for resizing while in edit mode

### ISSUE THREAD

**Issue by snario** [Leaflet/Leaflet.draw#299]
Say I click Edit then on a drawn Circle, and I make the radius slightly larger, I would like to trigger an event before I stop editing / save / cancel my edits. So, maybe something like

`map.on('draw:resize', ...)`

**Comment by arkhemlol** [comment]
Don't get it. I have leaflet map object in my `e.target`. I'm trying to catch currently edited path (circle). Some clarification would be nice.
