### ISSUE TITLE
Click first point to close this shape

### ISSUE THREAD

**Issue by rorentz** [Leaflet/Leaflet.draw#308]
For me it is not possible to close a shape by hitting the first point. Nothing happens. I am using the master versions of leaflet and draw, working on a mac with the latest chrome..

Any hints?

**Comment by rukayaj** [comment]
It's a bit confusing when it's a polyline. It could be "Click cancel to stop drawing" instead of "Click last point to finish line" maybe.

**Comment by smajl** [comment]
@rukayaj I disagree. Cancel should cancel drawing and remove what you've already drawn. This would be much more confusing then current message.
@jacobtoye None seem to respond to original OP question, why he can't close polygon. Actually, I am facing the same problem, can't figure it out. When I start to draw polygon the cursor also does not change to "cross". When I click first point, it just places another point over it. I can't find any major difference between demo and my code... :(

**Comment by p-realinho** [comment]
I'm also having the 'click first point to close' issue.
I believe it is related to the fact that each point is being duplicated, as @smajl mentioned, cause if I manage to get the duplicated point out of the way (either by removing the `translate3d`, lowering the `z-index`, or just simply removing it) and click on the "true" first point, it closes the polygon without a problem.

I'm running the latest version of Chrome (55.0.2883.87 m) on Win10, and didn't test it with any other browsers.

**Comment by umagon** [comment]
I'm having this same issue too. Whenever I click the first point, another point appears instead of closing. Also the points are big. Is there any solution to this yet?
