### ISSUE TITLE
Allow user to draw only one shape

### ISSUE THREAD

**Issue by stevevance** [Leaflet/Leaflet.draw#315]
[this issue has its own solution]

I have a site where I want the user to draw a shape. The shape's GeoJSON description will be saved to a database for them to access the shape later, but I only want to allow them to create one shape per database record. 

I didn't see a sanctioned way so I tried a method that watched for the event "draw:created" and then disabled the drawing toolbar. 

Use

```
map.on('draw:created', function (e) {
    console.log("something was created; hiding draw control");
    var type = e.layerType,
        layer = e.layer;

    drawControl.removeFrom(map);

    editableLayers.addLayer(layer);
});
```

to disable the draw control and 

```
map.on('draw:deletestop', function(e) {
    console.log("something was deleted; showing draw control");
    var type = e.layerType,
        layer = e.layer;

    drawControl.addTo(map);
});
```

to enable the draw control.

**Comment by hmarina** [comment]
Hi every body

I try with the code's MattFerraro and there is a error and  users can to drawing another feature.

Try this
1.-Create one feacture.
2.-Select Delete layer and next select save.
Draw Control appears and the users can draw another feacture.

Any solution for this.

Thank you so much.

**Comment by rowanwins** [comment]
@hmarina I resolved this by changing the final bit of the code to do a check for how many layers are in the drawItems group, if it equals undefined (essetentially 0) then it proceeds.

Cheers
Rowan

map.on("draw:deleted", function(e) {
       checkFeatures = drawnItems._layers.length;
        if (typeof checkFeatures === 'undefined'){
            drawControlEditOnly.removeFrom(map);
            drawControlFull.addTo(map);
        };
    });

**Comment by hmarina** [comment]
Excelent good job .

Thank you so much.

**Comment by dappydaniel** [comment]
I am using leaflet draw to create an app that allows users to draw shapes on basemaps pulled from mapbox and such edit should update into the mapbox. can someone give me the code that will do this please?

Thanks

**Comment by nikolai-b** [comment]
Quick follow from https://github.com/Leaflet/Leaflet.draw/issues/315#issuecomment-104233372 as leaflet has a `getLayers` function that is safer to use instead of `_layers`.

```js
map.on("draw:deleted", function(e) {
   if (drawnItems.getLayers().length === 0){
        drawControlEditOnly.removeFrom(map);
        drawControlFull.addTo(map);
    };
});
```

**Comment by h3ct0r** [comment]
Thanks for the snipped, hope that it going to be merged as an option in trunk!

**Comment by scottydelta** [comment]
make sure `repeatMode:false` when trying this 😞 
this can also be achieved using this, I just have the polygon enabled:
 ````
map.on("draw:created", function (e) {
    drawControl.setDrawingOptions({
        polygon:false
    });
    map.removeControl(drawControl);
    map.addControl(drawControl);
});

map.on("draw:deleted", function (e) {
    drawControl.setDrawingOptions({
        polygon:true
    });
    map.removeControl(drawControl);
    map.addControl(drawControl);
});
````

also apparently `drawControl` has no `removeFrom(map)`, it just have `drawControl.remove(map)`, so to make the above solutions work, replace `removeFrom` with `remove`.

**Comment by nk9** [comment]
There are a number of improvements that have been made to the original solution over the years. Here is a complete, working solution with Leaflet Draw 1.0.4:

```
// Set up the edit control
// Only allow a single shape to be drawn
var drawnItems = new L.FeatureGroup();
map.addLayer(drawnItems);

var drawControlFull = new L.Control.Draw({
    draw: {
        polyline: false,
    },
    edit: {
        featureGroup: drawnItems
    }
});
var drawControlEditOnly = new L.Control.Draw({
    edit: {
        featureGroup: drawnItems
    },
    draw: false
});
map.addControl(drawControlFull);

map.on(L.Draw.Event.CREATED, function (e) {
    drawnItems.addLayer(e.layer);
    drawControlFull.remove(map);
    drawControlEditOnly.addTo(map)
});
map.on(L.Draw.Event.DELETED, function(e) {
   if (drawnItems.getLayers().length === 0){
        drawControlEditOnly.remove(map);
        drawControlFull.addTo(map);
    };
});
```

**Comment by novaknole** [comment]
Hi @nk9 , Thanks for the following code. 

It shows the following error: Cannot read property '_controlCorners' of undefined as soon as I finish drawing the polygon. do you know why?

Thanks in advance.

**Comment by 2803media** [comment]
@nk9 how do you disable the edit tool because you can still click and make new polygons even if the toolbar is disable?

Update:
damned i had the repeatMode set to true.... Now it's working!

**Comment by Candyffm** [comment]
updated solution as of leaflet 1.6.0

```
map.on(L.Draw.Event.CREATED, function (e) {
    drawnItems.addLayer(e.layer);
    map.removeControl(drawControlFull);
    map.addControl(drawControlEditOnly);
});

map.on(L.Draw.Event.DELETED, function(e) {
    if (drawnItems.getLayers().length === 0){
        map.removeControl(drawControlEditOnly);
        map.addControl(drawControlFull);
    }
});
```

**Comment by canDry** [comment]
Further to @nk9 solution (that works great - thx), is it possible then to change the behaviour of the delete button to OK, CANCEL.  Since there's only one element to delete - no need for the user to have to select it.
