### ISSUE TITLE
Add color picker to change color

### ISSUE THREAD

**Issue by inakigarcia** [Leaflet/Leaflet.draw#318]
Hi everyone.

Is there any option to use a color picker to change the color af a polygon... If not it would be nice adding something similar.

Thanks

**Comment by AndreasSchmid1** [comment]
Is it somehow possible to change the color of all drawings during runtime?

**Comment by michaelguild13** [comment]
yes. I've made a branch for it but it's like 5 years old.


<http://threde.com/>
Michael Guild
+1.571.338.9782
mg@threde.com
<http://threde.com/>threde.com


Confidentiality Notice: This e-mail message, including any attachments, is
for the sole use of the intended recipient
(s) and may contain confidential and privileged information. Any
unauthorized review, use, disclosure or distribution is prohibited. If you
are not the intended recipient, please contact the sender by reply e-mail
and destroy all copies of the original message.
