### ISSUE TITLE
typo in documentation page

### ISSUE THREAD

**Issue by mpellerin42** [Leaflet/Leaflet.draw#327]
There is a typo in example of https://github.com/Leaflet/Leaflet.draw#edithandleroptions, so copy/paste  to try out don't work :
It should be :

```
selectedPathOptions: {
    maintainColor: true,
    opacity: 0.3
}
```

with an 'O' upperCase , cause actually with 'selectedPathoptions', it doesn't work ;)

**Comment by swim1986** [comment]
Thanks, that's really helpful.
