### ISSUE TITLE
Edit toolbar still disabled

### ISSUE THREAD

**Issue by kounips** [Leaflet/Leaflet.draw#330]
Hi,

First of all thanks for this plugin, it was great to see these much needed new functions implemented on my map with so little efforts :)

I have followed the instructions carefully but still can't figure out why the edit button and delete button are still not activated. They're here but inactive.

So I have an index.html page and a leafletembed.js file where I put all stuff related to the map.
In my html, aside from leaflet itself (I'm breaking the tags):

``` html
<link rel="stylesheet" type="text/css" href="assets/leaflet/Leaflet.draw-master/dist/leaflet.draw.css" />
<script type="text/javascript" src="assets/leaflet/Leaflet.draw-master/dist/leaflet.draw.js"></script>
```

Then in my leafletembed.js, I've got this:

``` js
 //everything for the map goes here

var map;
var ajaxRequest;
var plotlist;
var plotlayers=[];

function initmap() {
        //map
    var map = new L.map('map').setView([48.8760, 2.3335], 19);
    L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>',
    maxZoom: 20
}).addTo(map);


    // Initialise the FeatureGroup to store editable layers
var drawnItems = new L.FeatureGroup();
map.addLayer(drawnItems);

// Initialise the draw control and pass it the FeatureGroup of editable layers
var drawControl = new L.Control.Draw({
    edit: {
        featureGroup: drawnItems
    }
});
map.addControl(drawControl);

//Create the layer that was drawn
map.on('draw:created', function (e) {
    var type = e.layerType,
        layer = e.layer;

    if (type === 'marker') {
        // Do marker specific actions
    }

    // Do whatever else you need to. (save to db, add to map etc)
    map.addLayer(layer);
});

//Edit the layer that was created
map.on('draw:edited', function (e) {
    var layers = e.layers;
    layers.eachLayer(function (layer) {
        //do whatever you want, most likely save back to db
    });
});
```

Then I have other stuff from leaflet's getting started pages that work just fine.

At first drawn layers used to disappear immediately, so I added the piece of code "draw:created" and the problem was solved, that was great and so I thought adding the "draw:edited" block would then enable me to edit and delete layers, but it's still not active.

I've really tried to understand what I missed but I couldn't find an answer, trying to fix this by adding some code grabbed on threads and tweaking in vain.
I've tried to compare with the examples downloaded along with leaflet.draw but I found in the html script links to all .js files that were not mentioned on leaflet.draw's github page. I did try to put links to EditToolbar.js amongst others in my html but the problem remained.
I can code a bit but I'm not a programmer and my guess is maybe some stuff here are not explained because any average programmer would know them...

I would be grateful if someone could let me know what I did wrong.

Thanks :+1:

**Comment by amoraleda** [comment]
As @kounips, I had the same problem until I saw this comment, and I'm a programmer. =)  The misunderstanding comes from your **Readme.md** file, section *Events, draw:created*. There you can find

```
map.addLayer(layer);
```
instead of 

```
drawnItems.addLayer(layer);
```


Thanks for your work!
