### ISSUE TITLE
bower pulls outdated leaflet-dist dependency

### ISSUE THREAD

**Issue by r0b-** [Leaflet/Leaflet.draw#332]
Hi,

if I install leaflet.draw#master via bower it always pulls the outdated leaflet-dist package (0.7.2) although I have latest leaflet (0.7.3) installed.
Maybe this (unofficial) package/dependency should be replaced with official leaflet package (without the "-dist")?

Thanks
Rob

**Comment by robbiet480** [comment]
@jacobtoye @r0b- is correct here, the bower issue with Leaflet has been resolved for a while. I'm going to open a PR to remove leaflet-dist, especially since it's so far behind now

**Comment by robbiet480** [comment]
PR is #373

**Comment by robbiet480** [comment]
@jacobtoye This is still an issue when trying to `bower install --save leaflet.draw`. Can my PR get merged?

**Comment by Jonibigoud** [comment]
This is still an issue. Can  robbiet480 's PR get merged?

**Comment by stevehipwell** [comment]
+1
