### ISSUE TITLE
Ability to cancel drawing

### ISSUE THREAD

**Issue by jacobtoye** [Leaflet/Leaflet.draw#34]
Currently the user can press Esc to cancel drawing. Should also add a button that cancels as well. Could appear only when user has selected a drawing tool.

**Comment by Loykos** [comment]
How can I cancel drawing if started by the Toolbar button? How can I get the drawHandler?

**Comment by BitaShamsafar** [comment]
try this 
` L.DomEvent.on(document.getElementById('abbruch'), 'click', this.disable, this);`
put it in Toolbar.js inside one of functions

**Comment by mapping-mat** [comment]
this worked for me:
  drawControl._toolbars.draw._activeMode.handler.disable()
given: 
  var drawControl = new L.Control.Draw({position: 'topleft'});
