### ISSUE TITLE
Put edit/delete buttons in a corner of the drawn elements

### ISSUE THREAD

**Issue by jorgeas80** [Leaflet/Leaflet.draw#343]
Hello,

I'd like to know how hard would be to put the Edit/Delete button in the upper right corner of the polygon/rectangle drawn, once you drew it (of course, in case you draw one of these figures). 

My point is to translate the Edit/Delete feature to the drawn element, instead of having those buttons in a separated toolbar.

**Comment by jacobtoye** [comment]
This would be quite difficult to achieve with the currently state of the library. Good idea though I will keep it in mind for future versions.
