### ISSUE TITLE
Marker url 

### ISSUE THREAD

**Issue by jpsantos83** [Leaflet/Leaflet.draw#344]
I can´t find the option for editing the iconUrl and shadowUrl from the marker. He gives me by default js/images and I would like to change to images/ 

Thank you. 
Regards

**Comment by jacobtoye** [comment]
See [MarkerOptions](https://github.com/Leaflet/Leaflet.draw#markeroptions) which are a part of [DrawOptions](https://github.com/Leaflet/Leaflet.draw#drawoptions).

Also see the [example setup](https://github.com/Leaflet/Leaflet.draw#example-leafletdraw-config).
