### ISSUE TITLE
Dude: Save & Redraw

### ISSUE THREAD

**Issue by marcoas** [Leaflet/Leaflet.draw#349]
(Tanslated By Google)
In my project, I need only would use "polylines".
How I can get all the points of the polyline to save (in a database)?
And How I can redraw a polyline, knowing the points that compose?

(Spanish)
En mi proyecto, solamente necesito usaría "polylines".
¿Como puedo obtener todos los puntos del polyline para poder guardarlos (en una base de datos)?
Y ¿Como puedo volver a dibujar un polyline, sabiendo los puntos que lo componen?

**Comment by jacobtoye** [comment]
Thanks @morganherlocker
