### ISSUE TITLE
L.Control.Draw is undefined with angular

### ISSUE THREAD

**Issue by Nolski** [Leaflet/Leaflet.draw#356]
Hi,

I'm writing an angular web application which is making use of Leaflet and Leaflet.draw and I seem to be having issues with `L.Control.Draw` being undefined. Leaflet is working fine and is drawing the map fine. A snippet from one of my controllers is as follows.

```javascript
angular
    .module('Yellr')
    .controller('newAssignmentGeofenceCtrl', ['$scope', 'leafletData',
    function ($scope, leafletData) {

        var map = L.map('set-geofence-map', {drawControl: true}).setView([51.505, -0.09], 13);

        L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
            attribution:
                '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
        }).addTo(map);

        var drawnItems = new L.FeatureGroup();
        map.addLayer(drawnItems);

        // Initialise the draw control and pass it the FeatureGroup of editable layers
        var drawControl = new L.Control.Draw({ // ERROR: Function is undefined
            edit: {
                featureGroup: drawnItems
            }
        });
        map.addControl(drawControl);
    }]);
```
It seems like `L.Control.Draw` is never being created. Have you have people have issues with Leaflet.draw and angular before?

**Comment by jacobtoye** [comment]
I haven't used angular yet but I think you would need to have an angular leaflet.draw directive. See the leaflet one here: https://github.com/tombatossals/angular-leaflet-directive
