### ISSUE TITLE
Cancel event ?

### ISSUE THREAD

**Issue by willemx** [Leaflet/Leaflet.draw#357]
In my app I need to perform some action when the cancel-button is clicked while editing, however, there is no cancel event in the API.
Is there some other way that I can detect a cancel-click?
(I have been experimenting a bit with Jquery .click() on some draw elements, but I can't get it working...)

**Comment by jacobtoye** [comment]
You should be able to use the [draw:editstop event](https://github.com/Leaflet/Leaflet.draw#draweditstop)

**Comment by IllyaMoskvin** [comment]
For anyone else coming here via search engines, a clarification: you can use the `draw:editstop` event to _specifically_ capture Cancel-clicks on the Edit tool. It's not generic. AFAICT, you cannot use it to capture events for e.g. the Cancel button on the Rectangle, or on other tools (#556)
