### ISSUE TITLE
Adding geoJson properties to an item drawn with Leaflet.draw

### ISSUE THREAD

**Issue by ktmn** [Leaflet/Leaflet.draw#358]
If I pop a marker on the map and call toGeoJSON() on it everything works as expected, I get:

    {
        "type": "FeatureCollection",
        "features": [
        {
            "type": "Feature",
            "properties": {},
            "geometry": {
                "type": "Point",
                    "coordinates": [
                        -30.146484374999996,
                        6.053161295714079
                    ]
                }
            }
        ]
    }

What must I do before calling toGeoJSON() in order for the returned json string to include some properties, like this:

    {
        "type": "FeatureCollection",
        "features": [
        {
            "type": "Feature",
            "properties": {
                "label": "Point label",
                "popupContent": "<p>Im a popup</p>"
            },
            "geometry": {
                "type": "Point",
                    "coordinates": [
                        -30.146484374999996,
                        6.053161295714079
                    ]
                }
            }
        ]
    }

The reason I'm asking is, I'd add the properties afterwards, directly to the JSON string, but it's hard to identify your point from that string. Only ID-like feature are the coords, but they are not guaranteed to be unique. So if I could at least slip in a little ID into the JSON somehow. Or add the properties beforehand.

**Comment by jacobtoye** [comment]
Check out the Leaflet implementation of `toGeoJSON` at https://github.com/Leaflet/Leaflet/blob/master/src/layer/GeoJSON.js#L234. It does not output any properties unfortunately. In the past I have manually added these properties. Closing this issue as is a Leaflet core issue.

**Comment by TimMcCauley** [comment]
+1
