### ISSUE TITLE
Replacing mouse events and location with multi-touch (TUIO)

### ISSUE THREAD

**Issue by treborrr** [Leaflet/Leaflet.draw#359]
I'm trying to replace the mouse input with TUIO based multi-touch (https://github.com/borismus/MagicTouch) for polyline creation. A touch controlled div will function as the location input, but unfortunately I can't get it working. 
How would I replace _onMouseDown, _onMouseMove and _onMouseUp in leaflet.draw with a custom input?

**Comment by jacobtoye** [comment]
Please see https://github.com/Leaflet/Leaflet.draw/issues/2 for touch support.
