### ISSUE TITLE
Add shapes to custom pane from Leaflet 0.8-dev

### ISSUE THREAD

**Issue by rwwagner90** [Leaflet/Leaflet.draw#360]
I am trying to have the shapes that I draw be added to one of the new custom panes, that are a feature of Leaflet 0.8-dev and 1.0. I have not been able to add them successfully though. Is there a way to do it? I tried creating a renderer and using that:

```js
var filterPane = map.createPane('filterPane');
var renderer = (L.SVG && L.svg()) || (L.Canvas && L.canvas());
renderer.options.pane = 'filterPane';

//These are the drawing options I set
draw = {
        polyline: {
          metric: true,
          shapeOptions: {
            renderer: renderer,
            color: '#03f',
            weight: 5,
            fillOpacity: 0
          }
        },
        polygon: {
          allowIntersection: false,
          showArea: true,
          drawError: {
            color: '#b00b00',
            timeout: 1000
          },
          shapeOptions: {
            renderer: renderer,
            color: '#03f',
            weight: 5,
            fillOpacity: 0
          }
        },
        rectangle: {
          shapeOptions: {
            renderer: renderer,
            color: '#03f',
            weight: 5,
            fillOpacity: 0
          }
        },
        circle: {
          shapeOptions: {
            renderer: renderer,
            color: '#03f',
            weight: 5,
            fillOpacity: 0
          }
        },
        marker: false
      };
```

This does not appear to work though. Any ideas?

**Comment by jacobtoye** [comment]
I haven't poked around with the custom pane stuff yet. Leaflet.draw adds the polyline directly to the map see: https://github.com/Leaflet/Leaflet.draw/blob/master/src/draw/handler/Draw.Polyline.js#L152

**Comment by rwwagner90** [comment]
Closing, as I am no longer using Leaflet

**Comment by clintharris** [comment]
For future reference in case others end up here looking for a way to do this, you can specify the pane as part of the `shapeOptions`:
```
new L.Draw.Rectangle(leafletMap, { shapeOptions: { pane: 'my-custom-pane' } });
```
This works because the value of `shapeOptions` is passed directly to the Leaflet layer class (e.g., `L.Rectangle`) which inherits the `pane` option from the `L.Layer` base class.
