### ISSUE TITLE
Can't enable editing on a polyline

### ISSUE THREAD

**Issue by kyletolle** [Leaflet/Leaflet.draw#364]
On the current [master branch](https://github.com/Leaflet/Leaflet.draw/commit/07b1448f4eba33982f662398988f0337ee55cc02) I can't manually enable editing mode on a polyline.

Calling `layer.editing.enable()` results in an error:

```
 Uncaught TypeError: Cannot set property 'fill' of undefined
```

And I believe that leads us back to this line:
https://github.com/Leaflet/Leaflet.draw/commit/07b1448f4eba33982f662398988f0337ee55cc02#diff-417e4ee28e399d7a4c5dbc14f6897ffaR1153

---

I can go into editing mode using the control on the map, but not when I try to enable the editing mode myself.

I have created a [small project](https://github.com/kyletolle/leaflet-draw-polyline-enable-editing-bug) to help demonstrate this issue.

The line that causes the error is:
https://github.com/kyletolle/leaflet-draw-polyline-enable-editing-bug/blob/master/index.html#L133

If you pull down the project, open it in your browser, and then click on the polyline, you can see the error in the dev tools console. Try clicking on the marker, and then dragging it around. You can drag it with no problems. You can click on the polygon to get it into editing mode too. So going into editing mode works on some features, but not the polyline.

Hope this helps narrow down where the issue might be.

**Comment by kyletolle** [comment]
In fact, if we even try to set the same property when it's a Polygon handler, we get the same error. I don't think the `options.editing` ever gets set in this case.

If nothing else, shouldn't it check for the existence of `options.editing` before trying to set the fill property? The underlying assumption that `options.editing` will always be defined is not met here.

When drawing a feature, the shapeOptions get merged in to the options. And for editing, there's selectedPathOptions, but we never merge those in during this path, do we? Is that what it's expecting?

I did find where `options.editing` is set:
https://github.com/Leaflet/Leaflet.draw/blob/ccca4b11ba4ff545433bf70f610b215053a2615e/src/edit/handler/EditToolbar.Edit.js#L160
But it's only set when `selectedPathOptions` is passed in, and this is only set when one is using the EditToolbar, which is not what I'm doing.

So, the editing object never gets set, because that's handled by the EditToolbar, which I'm not using, which I believe is the root issue.

Additionally, it looks like when manually enabling edit mode, we don't get the default styles either.

Would it be possible to have a default set for the editing styles within the edit handlers? I think that would fix the bug here and also be a sensible default.

Hopefully this digging around was helpful! Cheers.

**Comment by kyletolle** [comment]
A workaround for this is to set the layer's editing option to an empty object before enabling editing.

This doesn't give any of the default styling when editing, but it does keep things from crashing.

```
layer.options.editing || (layer.options.editing = {});
layer.editing.enable()
```

**Comment by manleyjster** [comment]
Hey @kyletolle - This is a known issue. I explained the origin of the bug in #361, but haven't had time to fix it yet. I'm hoping to have the time to put together a PR over the weekend.

**Comment by kyletolle** [comment]
Ahh, sorry I didn't see that before posting this stuff. Thanks for the update!

It was good to find a workaround for it though, in the meantime.

I appreciate your continued efforts here. I'd be happy to help with some testing, so just let me know!

**Comment by sjreynolds143** [comment]
Hi. Love the plugin, it does everything I want. But what I really, really need right now is to be able to drop a polyline onto the map and have it editable. Any news of a fix for this? Happy to test, but my JS isn't up to moving things around in the classes right now! Thanks.

**Comment by ddproxy** [comment]
When you add a polyline to the map, add it to the drawnItems feature Layer (or whatever featureGroup you are using for the items you want to edit).

http://jsfiddle.net/ddproxy/suL12z93/3/

```javascript

var drawnItems = new L.FeatureGroup();
map.addLayer(drawnItems);
...
var drawControl = new L.Control.Draw({
    edit: {
        featureGroup: drawnItems
    }
});
...
drawnItems.addLayer(L.polyline(myLatLngs));
```

**Comment by Ray-Luo** [comment]
@ddproxy Your way works like a charm!

**Comment by catbadger** [comment]
thank you @ddproxy !!!
