### ISSUE TITLE
Editing a shape should fire events as it is edited

### ISSUE THREAD

**Issue by nomcopter** [Leaflet/Leaflet.draw#374]
This is very useful to keep other shapes in sync while one is being dragged.

**Comment by troygnichols** [comment]
+1 for this feature.  I have some other items in my UI that I want to update as a user drags to edit a polygon (computed area of the polygon etc).

Would you consider a PR from @nomcopter's fork? Happy to make one myself, unless nomcopter wants to.

**Comment by troygnichols** [comment]
Oh, there is one.  For posterity: https://github.com/Leaflet/Leaflet.draw/pull/375
