### ISSUE TITLE
Map scrolling/panning when dragging point outside map edge

### ISSUE THREAD

**Issue by canadaka** [Leaflet/Leaflet.draw#382]
A nice feature of the Google Maps DrawingManager plugin is it will scroll the map if you are adding or editing a point and move your mouse beyond the edge of the map.
https://developers.google.com/maps/documentation/javascript/examples/drawing-tools

Would this be something possible with Leaflet.draw?

**Comment by chriswiggins** [comment]
Hey @canadaka 

I've just seen your issue and have figured out myself a fairly simple way of doing this as I also needed to accomplish the same functionality:
Firstly, listen to drawstart/editstart events:

```javascript
//Move the map around when we're editing or drawing
var self = this;

//Move the map around when we're editing or drawing
self._map.on('draw:editstart', function(){
	self._enableMapMoveDrawing();
});

self._map.on('draw:editstop', function(){
	self._disableMapMoveDrawing();
});

self._map.on('draw:drawstart', function(){
	self._enableMapMoveDrawing();
});

self._map.on('draw:drawstop', function(){
	self._disableMapMoveDrawing();
});
```

Then, listen to mouseMove events and check where the mouse is in relation to the map bounds:

```javascript
MyClass.prototype._enableMapMoveDrawing = function(layer){
	this._map.on('mousemove', this._mapMoveDrawingMouseMove, this);
};


MyClass.prototype._mapMoveDrawingMouseMove = function(e){
	var mousePos = e.containerPoint;
	var mapSize = this._map.getSize();

	if(mousePos.y <= 20){
		this._map.panBy([0, -20]);
	}else if(mousePos.y > mapSize.y + 20){
		this._map.panBy([0, 20]);
	}

	if(mousePos.x <= 20){
		this._map.panBy([-20, 0]);
	}else if(mousePos.x > mapSize.x + 20){
		this._map.panBy([20]);
	}
};

MyClass.prototype._disableMapMoveDrawing = function(){
	this._map.off('mousemove', this._mapMoveDrawingMouseMove, this);
};
```

Note that I'm using a class internally and thats why its set out the way it is but you should be able to modify it as you require

**Comment by ddproxy** [comment]
@canadaka @chriswiggins Is this issue resolved or something we should spin off to an other plugin?

**Comment by canadaka** [comment]
Looks like @chriswiggins code is a solution.

**Comment by chriswiggins** [comment]
I'm happy to pull this out into a separate plugin if people would like me to :-)

**Comment by canadaka** [comment]
I think it's something others would use.

**Comment by ddproxy** [comment]
:+1:
