### ISSUE TITLE
circle becomes a marker

### ISSUE THREAD

**Issue by Henner** [Leaflet/Leaflet.draw#383]
I am using this version:
http://leaflet.github.io/Leaflet.draw/leaflet.draw.js

from your example here:
http://leaflet.github.io/Leaflet.draw/

draw a circle in that example and do the following on console:
drawnItems.toGeoJSON()

you will get a point...

**Comment by jieter** [comment]
GeoJSON doesn't support circles currently, so Leaflet converts them tot points. (Documented here: http://leafletjs.com/reference.html#circle)

**Comment by Henner** [comment]
yeep, sorry.
see:
https://github.com/Leaflet/Leaflet/issues/2888
