### ISSUE TITLE
Incompatible with L.GeoJson?

### ISSUE THREAD

**Issue by Ravendarksky** [Leaflet/Leaflet.draw#385]
Any features I create using L.geoJson cause crashes when I try and edit/delete them.

Is this plugin incompatible with them or am I doing something wrong?

Here is the workaround I'm currently using, but it's nasty as it drops all the properties off your geoJSON.

    if (!(typeof (geoJSONFeatures) == 'undefined')) {
        for (var i = 0; i < geoJSONFeatures.length; i++) {

            var currentFeatureGeoJson = L.geoJson(geoJSONFeatures[i]);
            var currentFeature;
            if (geoJSONFeatures[i].geometry.type == "Point") {
                for (var j in currentFeatureGeoJson._layers) {
                    currentFeature = L.marker(currentFeatureGeoJson._layers[j].getLatLng());
                    break;
                }
            }
            else if (geoJSONFeatures[i].geometry.type == "LineString") {
                for (var j in currentFeatureGeoJson._layers) {
                    currentFeature = L.polyline(currentFeatureGeoJson._layers[j].getLatLngs());
                    break;
                }
            }
            else if (geoJSONFeatures[i].geometry.type == "Polygon") {
                for (var j in currentFeatureGeoJson._layers) {
                    currentFeature = L.polygon(currentFeatureGeoJson._layers[j].getLatLngs());
                    break;
                }
            }

            currentFeature.addTo(drawnItems);
        }
    }

**Comment by jieter** [comment]
Works in my experience. Can you provide a jsfiddle demonstrating the problem?

**Comment by Ravendarksky** [comment]
I've never used jsfiddle before and cannot seem to get it to work. I'm missing something obvious.

https://jsfiddle.net/ravendarksky/3phnq3ub/2/

Here is a zip of the problem:

http://www.filedropper.com/geojsonproblem

If you run it you will see that objects A1,2,3 work as expected (made using code above) but objects B1,2,3 don't work (made using L.geoJson)

Thanks for your help!

**Comment by jieter** [comment]
What you're adding to `drawnItems` are `GeoJSON` objects, not the features you want to edit. This works (and :

```JavaScript
var geoJSONFeatures2 = [
    {"type":"Feature","properties":{"name": "B1"},"geometry":{"type":"LineString","coordinates":[[-12,60],[-12,62],[-12,63]]}},
    {"type":"Feature","properties":{"name": "B2"},"geometry":{"type":"Polygon","coordinates":[[[-10,58],[-11,58],[-12,60],[-13,60],[-14,60]]]}},
    {"type":"Feature","properties":{"name": "B3"},"geometry":{"type":"Point","coordinates":[1,60]}}
];

L.geoJson(geoJSONFeatures2).eachLayer(function (layer) {
    layer.bindLabel(layer.feature.properties.name);
    layer.addTo(drawnItems);
});
```

jsfiddle doesn't work because you use https-urls for leaflet and other assets (see console), and have js code wrapped in `<script>`-tags.

**Comment by Ravendarksky** [comment]
Thank you very much for your help. I understand the difference now and I'll be able to make jsfiddles for next time!
