### ISSUE TITLE
Mouse pointer offset from tooltip when drawing polygon

### ISSUE THREAD

**Issue by srt32** [Leaflet/Leaflet.draw#392]
Sometimes when drawing polygons, after creating a few points, the tooltip will be offset from the mouse pointer (see below image). The issue does not occur reliably but only sometimes.

- Seen in Safari on OSX.
- leaflet-draw: 0.2.3

I'm happy to try to debug this issue further but could use some more direction about where to look or ideas on how to more reliably reproduce it. Thanks!

EDIT: possibly related to https://github.com/Leaflet/Leaflet.draw/issues/372.

![image](https://cloud.githubusercontent.com/assets/2181356/7072998/3e9cc13a-dea5-11e4-82bc-d94add791815.png)

**Comment by ddproxy** [comment]
Hey @srt32 - can you check 0.2.4 for this issue?

**Comment by srt32** [comment]
@ddproxy, I am not longer working on a project using the library so I don't have a way to test. Sorry ;(

**Comment by ddproxy** [comment]
Thanks @srt32
