### ISSUE TITLE
Unable to draw polylines and polygons with Leaflet 0.8dev (master branch)

### ISSUE THREAD

**Issue by davenquinn** [Leaflet/Leaflet.draw#393]
Recent builds of Leaflet 0.8dev break polyline/polygon creation functionality. Selecting the tool creates the tooltip instructing to "Click to start drawing line", but clicks on the map have no effect. Rectangles and circles work fine.

This behavior can be seen when the Leaflet core assets used in examples are switched to v0.8dev, as shown [here](http://rawgit.com/davenquinn/Leaflet.draw/873316e/examples/full.html).

**Comment by davenquinn** [comment]
Moving the mouseup command to the map from the mouse marker (in `Draw.Polyline.js`) seems to help (you can start editing), but everything is extremely jerky and doesn't work in with Leaflet v0.7...

**Comment by davenquinn** [comment]
Fixed the issue by adding `mousemove` handlers to both the marker and the map container. Jerkiness is resolved by changing how the cursor position is calculated in the handler.

```javascript
var newPos = e.layerPoint,
    latlng = e.latlng;
```
becomes
```javascript
var newPos = L.point(e.originalEvent.clientX-10, e.originalEvent.clientY-10);
var latlng = this._map.layerPointToLatLng(newPos);
```

Adding `mouseup` events to both the map and the mouse marker layer seems to work for both leaflet 0.7.2 and 0.8dev. Functional examples:

- [Leaflet 0.8dev](http://rawgit.com/davenquinn/Leaflet.draw/leaflet-0.8dev/examples/full.html)
- [Leaflet 0.7.2](http://rawgit.com/davenquinn/Leaflet.draw/master/examples/full.html)

**Comment by yohanboniface** [comment]
> Fixed the issue by adding mousemove handlers to both the marker and the map container.

May be related to https://github.com/Leaflet/Leaflet/pull/3307

**Comment by mmjamal** [comment]
on the demo for 0.8dev the stutter and jerkiness still remains
if you have an existing drawn polygon.

to reproduce the issue.

1. draw a polygon
2. move the mouse fast on the surface of drawn polygon - you will notice - marker dissapears and becomes hand again.

but if there are no drawn polygon it works as expected.

**Comment by ddproxy** [comment]
@mmjamal @yohanboniface @davenquinn this seems like a Leaflet issue, can you confirm this is still happening in L 1.0 or L 0.7.7?
