### ISSUE TITLE
Uncaught TypeError: Cannot read property 'enable' of undefined. (Polygon added after map load)

### ISSUE THREAD

**Issue by tyeware** [Leaflet/Leaflet.draw#398]
I am loading a single pologon into the featureGroup after the map and feature group has been loaded, by doing an ajax call to a web service. Creating the polygon is successful, but when then attempting to edit the polygon  through the "Edit Layers" control, a JS error is received: "Uncaught TypeError: Cannot read property 'enable' of undefined". Objects are declared before data is received:
```javascript
var myPolygon;
var myFeatureGroup = L.featureGroup();
var map = L.map('mapdiv').setView([-21.113887987117593, 149.14807319641113], 15);
L.tileLayer('http://{s}.tiles.mapbox.com/v3/##myaccount##/{z}/{x}/{y}.png', {
    maxZoom: 18
}).addTo(map);
```
Then, when data is received from the AJAX function for the polygon, it is added to the featureGroup as follows:
```javascript
function getPolygonDetails_CallBack(response) {
    handleResponse(response.d.response);

    myPolygon = omnivore.wkt.parse(response.d.polygonGeography);
    myFeatureGroup.addLayer(myPolygon);
    myFeatureGroup.addTo(map);

    var drawControl = new L.Control.Draw({
        edit: {
            featureGroup: myFeatureGroup
        },
        draw: {
            polygon:true,
            polyline: false,
            rectangle: false,
            circle: false,
            marker: false
        }
    }).addTo(map);

    map.on('draw:created', function (e) {
        myFeatureGroup.addLayer(e.layer);
    });
}
```

Now - when the draw modify control is used, the error is displayed - as though it can no longer reference "myPolygon".

![image](https://cloud.githubusercontent.com/assets/12078426/7290596/1a23ee8e-e9c5-11e4-8ab9-ed057212742a.png)

Same result tested in leaflet 0.7.3 & 0.8-dev and leaflet.draw 0.2.2 & 0.2.3.

**Comment by tyeware** [comment]
I suspect this issue is with this:
```Javascript
myPolygon = omnivore.wkt.parse(response.d.polygonGeography);
```
I have set up this JSFiddle. When the coordinates are built directly from an array, the edit function is successful. When built using the function call for omnivore.wkt.parse - the render is successful, but editing generates the error.

https://jsfiddle.net/f9kmrhb7/73/

**Comment by dvector** [comment]
Its returning a featuregroup object
```
if (myPolygon instanceof L.FeatureGroup) {
	alert('Its a FeatureGroup object');
}
```

**Comment by ddproxy** [comment]
@dvector @tyeware Have you resolved the issue with this? (probably wkt parsing)

**Comment by tyeware** [comment]
Hi @dvector & @ddproxy - This issue still occurs. As you have said, in my example, myPolygon is of type L.FeatureGroup when it should be of type L.Polygon, when I am using the following statement to create the polygon:

`myPolygon = omnivore.wkt.parse(response.d.polygonGeography);`

The reason why I was using the omnivore parsing was because this required less manipulation by the web service to prepare the data before it was sent to the client for rendering. As mentioned, building this manually from an array works fine.

So the question is - how can I have the above statement return an L.Polygon rather than an L.FeatureGroup?

Updated fiddle:

[https://jsfiddle.net/f9kmrhb7/85/](url)

**Comment by ddproxy** [comment]
@tyeware @dvector

Updated:
[https://jsfiddle.net/f9kmrhb7/86/](https://jsfiddle.net/f9kmrhb7/86/)

`omnivore.wkt.parse()` returns a GeoJSON object, which by default, is a [FeatureGroup](http://leafletjs.com/reference.html#geojson)

Since FeatureGroup extends [LayerGroup](http://leafletjs.com/reference.html#layergroup) You can walk through the layers presented and add them individually to the FeatureGroup used for Leaflet.draw

**Comment by tyeware** [comment]
That's awesome - thanks for the assistance.
