### ISSUE TITLE
Snap to vertex

### ISSUE THREAD

**Issue by kyriacos** [Leaflet/Leaflet.draw#406]
Is there a way i can get the draw to snap to an existing vertex? We are currently using Openlayers 2 and thinking of switching to Leaflet than upgrade to Openlayers 3.

To get an idea of what i mean there's an example using OpenLayers 3 at http://openlayers.org/en/v3.5.0/examples/draw-and-modify-features.html?q=draw

If you draw a polygon and then start drawing another one, when you get close to an existing vertex attaches/snaps to it.

Thanks

**Comment by ddproxy** [comment]
https://github.com/makinacorpus/Leaflet.Snap does what you need
