### ISSUE TITLE
DeleteHandlerOptions is empty in the documentation

### ISSUE THREAD

**Issue by pgrm** [Leaflet/Leaflet.draw#408]
Hi, the documentation of [DeleteHandlerOptions](https://github.com/Leaflet/Leaflet.draw/blob/master/README.md#deletehandleroptions) is empty. Does it mean the object doesn't really have any properties or is it just missing?

I've found this old issue https://github.com/Leaflet/Leaflet.draw/issues/119, which requests to add `selectedPathOptions` to `DeleteHandlerOptions`, which happens to be the only property on `EditHandlerOptions`. This makes me think that `DeleteHandlerOptions` doesn't have any properties, is that correct?

In which case, what is the point of the property? Is it for future ideas?

Thanks for clarification

**Comment by ericdrosas87** [comment]
The solution is simply to omit the field entirely if you do not want to use it:

`
interface EditOptions {
            /**
             * This is the FeatureGroup that stores all editable shapes.
             * THIS IS REQUIRED FOR THE EDIT TOOLBAR TO WORK
             *
             * @default null
             */
            featureGroup: FeatureGroup;

            /**
             * Edit handler options. Set to false to disable handler.
             *
             * @default null
             */
            edit?: DrawOptions.EditHandlerOptions | false;

            /**
             * Delete handler options. Set to false to disable handler.
             *
             * Default value: null
             */
            remove?: null | false;
        }
`

I pulled the above lines straight from the source code, as you can see the remove property can either be null or false.

I propose opening a bug and removing/rewording these comments and updating the documentation.
