### ISSUE TITLE
Publish v0.2.4 to NPM

### ISSUE THREAD

**Issue by hokkos** [Leaflet/Leaflet.draw#410]
Hi,
the last package on [npm is the 0.2.3](https://www.npmjs.com/package/leaflet-draw), please update it to 0.2.4.

Thanks.

**Comment by abrin** [comment]
it would be nice have this exposed to "bower" as well. I think the release needs to be published to their repo (but I'm not 100% sure)

**Comment by spalger** [comment]
+1

**Comment by syldor** [comment]
+1

**Comment by StepanKuzmin** [comment]
+1

**Comment by ddproxy** [comment]
@hokkos @abrin @spalger @syldor @stepankuzmin This has been done, closing this issue.
