### ISSUE TITLE
leaflet.draw not working with 0.8dev?

### ISSUE THREAD

**Issue by jhpoosthoek** [Leaflet/Leaflet.draw#413]
I downloaded the master.zip and tried out examples/basic.html. As I need 0.8dev I changed the libs/leaflet-src.js in the HTML with the 0.8dev version of leaflet. But somehow I can't draw polylines and polygons anymore. Does anyone have an idea what might be the problem?

Thanks in advance!

**Comment by PaulTodd** [comment]
I updated to the latest version of Leaflet 1.0dev.  I now have issues editing and deleting markers/polygons/polylines.  I've been able to fix all the plugins I use except for leaflet-draw.  Here are the actions and errors associated with each.  Has anyone else seen these errors and know of a workaround?

Markers:
Edit - Unhandled exception at line 1128, column 3 in http://localhost:63946/js/leaflet.draw-src.js

0x800a138f - JavaScript runtime error: Unable to get property 'enable' of undefined or null reference

	addHooks: function () {
		var marker = this._marker;

		marker.dragging.enable();
		marker.on('dragend', this._onDragEnd, marker);
		this._toggleMarkerHighlight();
	},

Edit Cancel - Unhandled exception at line 1136, column 3 in http://localhost:63946/js/leaflet.draw-src.js

0x800a138f - JavaScript runtime error: Unable to get property 'disable' of undefined or null reference

	removeHooks: function () {
		var marker = this._marker;

		marker.dragging.disable();
		marker.off('dragend', this._onDragEnd, marker);
		this._toggleMarkerHighlight();
	},

Delete:  No error, but it will not delete the marker.

Polygon:
Edit - Unhandled exception at line 1448, column 7 in http://localhost:63946/js/leaflet-src.js

0x800a138f - JavaScript runtime error: Unable to get property 'lat' of undefined or null reference

	project: function (latlng) {
		var d = Math.PI / 180,
		    max = 1 - 1E-15,
		    sin = Math.max(Math.min(Math.sin(latlng.lat * d), max), -max);

		return new L.Point(
				this.R * latlng.lng * d,
				this.R * Math.log((1 + sin) / (1 - sin)) / 2);
	},

Edit Cancel - Unhandled exception at line 5419, column 3 in http://localhost:63946/js/leaflet-src.js

0x800a138f - JavaScript runtime error: Unable to get property '0' of undefined or null reference

	// recursively turns latlngs into a set of rings with projected coordinates
	_projectLatlngs: function (latlngs, result) {

		var flat = latlngs[0] instanceof L.LatLng,
		    len = latlngs.length,
		    i, ring;

		if (flat) {
			ring = [];
			for (i = 0; i < len; i++) {
				ring[i] = this._map.latLngToLayerPoint(latlngs[i]);
			}
			result.push(ring);
		} else {
			for (i = 0; i < len; i++) {
				this._projectLatlngs(latlngs[i], result);
			}
		}
	},

Edit Save - Unhandled exception at line 3011, column 4 in http://localhost:63946/js/leaflet.draw-src.js

0x800a138f - JavaScript runtime error: Unable to get property 'dispose' of undefined or null reference

	removeHooks: function () {
		if (this._map) {
			// Clean up selected layers.
			this._featureGroup.eachLayer(this._disableLayerEdit, this);

			// Clear the backups of the original layers
			this._uneditedLayerProps = {};

			this._tooltip.dispose();
			this._tooltip = null;

			this._map
				.off('mousemove', this._onMouseMove, this)
				.off('touchmove', this._onMouseMove, this);
		}
	},

Polyline:
Edit - Unhandled exception at line 81, column 3 in http://localhost:63946/js/leaflet-src.js

0x800a138f - JavaScript runtime error: Unable to get property '_leaflet_id' of undefined or null reference

	// return unique ID of an object
	stamp: function (obj) {
		/*eslint-disable */
		obj._leaflet_id = obj._leaflet_id || ++L.Util.lastId;
		return obj._leaflet_id;
		/*eslint-enable */
	},

**Comment by danzel** [comment]
Use the leaflet-master branch
https://github.com/Leaflet/Leaflet.draw/tree/leaflet-master
I'm working on fixing it up for some breaking changes now, so check back in 24 hours and it should work.
If it doesn't then please open a new issue.

**Comment by jhpoosthoek** [comment]
Hi Dave, sorry for not having responded earlier. I was wondering, could you turn the changes into a new leaflet.draw-src.js on dist? Thanks in advance.
