### ISSUE TITLE
Draw a marker button does not works on my Iphone and Ipad

### ISSUE THREAD

**Issue by rischanlab** [Leaflet/Leaflet.draw#423]
I've tried to open this demo http://leaflet.github.com/Leaflet.draw/ and I could not add my point (draw a marker) by using my safari browser. I've tried using my Iphone and my Ipad and the result is same.

**Comment by jekuno** [comment]
Please have a look at https://github.com/Leaflet/Leaflet.draw/pull/285

**Comment by ddproxy** [comment]
@rischanlab L.draw 0.3.0 will be released tomorrow with support for touch (on L 0.7.7) L 1.x support is slated for 0.5.0 to try to coincide with the official L 1.x release.
