### ISSUE TITLE
Draw polygon with mousemove

### ISSUE THREAD

**Issue by vko-online** [Leaflet/Leaflet.draw#426]
Would be great if user clicks on polygon-editor button on toolbar, and draw polygon without those points, (I can not explain)
He just draws a polygon and presses done button, not the way he would click on the first point of polygon, (if you try Zillow- Rents app from AppStore you will understand what i mean, they have that feature that user can simply draw area, not neccesarily to multiple clicks on map, and press ok)

**Comment by jekuno** [comment]
Have a look at https://github.com/Wildhoney/Leaflet.FreeDraw for a free draw feature.
