### ISSUE TITLE
leaflet repeated in the bower.json

### ISSUE THREAD

**Issue by iranreyes** [Leaflet/Leaflet.draw#427]
In the bower.json you have:

  "dependencies": {
    "leaflet-dist": "0.7.x"
  },

and

  "devDependencies": {
    "leaflet": "~0.7.0",
    ....
  }

But the leaflet itself has a dist version so the leaflet-dist library is not necessary.

**Comment by jwasil** [comment]
I :+1: this issue.  This could be resolved via #373, is that right @jacobtoye, et. al.?  Thanks.
