### ISSUE TITLE
How to save markers and other layers

### ISSUE THREAD

**Issue by wocmultimedia** [Leaflet/Leaflet.draw#430]
I'm not a developer. I want to use your plugin but I don't understand how to save markers after I set it on the map using the full example.
Please, let me have a full functional example including the save function code lines or point me at where I can find it.
I need to create maps for my website.
Thanks
Angelo

**Comment by jieter** [comment]
Maybe you could use http://geojson.io to edit the maps and [view the resulting GeoJSON in your website](http://leafletjs.com/reference.html#geojson)?

**Comment by wocmultimedia** [comment]
You suggest to create a set of markers on geojson.io then I can copy the feature objects or save it as GeoJSON and use it in my map project to later change colours and other properties?

**Comment by jieter** [comment]
You did not give a whole lot of information about your map creation requirements, so it might not work for you, but you can change color properties in geojson.io. These properties are saved in each Point properties map:
```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "marker-color": "#b70c0c",
        "marker-size": "medium",
        "marker-symbol": ""
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          10.8984375,
          57.7041472343419
        ]
      }
    }
  ]
}```
Vanilla Leaflet will not do anything with these properties, you need some [simplestyle implementation](https://github.com/mapbox/simplestyle-spec/wiki/Implementations) to display them according to the style you gave them in geojson.io.

**Comment by wocmultimedia** [comment]
I'll give you better information about my map work requirements. I'm a video director, so I'm going to create maps with multimedia embedded in a marker. So far I'm using maps marker pro to do in my Wordpress based site but I want to develop a similar custom map with selectable layers in a collapsible panel like this http://labs.easyblog.it/maps/leaflet-panel-layers/examples/collapsible-panel.html 
I saw that in this case the author used geojson data to create his bar.js then he styled later.

My need is to create my selectable custom layers according to different topics of my itinerary (i.e. one layer each for museums, churchs, etc.)
I suppose I can create each layer with geojson.io then add my multimedia to popup arguments.
What do you suggest? This is a map I created in my website but with on e layer only http://www.wocmultimedia.biz/en/video-map-marker/

Thanks

**Comment by jieter** [comment]
hmm, sounds like some custom code will be needed to make this work, but you could also add the video url to the Point's properties.

**Comment by wocmultimedia** [comment]
Thanks. I will study the geojson instructions and see how I can accomplish it.
Your support is great indeed.
