### ISSUE TITLE
Is this still actively maintained?

### ISSUE THREAD

**Issue by kyriacos** [Leaflet/Leaflet.draw#431]
Going through some of the issues and looking at the last commit it seems that work has stopped on this plugin.

True/false? :)

**Comment by stev-0** [comment]
I agree, it would be nice to know what the status of the project is. Is it waiting for Leaflet-1.0 or what?

**Comment by danzel** [comment]
I'm working on getting leaflet master support working again.
We don't have a lot of time to work on this unfortunately, as usual PRs are nice but even then it takes a bit of time to go through them.

**Comment by jekuno** [comment]
:+1:

**Comment by ddproxy** [comment]
This has moved to https://github.com/Leaflet/Leaflet.draw/issues/473
