### ISSUE TITLE
Continue drawing

### ISSUE THREAD

**Issue by Starefossen** [Leaflet/Leaflet.draw#44]
Are there any technical limitations within the leaflet framework which would prohibit a continue drawing feature?

**Comment by ValGeolives** [comment]
Hi, i need that feature too ! :/ @Oliv05 can you show me your hack?  
thanks !

**Comment by Oliv05** [comment]
Hi
I'm quite buzzy right now to clean the code (there is some code used in my app here but not relevant for your problem), so the idea is to redefine Polyline addHooks and removeHooks methods. I hope this could help you :
'''
L.Draw.Polyline.prototype.addHooks = function() {
	nttLog('addHooks');
	L.Draw.Feature.prototype.addHooks.call(this);
	
	if (NTT.carto.lastPolyline) {
		// pour pouvoir reprendre la ligne à la fin (la continuer) quand la
		// ligne est chargée à l'initialisation de l'appli, data existante côté
		// serveur
		this._nttModified=true;
		this._geoid = NTT.carto.editingTraceId;
		
		this._poly = NTT.carto.lastPolyline;
		var latlongs=this._poly.getLatLngs(); length=latlongs.length;
		this._markerGroup = new L.LayerGroup();
		this._markers = [];
		this._poly.setLatLngs([]);//On met à zéro car addVertex rerempli _poly
		
		this._currentLatLng=this._map.getCenter();
		for (var i=0;i<length;i++){
			this.addVertex(latlongs[i]);
		}
	}
	else{
		this._nttModified=false;
	}

	NTT.carto.drawPolyline = this;
	if (this._map) {
		if (!this._markers) {
			this._markers = [];
			this._markerGroup = new L.LayerGroup();
		}
		this._map.addLayer(this._markerGroup);

		if (this._poly) {
			this._poly._map = this._map;
		}
		else
			this._poly = new L.Polyline([], this.options.shapeOptions);

		this._tooltip.updateContent(this._getTooltipText());

		// Make a transparent marker that will used to catch click events. These
		// click
		// events will create the vertices. We need to do this so we can ensure
		// that
		// we can create vertices over other map layers (markers, vector
		// layers). We
		// also do not want to trigger any click handlers of objects we are
		// clicking on
		// while drawing.
		if (!this._mouseMarker) {
			this._mouseMarker = L.marker(this._map.getCenter(), {
				icon : L.divIcon({
					className : 'leaflet-mouse-marker',
					iconAnchor : [ 20, 20 ],
					iconSize : [ 40, 40 ]
				}),
				opacity : 0,
				zIndexOffset : this.options.zIndexOffset
			});
		}

		this._mouseMarker.on('mousedown', this._onMouseDown, this).addTo(
				this._map);

		this._map.on('mousemove', this._onMouseMove, this).on('mouseup',
				this._onMouseUp, this).on('zoomend', this._onZoomEnd, this);
	}
};

/**
 * Redefinition des fonctions addHooks et removeHooks pour continuer la première
 * ligne plutôt que d'en retracer une nouvelle
 * 
 */
L.Draw.Polyline.prototype.removeHooks = function() {
	// alert('hehe');

	nttLog('RH:Remove Hooks');

	L.Draw.Feature.prototype.removeHooks.call(this);

	this._clearHideErrorTimeout();

	this._cleanUpShape();

	// remove markers from map
	this._map.removeLayer(this._markerGroup);
	nttLog('RH:removeMarkerGroup');
	 delete this._markerGroup;
	 delete this._markers;
	
	this._map.removeLayer(this._poly);
	nttLog('RH:RemoveLayer this._poly');
	var geojson=this._poly.toGeoJSON();
	delete this._poly;
		

	this._mouseMarker.off('mousedown', this._onMouseDown, this).off('mouseup',
			this._onMouseUp, this);
	this._map.removeLayer(this._mouseMarker);
	nttLog('RH:RemoveLayer this._mouseMarker');
	delete this._mouseMarker;

	
	// clean up DOM
	this._clearGuides();

	this._map.off('mousemove', this._onMouseMove, this).off('zoomend',
			this._onZoomEnd, this);
	
	if (this._nttValidated){
		if (this._nttModified){
			geojson.id=this._geoid;
			updateGeo(geojson, null);//On envoie la modification
		}
		else//Envoie d'une nouvelle trace
			sendNewTrace(geojson, null);
		this._nttValidated=false;
	}

};

'''

**Comment by ValGeolives** [comment]
@Oliv05  Thanks for the quick answer ! //Merci beaucoup!

**Comment by humiki** [comment]
It's still not possible to continue drawing a polyline in version 0.7.3. Any plans to implement this feature?

**Comment by ValGeolives** [comment]
@humiki this is a little function i made to continue drawing à polyline.
```javascript 
this.restartManualDraw = function (Poly,opt)
    {
        self.ObjCreate = new L.Draw.Polyline(map, opt); //enable new polyline drawing mode.
        self.ObjCreate.enable();
        self.ObjCreate._mouseDownOrigin = L.point(55, 5); // line needed for anoying tips ( size in kilometers)

        var lastPolyDraw = null;
        var layerD = null;

        if (isDefined(Poly)) //if we pass a polyline in parameters
        {
            if (Poly instanceof GLVPolyline) // my stuff
                lastPolyDraw = Poly.getNative(); //my stuff
            else
                lastPolyDraw = Poly; 
        }
        else 
        {
            lastPolyDraw = self.getLastLine().getNative(); //getLastLine drawn.
            layerD = self.getLayerDessin(); // get the featureGroup 
            layerD.removeLayer(lastPolyDraw); //remove polyline (my stuff) you had to remove from featureGroup
        }

        if (isDefined(lastPolyDraw)) // if we have a result
        {

            var points = lastPolyDraw.getLatLngs(); // get all the latlng from the polyline we have to restart drawing
            self.ObjCreate._currentLatLng = points[0];// needed for tips 
            for (var i = 0; i < points.length; i++)
            {
                self.ObjCreate.addVertex(points[i]); // add latlng by latlng to re build the polyline
            }
        }
    };
```

it's not perfect but it works :)

**Comment by olmoe** [comment]
@ValGeolives 
Where do I put this code?

**Comment by pimeggermont** [comment]
What is the status of this issue? I am also searching for this functionality in Leaflet.
Does someone got an in code example from the code above?

**Comment by Candyffm** [comment]
Still haven't found an anwser to this topic. Why is it closed?

**Comment by ElijahKotyluk** [comment]
@jacobtoye any plans to get this implemented?
