### ISSUE TITLE
Hide polylines at Zoom level

### ISSUE THREAD

**Issue by olmoe** [Leaflet/Leaflet.draw#444]
Hi fellas!

I want to hide all polylines which were made at a certain zoom level, for instance, if I made a polyline at zoom level 15, then I can only see those polylines at that zoom level, so if I zoom in to level 14 they disappear and when I go back to level 15 they come up again.

Where would I even start to get this going?

Great plugin, love it! :)

**Comment by danzel** [comment]
You'd need to listen to the zoom events on the map and add/remove the layers from the map.
Outside of the scope of the draw plugin.
Good luck!
