### ISSUE TITLE
Line, PolyLine, Circle, etc. Disappear after drawing

### ISSUE THREAD

**Issue by DrYSG** [Leaflet/Leaflet.draw#463]
I thought this was a Leaflet 1.0 Beta 2, issue. But I rolled back to 7.7 and the current copy of Leaflet.draw.  (Tried in desktop Chrome and Firefox).

I have no issue starting the drawing of lines, polylines, or ciricles, or rectagles. But when I complete by clicking on the last item, it dissapears. No errors in console. I copied the code pretty much line for line. (I originally did not have the map created till later, and added the drawLayer at that time). But I am mystified. Any ideas on what I can do to debug:

```javascript
             theMap = L.map('mapCanvas', {
                 center: mCityCenter,
                 zoom: 20,
                 layers: [osmLight, mapLayer, carLayer]
             });
             drawLayer = new L.FeatureGroup();
             drawLayer.addTo(theMap);
             var drawControl = new L.Control.Draw({
                 edit: {
                     featureGroup: drawLayer
                 }
             });
             drawControl.addTo(theMap);
```

**Comment by AbdelBa** [comment]
Once a shape is drawn, you are free to use it the way you want.
In your case, you want to add it to the map.

It's described [here](https://github.com/Leaflet/Leaflet.draw#drawcreated).

```javascript
map.on('draw:created', function (e) {
    // Do whatever else you need to. (save to db, add to map etc)
    map.addLayer(layer);
});
```

**Comment by DrYSG** [comment]
Yes, I got used to the old old version of leaflet.draw. Thanks for the refreshing. I am closing this.
