### ISSUE TITLE
Add measurement result in popup

### ISSUE THREAD

**Issue by huangcong891** [Leaflet/Leaflet.draw#472]
I'm new to Leaflet，I just have a issue that add the measurement result to popup.

Can anyone help me with that?

Thank you very much

**Comment by thataustin** [comment]
Here's an example: https://www.mapbox.com/mapbox.js/example/v1.0.0/show-polygon-area/

You should probably close this issue.  That's more of a stackoverflow question, or maybe even just a question for google ;)

**Comment by huangcong891** [comment]
Thank you very much!
