### ISSUE TITLE
Find lat-long information of drawn shapes and restrict shapes to be drawn inside polygon only

### ISSUE THREAD

**Issue by ultrasonicsoft** [Leaflet/Leaflet.draw#475]
Hi There,

I am using this library for drawing on graph and love this one.

I am having below requirement.
1. I will draw a polygon and allow other shapes like rectangle, circle to be drawn in that polygon only. If user tries to draw outside polygon he shouldn't be able to do so.
2. I want to save all drawn shapes to be saved in my db along with lat-long information. 

Could you please let me know if there is any way to get drawn shapes information?

Thanks!

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com/questions/tagged/leaflet](https://gis.stackexchange.com) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
