### ISSUE TITLE
Glyphicons attribution missing in Leaflet.draw demo?

### ISSUE THREAD

**Issue by sgustafsson** [Leaflet/Leaflet.draw#476]
Hi,

in the readme, it says "The icons used for some of the toolbar buttons are either from http://glyphicons.com/ or inspired by them". I assume you are using those icons under the GLYPHICONS FREE license?; if so, the GLYPHICONS site says "The GLYPHICONS FREE can be used both commercially and for personal use, but you must always add a link to GLYPHICONS.com in a prominent place (e.g. the footer of a website), include the CC-BY license and the reference to GLYPHICONS.com on every page using icons." I don't see this kind of attribution made on http://leaflet.github.io/Leaflet.draw/

**Comment by ddproxy** [comment]
@sgustafsson I agree this is an issue, but I think the Glyphicons license wasn't a clear when Leaflet.draw used them or for inspiration (>2 years ago) so we are grandfathered with the previous license. By 0.4.0 I'll redesign the icons to not use Glyphicons (and higher-res).
