### ISSUE TITLE
Is it possible to style edit marker icons?

### ISSUE THREAD

**Issue by Starefossen** [Leaflet/Leaflet.draw#48]
Is any way to change the style of the marker icons in a polyline when it is in edit mode?

When instantiating the drawControl I know that this it is possible:

```
var drawControl = new L.Control.Draw({
    polyline: {
        icon: new L.DivIcon({
            iconSize: new L.Point(10, 10),
            className: 'leaflet-div-icon leaflet-editing-icon my-own-class'
        })
    }
});
```

However this only applies to drawing and the style reverts back to the "default" when entering edit mode. The only solution for achieving this when editing is to override the `leaflet-editing-icon` css class which is kind of a dirty hack. 

Am I missing something?

**Comment by mfdickerson** [comment]
I've tried the above code, and still have the style of the marker icons revert back to their default settings.

**Comment by mfdickerson** [comment]
This worked:
`
L.Edit.Poly = L.Edit.Poly.extend({
    options : {
        icon: new L.DivIcon({
             iconSize: new L.Point(20, 20),
             className: 'leaflet-div-icon leaflet-editing-icon my-own-icon'
        })
    }
});
`

**Comment by RickMohr** [comment]
I see no CSS styling for `leaflet-editing-icon` in either Leaflet or Leaflet Draw -- looks like the intent is to allow styling vertex icons using that class, so could omit `my-own-icon`.

**Comment by RickMohr** [comment]
Note -- if you're not using the Draw toolbar you can update the vertices for drawing by extending `L.Edit.PolyVerticesEdit` similarly to `L.Edit.Poly` above.

**Comment by 8volution23** [comment]
Sorry to revive this thread again, but how would you change the vertices shape to circles instead of squares? I tried this so far: `.leaflet-editing-icon{
    border-radius: 20px;
}` which rounds the squares, but I couldn't make them smaller.

@RickMohr , I've seen you did something similar [here](https://github.com/OpenTreeMap/otm-core/pull/3039), but not sure how to apply it to Leaflet.draw

**Comment by nadun-ascentic** [comment]
@8volution23 If you really need to do it, just use width and height property with !important. 
`.leaflet-editing-icon { 
    width: 10px !important; 
    height: 10px !important; 
    border-radius: 20px; 
}`

**Comment by juanAFernandez** [comment]
Also something as simple as overrite the classes, to for example, change to circles:

```
.leaflet-div-icon {
  background-color: #f4f4f4;
  border: 1px solid #666;
  border-radius: 50%;
  display: inline-block;
}

.leaflet-editing-icon {
  background-color: #f4f4f4;
  border: 1px solid #666;
  border-radius: 50%;
  display: inline-block;
}
```

**Comment by tonghohin** [comment]
I found a way to replace the edit icons with your own icons without messing with the CSS.

```
const moveIcon = L.divIcon({
    className: "",
    iconAnchor: [10, 10],
    html: renderToString(<MoveIcon className="size-5" />)
});

const resizeIcon = L.divIcon({
    className: "",
    iconAnchor: [5, 5],
    html: renderToString(<CustomDotIcon className="size-2.5" />)
});

L.Edit.PolyVerticesEdit = L.Edit.PolyVerticesEdit.extend({
    options: {
        icon: resizeIcon,
        touchIcon: resizeIcon
    }
});

L.Edit.Rectangle = L.Edit.Rectangle.extend({
    options: {
        moveIcon: moveIcon,
        resizeIcon: resizeIcon,
        touchMoveIcon: moveIcon,
        touchResizeIcon: resizeIcon
    }
});

L.Edit.Circle = L.Edit.Circle.extend({
    options: {
        moveIcon: moveIcon,
        resizeIcon: resizeIcon,
        touchMoveIcon: moveIcon,
        touchResizeIcon: resizeIcon
    }
});
```
