### ISSUE TITLE
L.Draw.Polygon and L.Draw.Polyline Handlers in 0.2.4 does not work with leaflet 0.7.7 in Chrome

### ISSUE THREAD

**Issue by atlefren** [Leaflet/Leaflet.draw#483]
With this minimal setup:

```
var map = L.map('map');
var osmUrl = 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
var osmAttrib ='Map data © <a href="http://openstreetmap.org">OpenStreetMap</a> contributors';
var osm = new L.TileLayer(osmUrl, {minZoom: 8, maxZoom: 12, attribution: osmAttrib}).addTo(map);

map.setView([51.505, -0.09], 13);

var drawControl = new L.Draw.Polyline(map);
drawControl.enable();
```

Map drawing does not work in Chrome (tested 48.0.2564.116 on Win 8) or Opera (tested 35.0 on win8). However, it works as expected in IE 11 and Firefox 44.0.2.

By "does not work" I mean that I'm unable to start drawing a polyline/polygon, the cursor changes and the help text appears, but when i click the map nothing happens.

I'm rather certain that this is caused by the fact that the "onmousedown"-event on this._mouseMarker is never triggered. This in turn means that this._mouseDownOrigin is always undefined/null and that the code in _onMouseUp always skips doing what it should.

I've tried figuring out WHY the onmousedown event never triggers, but I cannot seem to figure out what causes this. Any help appreciated, given a nod in the right direction I might be able to fix this, but for now I'm stuck

**Comment by IvanSanchez** [comment]
@atlefren Leaflet 0.7.x or 1.0.0-beta?

**Comment by atlefren** [comment]
@IvanSanchez 0.7.7 as stated in the title

**Comment by IvanSanchez** [comment]
Ah, OK.

And, am I right to assume you're using a mouse and not a touchscreen? Also, does it work in Chrome on Linux/Mac?

**Comment by atlefren** [comment]
Using mouse, yes

Tested in 
Chrome 48.0.2564.116 on Win 8): Does not work
Opera  35.0 on win8): Does not work
Chrome Version 46.0.2490.80 (64-bit) on Ubuntu: Does not work
Firefox 42.0 on Ubuntu: Does not work
InternetExplorer 11 on Win8: Works
Firefox 44.0.2 on Win8: Works

Also, tested on Chrome on Android (touch): Does not work


Minimal example: http://docs.atlefren.net/ldraw/

**Comment by Golovior** [comment]
I don't know if it is required, but shouldn't you add the drawControle to the map?

`map.addControl(drawControl);`

**Comment by atlefren** [comment]
@Golovior I'm trying to use just the handler, not the whole draw control

**Comment by atlefren** [comment]
/me slaps himself around with a large trout

Stupid me!

It turns out that by not including the stylesheet for Leaflet Draw I miss the required styles for the invisible marker used for drawing (the leaflet-mouse-marker class). This causes something to break.

Solution: reference the proper css file!

Sorry for the fuzz guys!
