### ISSUE TITLE
Polygon - Click on first point don't finish the shape

### ISSUE THREAD

**Issue by csailly** [Leaflet/Leaflet.draw#510]
When drawing a polygon, a click on first point don't finish the polygon.

Analyse :
When drawing, mouseup event is call twice so two markers with same coordinates are created. So first marker is behind second marker and can not be clicked.

Workaround (tested with Leaflet version 0.7.7):
Edit src and comment line setting mouseup event on map :
`this._map`
`				//.on('mouseup', this._onMouseUp, this) // Necessary for 0.7 compatibility`
`				.on('mousemove', this._onMouseMove, this)`
`				.on('zoomlevelschange', this._onZoomEnd, this)`
`				.on('click', this._onTouch, this)`
`				.on('zoomend', this._onZoomEnd, this);`

**Comment by ChrisRus** [comment]
Using Leaflet 0.7.7 + leaflet-draw 0.3.0 and trying simple scenario based on 'Common tasks' README.md example. Everything appears to be working okay except for when I finish drawing the shape disappears. For circle/rectangle this occurs immediately upon mouse-up. For polyline/polygon this occurs when last/first-drawn point is clicked. Is this related I wonder?

**Comment by Nyxelio** [comment]
Note this workaround works great on Chrome (or with any touch-enabled browser). As you say, mouseup event is called twice.
But it also breaks Firefox, because the click event, this_onTouch, excludes: 
```if (L.Browser.touch) {
  this._onMouseDown(e);
  this._onMouseUp(e);
}```

**Comment by Nyxelio** [comment]
A tricky way is to bind mouseup only if browser support touch event, like that:
```
if(!L.Browser.touch){
     this._map.on('mouseup', this._onMouseUp, this); // Necessary for 0.7 compatibility
}
this._map
     // .on('mouseup', this._onMouseUp, this) // Necessary for 0.7 compatibility
     .on('mousemove', this._onMouseMove, this)
     .on('zoomlevelschange', this._onZoomEnd, this)
     .on('click', this._onTouch, this)
     .on('zoomend', this._onZoomEnd, this);
```

**Comment by fehro** [comment]
@Nyxelio your suggestion fixed the issue for me. We were getting it randomly on certain machines regardless of the browser used (Edge, Chrome) but works great now. Thanks!
