### ISSUE TITLE
Use SVG for icons

### ISSUE THREAD

**Issue by edg2s** [Leaflet/Leaflet.draw#518]
Current we build a PNG and a 2x PNG. Most browser support SVG directly.

**Comment by ddproxy** [comment]
PNG support is still included for older browsers... :(

**Comment by edg2s** [comment]
Indeed. To be clear I'm suggesting SVG with a PNG fallback. This can be done with one extra line of CSS using the linear gradient trick: http://pauginer.com/post/36614680636/invisible-gradient-technique

**Comment by edg2s** [comment]
We are currently successfully serving SVGs in Wikipedia's map extension: https://www.mediawiki.org/wiki/Extension:Kartographer/demo?veaction=edit

**Comment by ddproxy** [comment]
Sweet, thanks @edg2s
