### ISSUE TITLE
Get polyline that is  being drawn

### ISSUE THREAD

**Issue by senolozgur** [Leaflet/Leaflet.draw#547]
We need to get polyline that is being drawn(before drawing(before draw:created fires) finishes).
When drawing finishes we can use drawControl.options.edit.featureGroup._layers; but wile polyline is still being drawn  we couldnt access drawn polyline.
Is that possible?

**Comment by SirenHound** [comment]
If you can access the handler, you can get the property _poly, which is the shape being drawn.

I've created a fiddle for you:
https://jsfiddle.net/Sirenhound/fxk7mrxv/

**Comment by senolozgur** [comment]
Thank you,
that helped very much.

**Comment by caioiglesias** [comment]
Please close this issue @senolozgur
