### ISSUE TITLE
How to obtain the geometry(coordinates) of the drawn polygon or circle?

### ISSUE THREAD

**Issue by yingxiaxin** [Leaflet/Leaflet.draw#551]
In some cases I need to get the geometry of the drawn graphic, like polygon and circle, but how to do it  ? How to get the coordinates of the draw result?

**Comment by maladon** [comment]
`            //can grab on to the leaflet draw events here and register whatever we want them to do.
            map.on('draw:created', function (e) {
                const type = e.layerType;
                const layer = e.layer;

                // When a user finishes editing a shape we get that information here
                editableLayers.addLayer(layer);
                console.log('draw:created->');
                console.log(JSON.stringify(layer.toGeoJSON()));
            });
`

**Comment by ddproxy** [comment]
A Circle will not be the geometry of the circle, instead it will be the centroid (point).

You can get the radius of the circle `circle.getRadius()`

**Comment by marie15** [comment]
Thanks for this piece of code, it helped me. In my case I want just to retrieve the coordinates of shapes not the complet geojson format.
Any help is appreciated :)

**Comment by knownasilya** [comment]
@ddproxy that seems weird, because you'd expect circle to export a Polygon geojson.

**Comment by hamza-sabri5** [comment]
if you are drawing a circle and want to obtain all of it's GeoJSON coordinates you can read this article it's so helpful 
https://gis.stackexchange.com/questions/285352/how-to-get-the-exact-circle-that-user-has-drawn-using-leaflet-draw-circle/381314#381314
