### ISSUE TITLE
Is it possible to delete multiple vertices of a polygon simultaneously?

### ISSUE THREAD

**Issue by rajkishan16** [Leaflet/Leaflet.draw#554]
Hi,

Suppose I have drawn a polygon using Leaflet.draw, but I made the mistake of creating too many vertices in the same direction. Right now, I know that it is possible to click on the Edit option and click on the vertices that I want to delete one by one. But if there are too many points, it might take a really long time to delete each and every such point. Is there any way by which I can delete multiple vertices of the polygon at the same time?

Thanks,
Raj

**Comment by ddproxy** [comment]
Not at this time.

**Comment by rajkishan16** [comment]
Thank you!

**Comment by t1a2l** [comment]
@rajkishan16 @ddproxy Hey, have the same issue, any news on this? any solution? or a way it can be achieved?
