### ISSUE TITLE
Uncaught TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by caioiglesias** [Leaflet/Leaflet.draw#555]
The demo at http://leaflet.github.io/Leaflet.draw/ is running on version `L.drawVersion="0.2.4-dev"` and works as expected.

On version 0.3.0 though:
1. Draw any shape. 
2. Click the edit button.
3. Click anywhere on the map other than the shape.

And you get `leaflet.js:6 Uncaught TypeError: Cannot read property 'call' of undefined`

https://jsfiddle.net/caioiglesias/pspsk5L3/

**Comment by TGMorais** [comment]
Hi,

I can confirm this is happening to me too, 
I may be wrong, but I believe this is because of a recent commit that attached an event handler of non-existent function.

https://github.com/Leaflet/Leaflet.draw/commit/88271ea62691f4f575289da76cf836731635f5a8#diff-8096a3175ddafb1620d59064f291af37R75

The `this._editStyle` callback is undefined, thus causing the click event to throw the error

**Comment by ALTinners** [comment]
I can confirm this is happening too.

**Comment by SkeDoodle** [comment]
Same bug here.

**Comment by SirenHound** [comment]
L.EditToolbar.Edit addHooks tries to bind non existent '_editStyle' function to the click event.

line 3258:           .on('click', this._editStyle, this)

and in removeHooks:
line 3278:    	.off('click', this._editStyle, this)

**Comment by shotor** [comment]
What is the purpose of the editStyle function? Is it save to remove?

**Comment by SkeDoodle** [comment]
Removing the line 3199 `.on('click', this._editStyle, this)` did the trick for me.

**Comment by flibbertigibbet** [comment]
Can work around this by adding an empty function before creating the draw control:
```javascript
L.EditToolbar.Edit.prototype._editStyle = function() {};
```

**Comment by mmasruhin28** [comment]
<?php
$my_js = "
        var toolDetail = ".json_encode($checkinData).";
        var i;
        
		var mapOptions = {
	           center: [-7.280445, 112.688845],
	           zoom: 12
	        }
        var map = new L.map('mapid', mapOptions);

        var layer = new L.TileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png');
        map.addLayer(layer);
        
        
        for (i = 0; i < toolDetail.length; i++) {
            var iconCustom = L.icon({
                iconUrl: '../img/tool-category/'+toolDetail[i].toolIdToolCategory.tool_category_pic,
                iconSize:     [30, 40],
            });
            
            function onClick(e) {
                console.log(i);
                $('#datatool-tool_name').val(toolDetail[i].tool_name);
                $('#datatool-tool_date_install').val(toolDetail[i].tool_date_install);
                $('#datatool-tool_tahun_anggaran').val(toolDetail[i].tool_tahun_anggaran);
                $('#datatool-tool_no_sk').val(toolDetail[i].tool_no_sk);
                $('#datatool-tool_loc_install').val(toolDetail[i].tool_loc_install);
                $('#datatool-tool_loc_lat').val(toolDetail[i].tool_loc_lat);
                $('#datatool-tool_loc_lng').val(toolDetail[i].tool_loc_lng);
            }
            
            
            var marker = L.marker([toolDetail[i].tool_loc_lat, toolDetail[i].tool_loc_lng], {icon: iconCustom}).bindPopup(toolDetail[i].tool_name).on('click', this.onClick, this);
            marker.addTo(map);
            
        }
        
        
        $('#datatool-tool_id_tool_category').on('change',function(){
            $.post(\"category?id=\"+$(this).val(), function(data){
                    toolDetail = JSON.parse(data);
                });
        });
        
        ";

$this->registerJS($my_js, View::POS_END); ?>

**Comment by mmasruhin28** [comment]
for (i = 0; i < toolDetail.length; i++) {
            var iconCustom = L.icon({
                iconUrl: '../img/tool-category/'+toolDetail[i].toolIdToolCategory.tool_category_pic,
                iconSize:     [30, 40],
            });
            
            function onClick(e) {
                console.log(i);
                $('#datatool-tool_name').val(toolDetail[i].tool_name);
                $('#datatool-tool_date_install').val(toolDetail[i].tool_date_install);
                $('#datatool-tool_tahun_anggaran').val(toolDetail[i].tool_tahun_anggaran);
                $('#datatool-tool_no_sk').val(toolDetail[i].tool_no_sk);
                $('#datatool-tool_loc_install').val(toolDetail[i].tool_loc_install);
                $('#datatool-tool_loc_lat').val(toolDetail[i].tool_loc_lat);
                $('#datatool-tool_loc_lng').val(toolDetail[i].tool_loc_lng);
            }
            
            
            var marker = L.marker([toolDetail[i].tool_loc_lat, toolDetail[i].tool_loc_lng], {icon: iconCustom}).bindPopup(toolDetail[i].tool_name).on('click', this.onClick, this);
            marker.addTo(map);
            
        }

**Comment by mmasruhin28** [comment]
i cant get i in function, console.log show count of data
