### ISSUE TITLE
Please add leaflet.draw v 0.3.0 to CDNJS

### ISSUE THREAD

**Issue by devdattat-webonise** [Leaflet/Leaflet.draw#567]
Leaflet.draw is available via CDN at https://cdnjs.com/libraries/leaflet.draw, but only two older versions are available.

Please add the 0.3.0 version to the CDN as well, since it is the only version which has the updated events.

**Comment by kandenas** [comment]
Any progress here? I should probably know this, but could how is the CDN link for leaflet draw maintained? Could it be automatically set to publish any new release of Draw from Github?

**Comment by ddproxy** [comment]
It's added to the CDNJS repository and committed in PR. I have not done
this yet, but anyone may do it.


Jon West

Skype: ddproxy
GVoice: (414) 604-6190

Gmail: ddproxy@gmail.com
Email: ddproxy@ddproxy.net
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby (a) notified that any
disclosure, copying, distribution or taking any action with respect to the
content of this information is strictly prohibited and may be unlawful, and
(b) kindly requested to inform the sender immediately and destroy any
copies. Digital Design Proxy is neither liable for the proper and complete
transmission of the information contained in this communication nor for any
delay in its receipt.

**Comment by devdattat-webonise** [comment]
@ddproxy Thanks for this information. I did not know this was possible.

I've opened an Issue there: https://github.com/cdnjs/cdnjs/issues/8650

**Comment by kandenas** [comment]
Super, many thanks to both of you for quick response :-)


Best,
Kjetil

**Comment by PeterDaveHello** [comment]
CDNJS maintainer here.

I am now working on this, and I have a problem here, there is minified js file in `dist` folder, but there isn't minified css file in there. I wonder if you could rename `leaflet.draw.css` to `leaflet.draw-src.css` and provide a minified `leaflet.draw-src.css` called `leaflet.draw.css`, just like the js file does, or even you can rename it by the most common used naming schema:

- leaflet.draw.js
- leaflet.draw.min.js
- leaflet.draw.css
- leaflet.draw.min.css

What do you guys think?

**Comment by kandenas** [comment]
Sounds good  - I guess the better way is to use the common naming schema.

**Comment by ddproxy** [comment]
Leaflet draw is now available automatically on cdnjs

**Comment by PeterDaveHello** [comment]
@ddproxy would you like to have a cdnjs badge in the readme like the build status badge? Thanks.
