### ISSUE TITLE
can't run example: L.Control.Draw is not a constructor

### ISSUE THREAD

**Issue by bubnenkoff** [Leaflet/Leaflet.draw#570]
remove plz

**Comment by bubnenkoff** [comment]
it was my issue

**Comment by nisinha** [comment]
Hi,

Recently I am facing with same issue. What exactly you did to resolve the issue?

**Comment by jerefrer** [comment]
Same here.

Could this just show that the library hasn't been properly required ?

**Comment by mgpolinn** [comment]
I found the issues with webpack,
TypeError: __WEBPACK_IMPORTED_MODULE_1_leaflet___default.a.Control.Draw is not a constructor
