### ISSUE TITLE
How to get currently edited layer from draw:editvertex event

### ISSUE THREAD

**Issue by rawbeans** [Leaflet/Leaflet.draw#575]
I am trying to use the editvertex event to handle whenever the bounds of polygons on my map change. When a vertex of a polygon is moved, this event is fired, but the data passed to the function is the list of vertices layers.

Is there an easy way to get the parent polygon object?

**Comment by AKAMEDIASYSTEM** [comment]
Hi, I have this issue too and would love to know the official Leaflet approach for this common use case...

In the meantime, I am getting the edited Polygon's new points (including points added during an edit) with the answer I posted over in StackOverflow http://stackoverflow.com/questions/38504322/leaflet-draw-get-polygon-latlng-in-draweditvertex-event/39237274#39237274

...hope this helps, and thanks to the Leaflet folks for making an excellent utility!
