### ISSUE TITLE
Cannot edit marker in example from main repo ("Uncaught TypeError: Cannot read property 'enable' of undefined")

### ISSUE THREAD

**Issue by m314** [Leaflet/Leaflet.draw#579]
From the examples, I opened the `basic.html` file in Chrome, added a marker and a rectangle, then tried to edit them both.  I cannot edit the marker (exception in the console, see below).  

Here's the error stack:
![image](https://cloud.githubusercontent.com/assets/558106/17780469/027c3d70-6531-11e6-8d02-7b1580895473.png)

Note that I _can_ edit the markers on the demo page (http://leaflet.github.io/Leaflet.draw/) and when I rollback the plugin files on a similar example to the leaflet.draw.css and Leaflet.draw.js (presumably an older version, which I downloaded from the demo page), I can edit the marker.

**Comment by ddproxy** [comment]
This issue should now be resolved, closing.

Please reopen if this error persists.

**Comment by FelipePinhoUFC** [comment]
Hi,
I get the same error when editing a poligon. My version is 0.4.9
