### ISSUE TITLE
Error while trying to delete/edit shape using leaflet draw - ESRI

### ISSUE THREAD

**Issue by nandeshnair** [Leaflet/Leaflet.draw#582]
I am trying to delete/ edit a shape created using leaflet draw.

I get the following error when trying to edit the shape created.

I'm using leaflet 1.0-rc1 and leaflet draw version 0.3.2.
![capture](https://cloud.githubusercontent.com/assets/11608218/18027083/1428b394-6c77-11e6-87e4-317aa2b831ba.JPG)

`var map = L.map('map').setView([28.7041, 77.1025], 13);
        L.esri.basemapLayer("Topographic").addTo(map);
        //Edit Toolbar

        var drawnItems = new L.FeatureGroup();
        map.addLayer(drawnItems);

        var drawControl = new L.Control.Draw({
            draw: {
                position: 'topleft',
                polygon: {
                   allowIntersection: false,
                    drawError: {
                        color: '#b00b00',
                        timeout: 1000
                    },
                    showArea: true
                },
                circle: {
                    shapeOptions: {
                        color: '#662d91'
                    }
                },
                polyline: false,
                rectangle: true,
                marker: false,
            },
            edit: {
                featureGroup: drawnItems
            }
        });
        map.addControl(drawControl);

        map.on('draw:created', function (e) {
            var type = e.layerType,
            layer = e.layer;
            drawnItems.addLayer(layer);
        });
        map.on('draw:edited', function (e) {
            var layers = e.layers;
            layers.eachLayer(function (layer) {
            });
        });`

**Comment by peterlawless** [comment]
@nandeshnair Did you close this issue because you found a solution?  If so, what was it?  I am using leaflet-draw@0.4.10 and leaflet@1.0.2 and encountering the same issue when I attempt to delete a shape.

**Comment by nandeshnair** [comment]
Hi Peter!
I updated all leaflet libraries and it worked. Please ensure that 'leaflet.css' and 'leaflet.draw.css' are imported in your code. Are you building your application using AngularJS and NodeJS?
If yes, then I recommend that you update AngularJS to the latest version as well.
