### ISSUE TITLE
Error when map loads

### ISSUE THREAD

**Issue by mblais29** [Leaflet/Leaflet.draw#590]
Hi,

I have installed the newest leaflet.draw with leaflet 0.7.7. When the map loads I am getting a cannot read property of "extend" of undefined and L.Draw.Polygon is not a constructor. See Image, any idea if this is a bug?
![leaflet draw errors](https://cloud.githubusercontent.com/assets/8483022/18292556/caea985c-7485-11e6-9073-67f1d17d0f5b.jpg)

**Comment by catbadger** [comment]
Do you have code that extends L.Draw.Polygon?

**Comment by SirenHound** [comment]
Have you included Draw.Polyline.js and Draw.SimpleShape.js in your build? These are required to construct the L.Draw.Polygon and L.Draw.Rectangle handlers respectively.

**Comment by mblais29** [comment]
Hi 

My code to create the map `
$(window).on('load',function(){
	/****************************************
	ADJUST MAP BASED ON WINDOW HEIGHT
	****************************************/
	
	// Adjust the map div to the screen size first
	$("#map").height($(window).height()- navBarMargin).width($(window).width());
	$(window).on("resize", resize);
	
	
	/****************************************
	ADDING GOOGLE MAP LAYERS
	****************************************/
		var map = new L.Map('map', {center: new L.LatLng(54.0000, -125.0000), zoom: 6});
	      var googleLayerHybrid = new L.Google('HYBRID');  // Possible types: SATELLITE, ROADMAP, HYBRID
		  var googleLayerSatellite = new L.Google('SATELLITE');
		  var googleLayerStreet = new L.Google('ROADMAP');
		  var googleLayerTerrain = new L.Google('TERRAIN');
		  //var esriMapTopo = L.esri.basemapLayer("Topographic");
		  //var esriMapImagery = L.esri.basemapLayer("Imagery");	  
		  map.addLayer(googleLayerHybrid);
		  
	/****************************************
	BASEMAP AND LAYER CONTROL FOR LEGEND
	****************************************/
	
	var baseLayers = {'Google - Street':googleLayerStreet, 'Google - Hybrid':googleLayerHybrid, 'Google - Satellite':googleLayerSatellite, 'Google - Terrain':googleLayerTerrain /*'ESRI - Imagery':esriMapImagery, 'ESRI - Topo':esriMapTopo*/};
	
	L.control.groupedLayers(baseLayers).addTo(map);
	
	// Initialise the FeatureGroup to store editable layers 
	var drawnItems = new L.FeatureGroup();
	map.addLayer(drawnItems);
	 
	// Initialise the draw control and pass it the FeatureGroup of editable layers 
	var drawControl = new L.Control.Draw({
	    edit: {
	        featureGroup: drawnItems
	    }
	});
	map.addControl(drawControl);
	
	      
});` and I have added everything that was from the leaflet.draw src & dist folder into my project folder. It seems to error when I add everything from the leaflet.draw/src folder into my project. I thought I needed those files to make it work? If I don't add the src files and folders I don't get any errors but when I go to draw anything the polygons or markers etc or either a) invisible or b) not there at all. 
![leaflet draw src folder](https://cloud.githubusercontent.com/assets/8483022/18303595/cd77f240-74d5-11e6-9b00-b774b93fab63.jpg)
![leaflet draw dist folder](https://cloud.githubusercontent.com/assets/8483022/18303599/d19ecd62-74d5-11e6-9fb6-cdde626cb467.jpg)

**Comment by catbadger** [comment]
you should only need leaflet.draw.js

**Comment by mblais29** [comment]
@catbadger I thought so too but when I draw it is invisible if I only add the leaflet.draw.js? I checked the console and no errors. Could it be because the map z-index is above the polygon, marker, polylines etc?

**Comment by mblais29** [comment]
I found out the issue, I was using an old google maps plugin that was not allowing me to draw anything on the map. I deleted those maps and added just the Open Street Map and the leaflet.draw works now.
