### ISSUE TITLE
Automatically delele the layer when drawing a new polyline

### ISSUE THREAD

**Issue by Hippipers** [Leaflet/Leaflet.draw#595]
I'm using Leaflet draw to draw some polylines and then send their coordinates (and informations in a form) to a PostGIS database with Ajax and Php.

When I first draw a polyline, it sends the coordinates of the polylines in my database.
But when I draw a second Polyline, it repeats the coordinates of my first polyline, and in another line in the database, the coordinates of the second polyline.

So, is there a way to delete automatically the first layer drawned when drawing another one ?

**Comment by ddproxy** [comment]
You can clear the layers in the drawnItems layer while listening to the draw events, such as draw:drawstart
