### ISSUE TITLE
Leaflet 1.0.0	Stable version

### ISSUE THREAD

**Issue by eaidland** [Leaflet/Leaflet.draw#601]
Hi!
As of today lefalet is in a stable version 1.0.0. 
(Leaflet 1.0.0	Stable version, released on September 27, 2016.)

Which version of Leaflet.draw is compatible with this new version?
Where to download the dist?
Please update readme also :+1: 

Thanks!

**Comment by JoeMatulka** [comment]
@eaidland Last I checked, Leaflet.draw doesn't support anything past 0.7.7

Someone please correct me if I'm wrong, because I'd love to use this library and Leaflet 1.0 :smile:

**Comment by jrandeniya** [comment]
I think its the `leaflet-master` branch but it hasn't been updated in about 10 months. The core Leaflet team mentioned this after the Leaflet 1.0 release:

> In addition to supporting the new release with fixes and improvements, the following areas will now get our close attention:
> 
> A cleaner, more stable plugin ecosystem. We want to make sure that all popular plugins work well with the latest release and are maintained. We’ll revise our plugin list page, > tighten our review process, take more key plugins under the wing of the Leaflet organization on GitHub and spend more time working on them.

Hopefully Leaflet.draw for R1.0 gets some attention :)

**Comment by ddproxy** [comment]
👍 Working on getting the time to do this. There is a bridge version for R1.0 in another repository that has not been approved yet.

There is also a move to rebuild the backend to be dependent on Leaflet.Editable and provide the current API, Events and UI as a 'wrapper'.

**Comment by ddproxy** [comment]
On that note...

@yohanboniface -- It has started... 1.0.0-rc.1 is being developed.

**Comment by yohanboniface** [comment]
> @yohanboniface -- It has started... 1.0.0-rc.1 is being developed.

Excellent!
Currently in a mission in Jordan, but please tell me if I can help in some way :)

**Comment by ddproxy** [comment]
@yohanboniface - about to board a plane to Denver. I have an hour to produce something somewhat useful while in a flying sardine canister.

**Comment by themre** [comment]
noticed that this is ready here: https://github.com/Leaflet/Leaflet.draw/pull/596

**Comment by themre** [comment]
great work! when will it be available in NPM?

**Comment by ddproxy** [comment]
Sorry about that!

0.4.0 is available on NPM now. Please close when you can confirm ;)

**Comment by themre** [comment]
Woohoo:) thanks!
