### ISSUE TITLE
Link http://leaflet.github.io/Leaflet.draw/lib/leaflet/leaflet.js 404ing

### ISSUE THREAD

**Issue by shiraleeana** [Leaflet/Leaflet.draw#608]
Hello! I'm wondering if the recent changes moved or deleted the file that was originally http://leaflet.github.io/Leaflet.draw/lib/leaflet/leaflet.js

We used to point to it (maybe we should have been pointing elsewhere!)

**Comment by ddproxy** [comment]
@shiraleeana Sorry for the changes, we moved the leaflet.github.io over to the master branch (gh-branch still exists for now).

You can access the file from http://leaflet.github.io/Leaflet.draw/examples/libs/leaflet-src.js however the suggested method is using npm or a cdnjs if possible.

**Comment by shiraleeana** [comment]
Cool thanks Jon. Good to know where it went in case others are looking too.
We've switched over to the CDN!



On Mon, Oct 17, 2016 at 5:57 AM +1100, "Jon West" <notifications@github.com> wrote:












@shiraleeana Sorry for the changes, we moved the leaflet.github.io over to the master branch (gh-branch still exists for now).



You can access the file from http://leaflet.github.io/Leaflet.draw/examples/libs/leaflet-src.js however the suggested method is using npm or a cdnjs if possible.

**Comment by dmolesUC3** [comment]
For those of us that are not experienced Nodeheads, is there any guidance on how to switch to using either npm or a CDN?

**Comment by shiraleeana** [comment]
We had separated and hard coded the links so only had to make a switch to the CDN links instead. Sorry I can't help out.

**Comment by dmolesUC3** [comment]
Even knowing what the CDN links are would be useful.

**Comment by shiraleeana** [comment]
There's a list here. The latest version shows by default: https://cdnjs.com/libraries/leaflet

Then, for leaflet.draw, the link to the list is: https://cdnjs.com/libraries/leaflet.draw

We used the CSS and JS files of both (the last two links in both lists).

Hope that helps.

**Comment by ddproxy** [comment]
Using unpkg
```
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.1/dist/leaflet.css" />
<script src="https://unpkg.com/leaflet@1.0.1/dist/leaflet.js"></script>

<link rel="stylesheet" href="https://unpkg.com/leaflet-draw@0.4.0/dist/leaflet.draw.css" />
<script src="https://unpkg.com/leaflet-draw@0.4.0/dist/leaflet.draw.js"></script>
```

Using CDNJS
```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.1/leaflet.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.1/leaflet.js"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/0.4.0/leaflet.draw.css"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/0.4.0/leaflet.draw.js"></script>
```

I'll include some documentation in the repository as well to assist.

**Comment by ddproxy** [comment]
Thanks Andrea!

Get Outlook for Android<https://aka.ms/ghei36>
