### ISSUE TITLE
npm leaflet-draw still on 0.3.2

### ISSUE THREAD

**Issue by meendoo** [Leaflet/Leaflet.draw#609]
I've just checked the project on npm and I only see version 0.3.2, although there's a new 0.4.0 version. Could you guys publish the new one? Thanks.

**Comment by themre** [comment]
already asked here :) https://github.com/Leaflet/Leaflet.draw/issues/601#issuecomment-253724202

**Comment by meendoo** [comment]
Ok, so we are two! ;P

**Comment by themre** [comment]
at least two :)

**Comment by ddproxy** [comment]
Sorry about that!

0.4.0 is available on NPM now. Please close when you can confirm ;)

**Comment by meendoo** [comment]
Thanks, @ddproxy!
