### ISSUE TITLE
Could you also provide minified css file in release?

### ISSUE THREAD

**Issue by PeterDaveHello** [Leaflet/Leaflet.draw#628]
Hi there,

I'm Peter from CDNJS! As we want to serve all the js and css files with minified version, would you also consider to provide minified css file as you provide the minified js file?

Thanks a lot!

**Comment by ddproxy** [comment]
Yass! Didn't realize I left that out... I'll get that worked into the next patch!

**Comment by ddproxy** [comment]
leaflet.draw.min.css okay?

**Comment by PeterDaveHello** [comment]
I'll respectfully suggest to keep the same naming scheme as js use something like `-src` for the non-minified file.

**Comment by ddproxy** [comment]
Can do that too. Realized that after asking, just didn't tweak my query.

I'm looking at getting the minify process a bit sleeker for Leaflet.draw.

**Comment by ddproxy** [comment]
@PeterDaveHello What is the process for Leaflet/Leaflet to provide the corrosponding files to cdnjs?

**Comment by PeterDaveHello** [comment]
@ddproxy as you can see here:
https://cdnjs.com/libraries/leaflet.draw

We currently pull the files from your npm package, could also target on git repo if you want.

**Comment by ddproxy** [comment]
And it all starts making sense. Npm package is going to be best, trying to align the build process with Leaflet as much as possible.

**Comment by PeterDaveHello** [comment]
@ddproxy using git will be same good as you also release them on GitHub (even 3 more releases than npm!)

**Comment by ddproxy** [comment]
Does that use the packaged files in the release?

**Comment by PeterDaveHello** [comment]
What do you mean packaged files?

**Comment by PeterDaveHello** [comment]
Actually we pull the whole `dist` folder:
https://github.com/cdnjs/cdnjs/blob/f39fabc1f8911dab4c0893c1001cfbb4e5690f88/ajax/libs/leaflet.draw/package.json#L20-L28

**Comment by ddproxy** [comment]
Yes, I'm trying to figure out why Leaflet doesn't have any of those files in the dist directory/folder. The files are included in the tagged release into github and are pushed into npm via our publish.sh script.

**Comment by ddproxy** [comment]
@PeterDaveHello Please close this issue once minified css is confirmed? 0.4.3 has been released.

Also, I suspect 0.5.x will not have these files in the git dist directory. Rather these files will be deployed with npm and git's releases instead.

**Comment by PeterDaveHello** [comment]
Confirmed, thanks.

**Comment by PeterDaveHello** [comment]
@ddproxy not sure if you would put them in tagged commit as the release so that you won't need to pack them by yourself, GitHub will do it for you, if the files will not be exist in the tagged commit, we may have problem to fetch them, maybe need to transfer to npm auto-update then.

**Comment by ddproxy** [comment]
A tagged commit should do, I'm looking at what happens with Leaflet when they release - each tag is pushed off the master without committing to master. Then each tag (release) has it's own commit id and can be referenced.
