### ISSUE TITLE
Polyline draw not working on touchscreen in chrome browsers using mouse

### ISSUE THREAD

**Issue by riboher** [Leaflet/Leaflet.draw#631]
Hi!

I'm using Leaflet's version 0.7.7 and Leaflet.Draw 0.4.x in Ubuntu and I've come through this bug in which I couldn't use the mouse to paint polylines in a Lenovo laptop with touchscreen (In chrome browser).

Thanks!

**Comment by ddproxy** [comment]
@riboher Touch issue. Good catch in Ubuntu ( I don't get to test Ubuntu often :( )

Current 'fix' is messy.

https://github.com/Leaflet/Leaflet.draw/issues/618

**Comment by riboher** [comment]
@ddproxy, my PR does not only fix the problem in Ubuntu. I've tried it in Windows and macOS as well, in Chrome and Firefox the problem is fixed. Same issue in IE11 though :(. Clicking on the first point seems like a hard task. It works though when double clicking on a new point

**Comment by B3nCr** [comment]
This is related to this. https://github.com/Leaflet/Leaflet.draw/issues/624

I've submitted a pull request https://github.com/Leaflet/Leaflet.draw/pull/636

Hope this helps.
