### ISSUE TITLE
Canvas renderer has strange visual issues

### ISSUE THREAD

**Issue by jbccollins** [Leaflet/Leaflet.draw#635]
## How to reproduce

- Leaflet version I'm using: Whatever version http://leaflet.github.io/Leaflet.draw/docs/examples/full.html is using
- Leaflet Draw version I'm using: ^
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: Windows 10

## What behaviour I'm expecting and which behaviour I'm seeing
I'm expecting behavior like the first half of this gif. When I change the renderer to L.canvas() there are strange visual issues with the canvas.

![leaflet-draw-canvas](https://cloud.githubusercontent.com/assets/8915552/20286268/eabcc9cc-aa93-11e6-8526-029f1140a2f8.gif)

## Minimal example reproducing the issue

- I just visited the main example page and edited the map options via the console

**Comment by ddproxy** [comment]
Oh wow, that's an interesting one.

I'll tag this, but I'm not sure what's going on at first glance.

**Comment by jbccollins** [comment]
Yeah I'm not sure it's a leaflet-draw problem. It's quite possible that this is a leaflet issue.

**Comment by jbccollins** [comment]
Ok. I have a workaround solution that works for me. The reason I'm using canvas in the first place is because I'm drawing tens of thousands of features on a the map and svg performance is an issue with that kind of load. Canvas handles this much better. But for my use case a user is not going to be drawing anywhere near that number of polygons on the map so it's fine to use the svg renderer. Due to how shapeOptions are passed into the corresponding native leaflet shape (eg https://github.com/Leaflet/Leaflet.draw/blob/master/src/draw/handler/Draw.Rectangle.js#L38) You can just set the renderer in shape options.

```javascript
new L.Control.Draw({
      draw: {
        rectangle: {
          shapeOptions: {
            renderer: L.svg()
          }
        }
      }
    }));
```
I do have one remaining question though. Is it possible to set a shapeOption for every shape type so as to avoid code like this?

```javascript
new L.Control.Draw({
      draw: {
        rectangle: {
          shapeOptions: {
            renderer: L.svg()
          }
        },
        polyline: {
          shapeOptions: {
            renderer: L.svg()
          }
        },
        polygon: {
          shapeOptions: {
            renderer: L.svg()
          }
        }
        ...etc
      }
    }));
```

**Comment by jbccollins** [comment]
Answering my own question...

```javascript
    const shapeOptions = {
      renderer: L.svg(),
      color: 'orange',
      opacity: 1,
    };
    this._map.addControl(new L.Control.Draw({
      edit: {
        featureGroup: drawnItems,
        poly : {
          allowIntersection : false
        }
      },
      draw: {
        polyline: {
          shapeOptions: {...shapeOptions}
        },
        polygon : {
          allowIntersection: false,
          showArea:true,
          shapeOptions: {...shapeOptions}
        },
        circle: {
          shapeOptions: {...shapeOptions}
        },
        rectangle: {
          shapeOptions: {...shapeOptions}
        },
      },
    }));
```

**Comment by jbccollins** [comment]
https://github.com/Leaflet/Leaflet/issues/5145
I think that's the same issue but with a pure Leaflet implementation.
