### ISSUE TITLE
Example uses barely-visible pink lines

### ISSUE THREAD

**Issue by mvl22** [Leaflet/Leaflet.draw#642]
The example given at
http://leaflet.github.io/Leaflet.draw/docs/examples/full.html

results in pink lines that are in practice not very visible.

As this is likely to be an example that gets copied a lot, I think it would be sensible to copy the standard Leaflet.js blue colour instead as the default:

`#3388ff`

given at
http://leafletjs.com/reference-1.0.0.html#path-color

(Obviously people can still modify this as currently.)

**Comment by ddproxy** [comment]
@mvl22 This is done.
