### ISSUE TITLE
Unable to change units (metric = false) after draw control added to map

### ISSUE THREAD

**Issue by casramsey** [Leaflet/Leaflet.draw#645]
I don't see a way to change the units once the draw toolbar has been instantiated.  If I put the controls on the page and then call something like:
`drawControl.options.draw.circle.metric = false`
the option changes to false, but the tooltip measure still shows in metric.  i guess the option has already been passed on to the object.

Is there any other way for me to implement this manually?  I thought I might be able to capture the object on 'draw:drawstart', but the event doesn't hold the object.  any other possibilities?

Thanks!

**Comment by ddproxy** [comment]
It's correct that the draw control object is only applied when the toolbar has been initialized.

Have you tried calling setOptions on the toolbar with the new drawControl options?

**Comment by casramsey** [comment]
Good call - I set all draw options again using setOptions, just with metric changed.  Thanks!
