### ISSUE TITLE
Release 0.4.4 is missing several files

### ISSUE THREAD

**Issue by locobert** [Leaflet/Leaflet.draw#647]
The following files from the `dist` directory that are in 0.4.3 are missing in 0.4.4:
- leaflet.draw-src.css
- leaflet.draw-src.js
- leaflet.draw-src.map
- leaflet.draw.css

Is this intentional?

**Comment by ddproxy** [comment]
@locobert oops! I didn't configure the package.json properly for npm. My apologies, this will be included in the next patch.

**Comment by locobert** [comment]
Thanks for looking into this!

You might be still working on it, but I've just saw your recent commits and in 0.4.6 the files mentioned above are present but the `dist/images` folder is missing.

**Comment by ddproxy** [comment]
I know 😢  I've now learned the { "files": [] } option in the package.json will exclude all other files. There's a 0.4.7 that includes the images and the docs (now) so it should be much better.

Thanks for staying on top of this, let me know if I broke something yet again. Apparently npm releases are cheap.

**Comment by locobert** [comment]
Looks good - thanks a lot for the quick fix!

And I've learned that without the `files` list (almost) everything is included 😄 . I had looked at the history for `package.json` and was wondering how it worked before 0.4.4

**Comment by ddproxy** [comment]
Before 0.4.4 there was no files list. So, that's definitely the pain point. I'll be sure to include that declaration from now on in any packages I manage.
