### ISSUE TITLE
added dist/ to .gitignore?

### ISSUE THREAD

**Issue by z0d14c** [Leaflet/Leaflet.draw#652]
Please excuse me if I'm missing something -- I'm not trying to call anyone out or anything, and I'm very thankful for all the contributors to this project.

It seems though, that we recently added `./dist/*.js` etc. back to the .gitignore, causing some `npm installs` for me which point to, for example, my local github branch to have only the `./dist/images/*` and not the relevant `dist` files. Is this intentional? Is there some npm magic that I am missing which makes this ok? I see that if i set my `package.json` to point to "*" for leaflet-draw it still seems to work okay.

In any case, I don't recall having this issue previously and perhaps the README.MD could be updated to reflect a new workflow around contributing to this project.

**Comment by ddproxy** [comment]
You are right, this isn't clear. I'll get this wrapped up properly so installs work properly again.

**Comment by z0d14c** [comment]
fair enough, feel free to close when done

**Comment by vladimirbuskin** [comment]
@ddproxy @z0d14c but removing dist files is breaking usage with bower anyway right? I am using lib with bower, any option?

**Comment by ddproxy** [comment]
@vladimirbuskin I'll add a postinstall script to the bower file to generate the dist files upon install. This should resolve bower issues going forward, I believe.

**Comment by ddproxy** [comment]
@vladimirbuskin How are you having issues with Bower?

```bash
    bower install leaflet-draw#*
```

Installed leaflet-draw directory in bower_components...

```

272B Jan  4 09:04 .
136B Jan  4 09:04 ..
1.4K Jan  4 09:04 .bower.json
335B Jan  2 16:05 Leaflet.draw.iml
1.1K Jan  2 16:05 bower.json
272B Jan  2 16:05 dist
476B Jan  4 09:04 docs
217B Jan  2 16:05 index.html
```

And the correct version (0.4.8) with the dist directory

```
272B Jan  2 16:05 .
272B Jan  4 09:04 ..
340B Jan  2 16:05 images
7.0K Jan  2 16:05 leaflet.draw-src.css
110K Jan  2 16:05 leaflet.draw-src.js
143K Jan  2 16:05 leaflet.draw-src.map
4.8K Jan  2 16:05 leaflet.draw.css
 59K Jan  2 16:05 leaflet.draw.js
```

Bower uses the tagged release (https://github.com/Leaflet/Leaflet.draw/releases/tag/v0.4.8) to fetch the most recent release of the library  (not the master branch). If you are trying to use the bleeding edge in bower ( `leaflet-draw#master` ), that is not available.

**Comment by vladimirbuskin** [comment]
@ddproxy  works great, i didn't know that you have dists in tagged commits. Bower works good as you described for existing tags. No dists in master, which is ok after i understand how it's structured

**Comment by ddproxy** [comment]
I'm still figuring this out as well, so I'm glad this works properly for you. Just as additional information for how bower identifies what it pulls, `*` will pull the latest release whilst `0.4.8` will pull that version.

```bash
bower install leaflet-draw#*
bower install leaflet-draw#0.4.8
bower install leaflet-draw#0.4.2
```

Each release after 0.4.2 should be building and tagging dist releases. Prior to that version, dist was committed directly to master.

Closing this issue as it should be resolved for both NPM and Bower installs.
