### ISSUE TITLE
Bug in Polygon Tool after updating to Chrome 55

### ISSUE THREAD

**Issue by DouglasOGarrido** [Leaflet/Leaflet.draw#655]
- [X] I'm reporting a bug, not asking for help
- [X] I've looked at the [documentation](http://leaflet.github.io/Leaflet.draw/dist/reference-0.4.1.html) to make sure the behaviour is documented and expected
- [X] I'm sure this is a Leaflet Draw code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [X] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: 1.0.7
- Leaflet Draw version I'm using: 0.4.7
- Browser (with version) I'm using: Chrome 55.0.2883.87
- OS/Platform (with version) I'm using: Windows 10 x64
- Test in Chrome and then in Firefox to see the difference.

## What behaviour I'm expecting and which behaviour I'm seeing
- After updating Chrome 54 to Chrome 55, the Polygon tool stopping working. Started duplicating points (see the DIV's in HTML Dev Tools) and showing intersection errors that did not exist. 
- Another thing that changed was the Draw toolbar style.

## Minimal example reproducing the issue
- [jsBin](http://jsbin.com/tapavopare/edit?html,js,output) (This is a basic example taken from the Leaflet Draw sample folder itself).

- [X] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by z0d14c** [comment]
Hi, for the first bullet point I think that it may be related to #618, which is rooted in a change in how chrome handles click/touch events, which is interfacing badly with Leaflet. I think this is actively being worked on in Leaflet's main branch but I'm not 100%.

For your 2nd bullet point, I noticed that the maintainers of this project recently added ./dist/*.js etc. to the .gitignore which could possibly be messing with your styles? If that was the case, you probably wouldn't be able to load up the js either, though. We don't use the default draw toolbar styles so I'm not 100% on if they changed the styles recently, which would be a more likely explanation.

**Comment by DouglasOGarrido** [comment]
Hi @z0d14c, about the first bullet point, I'll wait until the Leaflet Team came up with a solution. Until there, I'll make some workarounds in my code or temporarily disable the Polygon tool.

For the second bullet point, I did not notice about .gitignore because I was picking up the CDN files. But the styles are not so important, I just wanted to show that difference, hehe.

Tks for your help. Any progress I can make, I notice here.

**Comment by ddproxy** [comment]
Styles didn't change - and this was done to encourage using CDN's rather than direct links to the repository as well as fall in line with Leaflet's practices.

**Comment by ddproxy** [comment]
Chrome is now being truthy when asked if it's touch even if it's not. That's great.

**Comment by z0d14c** [comment]
i believe my pull request may solve your problem https://github.com/Leaflet/Leaflet.draw/pull/657

**Comment by DouglasOGarrido** [comment]
Tks guy's!

I'll close this issue because in version 0.4.9, the bugs have been fixed. Thank you all!!

**Comment by plaxdan** [comment]
Version 0.4.9 is not working on Chrome 55 on Android. This jsbin is a clone of the [one above](https://github.com/Leaflet/Leaflet.draw/issues/655#issue-195040272) but with version 0.4.9 instead of 0.4.7:

http://jsbin.com/canigumexo

- visit the above URL on Android with Chrome 55
- click the rectangle draw tool
- try to draw a rectangle
- 💥  the rectangle stops drawing before your finger stops moving ...leaving a tiny rectangle on the map
