### ISSUE TITLE
Cannot close polygons.

### ISSUE THREAD

**Issue by umagon** [Leaflet/Leaflet.draw#670]
I'm opening this issue to address a problem depicted in some comments in #308, one of which is mine.

Whenever I start drawing a polygon, big points appear, and I'me pretty sure there are two of them each time I click somewhere within the map. Thing is, this makes it impossible to close/end the polygon, probably because the "first point" is below the second (duplicated) one.

![asdasd](https://cloud.githubusercontent.com/assets/4467191/21596702/8048e674-d11d-11e6-98b7-c94adf469259.png)

- Leaflet version I'm using: 1.0.1
- Leaflet Draw version I'm using: 0.4.7
- Browser (with version) I'm using: Chrome 55.0.2883.87 

I'm using Angular 2 with webpack.

**Comment by giangmd** [comment]
You can find at here: https://b3ncr.github.io/docs/examples/full.html
Updated file: https://b3ncr.github.io/src/draw/handler/Draw.Polyline.js
Hope, can help you.

**Comment by umagon** [comment]
Thanks, it did the trick. (I just had to also import Draw.Polygon.js) https://b3ncr.github.io/src/draw/handler/Draw.Polygon.js

When is this fix arriving to the trunk?

**Comment by umagon** [comment]
I update Leaflet via npm update leaflet-draw, and the latest version I can update to is 0.4.7. Am I doing something wrong?

**Comment by ddproxy** [comment]
Check your package.json and make sure you are not locked to leaflet-draw@0.4.7

**Comment by umagon** [comment]
I don't know why since I didn't change anything, but I was now able to update to 0.4.9. Thanks!
