### ISSUE TITLE
Q: Measurement tool

### ISSUE THREAD

**Issue by Twista** [Leaflet/Leaflet.draw#671]
Hello,

In previous version of LL.Draw I saw there was a measurement tool (displaying area of polygon which was drawn). Since couple last new version is not present anymore. 

Can I ask what happen ?

Thanks for great work on this project :)

**Comment by boris-arkenaar** [comment]
You need to enable it in the options:
```
{
  draw: {
    polygon: {
      showArea: true
    }
  }
}
```

**Comment by Twista** [comment]
Thank you for the answer.

Just double checked my code and the problem _was_ that I was using rectangle, but the option was set for the polygon.

That's right and it works now perfectly, but i'm sure it was working the other way in the past. Never mind.

Closing the issue - thanks again!
