### ISSUE TITLE
Is there a way to customize mouse messages displayed while drawing?

### ISSUE THREAD

**Issue by gwendal-pouliquen** [Leaflet/Leaflet.draw#674]
I have read the documentation but I can't find an option to modify the text message displayed when the user creates a marker ("Click map to place marker").

![screen shot 2017-01-05 at 10 13 30 am](https://cloud.githubusercontent.com/assets/11404690/21667238/27483e5a-d332-11e6-8559-09518b1bd293.png)

I do something like that in my code, to start the marker creation:
```
var myIcon = L.icon({iconUrl: 'myIcon.png'});
vm.newLocationDrawHandler = new L.Draw.Marker(map, {icon: myIcon});
```
And I would like to override the default message by adding an other option like L.Draw.Marker(map, {icon: myIcon, mouseMessage:'My custom message'})

Is it implemented? Or is there a way to modify it?

Thank you very much for you help :-)

**Comment by hanginwithdaddo** [comment]
Take a look at the following members in the plugin source:
L.drawLocal.draw.toolbar.actions.title
L.drawLocal.draw.toolbar.actions.text
. . .
L.drawLocal.draw.handlers.marker.tooltip.start
. . .
etc.
You can simply reassign these members with your own text.

**Comment by gwendal-pouliquen** [comment]
Perfect :-) I overrode these values in my code so I can update Leaflet Draw without losing my changes.

Thank you for your help.
