### ISSUE TITLE
Keep showing area/distance after creating polygon/line.

### ISSUE THREAD

**Issue by augustobg** [Leaflet/Leaflet.draw#676]
Using the option 'showArea: true' only display the area during the creation of the polygon, but when finishing, it disappears.
So, is there a way to keep on showing the area of the polygons or the distance of the line, after creating them?

**Comment by McCABRUS** [comment]
you can add a **bindpopup** with the **document.getElementsByClassName("leaflet-draw-tooltip-subtext")[0].innerHTML** info

**Comment by augustobg** [comment]
I created a function "getPopupContent", inside I implement what I want to use with the GeometryUtil.geodesicArea and GeometryUtil.readableArea functions.
And on: 
map.on('draw:created') -->  var content = getPopupContent(layer); layer.bindPopup(content);

Maybe a little bit more complex, but works for me.
Thanks.
