### ISSUE TITLE
Using proj4 and leaflet to transform coordinates

### ISSUE THREAD

**Issue by marie15** [Leaflet/Leaflet.draw#677]
Hello everybody, I'm using leaflet and proj4 library to transform coordinates of drawing polygon from WGS84 to a projected one, unfortunately it's not wotking, I got Nan,Nan as result. Honestly it's the first time I'm using proj4 library. Here is the code:
I added this scripts to my html page :

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.3.10/proj4.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/proj4leaflet/0.7.2/proj4leaflet.js"></script>
```
js script:
```javascript
latlngs = layer.getLatLngs();

var bngproj = '+proj=lcc +lat_1=33.3 +lat_0=33.3 +lon_0=-5.4 +k_0=0.999625769 +x_0=500000 +y_0=300000 +a=6378249.2 +b=6356515 +towgs84=31,146,47,0,0,0,0 +units=m +no_defs';

 var bngcoords = proj4(bngproj, [latlngs.lng, latlngs.lat]);

 alert(bngcoords);
```

Any help is appreciated :)

**Comment by ddproxy** [comment]
Sorry for the edits, I'm pretty sure the type proj4 expects is causing the response. Try casting the lat,lngs to float? I'll actually test this later tonight.

**Comment by marie15** [comment]
Thank a lot for yout attention, but finaly I found the solution. The
problem is that I didn't write the second parameter of proj4 function
correctly I had to write it like this: var bngcoords = proj4(bngproj,
[latlngs[i].lat, latlngs[i].lng]);

Thanks a lot

2017-01-11 23:59 GMT+00:00 Jon West <notifications@github.com>:
