### ISSUE TITLE
Adding multiple markers simultaneously using Leaflet.Draw

### ISSUE THREAD

**Issue by rajkishan16** [Leaflet/Leaflet.draw#687]
Right now, for drawing new markers, you have to click on the "Draw a marker" button and create a marker on the map. And then if you want to add another marker, you have to do the same thing again and so on. Is there something I can do to click the Draw button once, keep placing points on the map, and then click "Finish drawing" or something like that? Or is it already possible by some other means? I tried searching for it online, but couldn't find anything similar.

Thanks!

**Comment by nszceta** [comment]
```
map.on(L.Draw.Event.CREATED, function (event) {
    L.Draw.Marker().enable();
});
```

**Comment by mickeyjohn** [comment]
Hey @nszceta, I tried what your suggested but it does not work. Thanks.

**Comment by rajkishan16** [comment]
Hello @nszceta! Thanks for your response. I haven't got a chance to try your solution yet, but I also found another solution for this recently that I thought I'd share here.

Leaflet.Draw has a '[repeatMode](https://leaflet.github.io/Leaflet.draw/docs/leaflet-draw-latest.html#markeroptions)' property for drawing markers, and it is defaulted to false. You can set this to 'true' while creating your draw control. This is where I changed that value:

`var drawControl = new L.Control.Draw({
    edit: {
        featureGroup: featureGroup3
    },
    draw: {
        polygon: false,
        polyline: false,
        rectangle: false,
        circle: false,
        marker: {
            repeatMode: true
        }
    }
});`

Now, once you click Draw, you can continue creating markers until you click Cancel. Please let me know if you have any questions about this.

**Comment by mickeyjohn** [comment]
Thanks @rajkishan16. It's simply works.
