### ISSUE TITLE
[question] How to retrieve coordinates of a drawn polygon / rectangle

### ISSUE THREAD

**Issue by fbaffie** [Leaflet/Leaflet.draw#698]
Hi,

I had been using the custom fork of leaflet by "RCura" to draw polygons and rectanges. In Shiny, I was able to retrieve the point coordinates of those polygon / rectangles this way:
`selected_stations_indices <- reactive(which_station_in_polygon(stations, input$map_selectbox_features$features))`
and then in the `which_station_in_polygon`function, for each point i in each polygon p:
`coord[i, ] <- c(map_selection[[p]]$geometry$coordinates[[1]][[i]][[1]],
                          map_selection[[p]]$geometry$coordinates[[1]][[i]][[2]])`

I just can't figure it out with "leaflet.extras". Only drawing seems to be documented and not the retrieval of drawn information.
Even `input$map_selectbox_features´ doesn't work`

Thanks for your help!

**Comment by germanjoey** [comment]
I don't understand your example code at all - I guess you are using some
sort of code preprocessor that's unfamiliar to me.

But, getting coordinates for shapes is easy. You can either

a.) capture the L.Draw.Event.CREATED event to grab new shapes as they are
drawn, like this:

  map.on(L.Draw.Event.CREATED, function (e) {
    console.log(e.layer, e.layerType);
  });

b.) access shapes directly in the drawnItems array that you pass to the
L.Draw constructor.

Joe

**Comment by fbaffie** [comment]
Hey Joe,

Oops I'm sorry but it looks like I posted the issue at the wrong place, which is why you don't understand the code example... I am dealing with the leaflet package on R, which has a different syntax.
Thank you anyway for your answer.

Regards,           Florian
