### ISSUE TITLE
L.Mixin deprecated in Leaflet 1.0.0

### ISSUE THREAD

**Issue by jgravois** [Leaflet/Leaflet.draw#700]
- [X] I'm reporting a bug, not asking for help
- [X] I've searched through the issues to make sure it's not yet reported

`L.Evented.extend()` is the preferred technique in Leaflet 1.0.0 to specify mixins for objects that support events and should be used in favor of `L.Mixin`

more info: https://github.com/Leaflet/Leaflet/issues/5358

https://github.com/Leaflet/Leaflet.draw/blob/818af15d667dcb86d3cc42ad548b24a7358af3d4/src/draw/handler/Draw.Feature.js#L8

**Comment by seedgabo** [comment]
any updates of this?

**Comment by jjuraszek** [comment]
is there a plan to fix it?
