### ISSUE TITLE
Misaligned toolbar icons

### ISSUE THREAD

**Issue by K0ntrol** [Leaflet/Leaflet.draw#771]
- [x] I'm reporting a bug, not asking for help
- [x] I've looked at the [documentation](http://leaflet.github.io/Leaflet.draw/dist/reference-0.4.1.html) to make sure the behaviour is documented and expected
- [x] I'm sure this is a Leaflet Draw code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: 1.2.0
- Leaflet Draw version I'm using: 0.4.11
- Browser (with version) I'm using: Chrome Evergreen
- OS/Platform (with version) I'm using: Windows 10 Pro 1703
- Create a project with Leaflet 1.2.0 and Leaflet Draw 0.4.11

## What behaviour I'm expecting and which behaviour I'm seeing

![image](https://user-images.githubusercontent.com/9379815/29604512-64991ed2-87f0-11e7-9687-9d3906cd3233.png)

Icons on the draw toolbar are misaligned, they should be centered in their boxes

## Minimal example reproducing the issue

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

Using [jsfiddle](https://jsfiddle.net/Lc7b9n4d/)

**Comment by germanjoey** [comment]
I remember having this problem with an old version of leaflet & leaflet.draw, I wish I could remember what I did to fix it...

**Comment by vutrungduc7593** [comment]
I fix it by replacing images in node_modules/leaflet-draw/dist/images folder by new images in here https://github.com/Leaflet/Leaflet.draw/tree/master/src/images

**Comment by GeeBar** [comment]
The same happened to me

**Comment by GetHugWuSheng** [comment]
I'm using
Leaflet version I'm using: 1.2.0
Leaflet Draw version I'm using: 0.4.11
Browser (with version) I'm using: Chrome in Ubuntu

have the same problem

**Comment by nzifnab** [comment]
Hmm, @vutrungduc7593 's fix worked for me... but that means that the version of the images in github's "Releases" => `dist/images/*` are incorrect.

**Comment by bart** [comment]
On my machine it's working on version 0.4.13. The only thing I needed to do is refreshing the spreadsheet image because it was cached on my local server.

**Comment by brunob** [comment]
As i said in #814 a new release is needed to fix the bug.
