### ISSUE TITLE
Deprecated include of L.Mixin.Events

### ISSUE THREAD

**Issue by barbalex** [Leaflet/Leaflet.draw#775]
- [x] I'm reporting a bug, not asking for help
- [x] I've looked at the [documentation](http://leaflet.github.io/Leaflet.draw/dist/reference-0.4.1.html) to make sure the behaviour is documented and expected
- [x] I've searched through the issues to make sure it's not yet reported
- [x] I'm sure this is a Leaflet Draw code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)

----

## How to reproduce

- **Leaflet version I'm using: 1.2.0**
- Leaflet Draw version I'm using: 0.4.12
- Browser (with version) I'm using: Chrome 60.0.3112.101
- OS/Platform (with version) I'm using: Windows 10

## What behaviour I'm expecting and which behaviour I'm seeing
No warnings in the console

## Minimal example reproducing the issue
https://jsfiddle.net/barbalex/87qnj1wx
Check the output in the console

Seems that `L.Mixin.Events` is deprecated since leaflet v1.1.0 (https://github.com/Leaflet/Leaflet/releases/tag/v1.1.0)

**Comment by K0ntrol** [comment]
I am experiencing the same problem with the same setup.

**Comment by PowerPan** [comment]
I have already created a patch for that.
I have created a Pull Request [#772](https://github.com/Leaflet/Leaflet.draw/pull/772) and waiting for the approval

**Comment by barbalex** [comment]
this has been solved

**Comment by John-P** [comment]
I see that this has been fixed. However, my console is full of warnings still. Using leaflet 1.4.2 and leaflet draw 0.4.2.

**Comment by barbalex** [comment]
@John-P 
leaflet-draw@0.4.2 does not seem very up to date (24.8.2017). I am using leaflet-draw@1.0.4 now.

Plus: You probably have a typo in your leaflet version as latest is 1.4.0.

Everyting is working fine for me (also using react-leaflet@2.2.1).

**Comment by John-P** [comment]
@barbalex Ah yes, I made a typo. I am using leaflet 1.4.0 and leaflet draw 0.4.2. I was using the CDN from the end of the documentation which I didn't notice appears to be quite out of date. Edit: I've just changed the CDN URL to be up to date and all the warnings are gone. Excellent.
