### ISSUE TITLE
Doesn't work with leaflet >1.0.2 

### ISSUE THREAD

**Issue by mladenp** [Leaflet/Leaflet.draw#790]
- Leaflet version I'm using: >=1.0.3
- Leaflet Draw version I'm using: >=0.4.7
- Browser (with version) I'm using: 63.0.3230.0 (Official Build) 
- OS/Platform (with version) I'm using: macOS 10.12.6 

It won't work with versions bigger then 1.0.2 here is example: https://jsfiddle.net/mladen5/p8atjxv8/

**Comment by cherniavskii** [comment]
Hi @mladenp,
I tried Leaflet Draw v0.4.11 - it works with Leaflet 1.2.0

**Comment by mladenp** [comment]
Hey, i am sorry, my bad, it works i just forgot to import correct css version.
