### ISSUE TITLE
Can create two point polygon using "Finish" in toolbar

### ISSUE THREAD

**Issue by m314** [Leaflet/Leaflet.draw#792]
## How to reproduce

- Leaflet version I'm using: 1.0.3
- Leaflet Draw version I'm using: 0.4.12
- Browser (with version) I'm using: Chrome v. 61
- OS/Platform (with version) I'm using:  Windows 10
- Step 1: Start drawing a polygon.
- Step 2: Click twice, for two vertices.
- Step 3: Click the "Finish" button on the drawing toolbar.  This creates a two-vertex "polygon" (really a line).

## What behaviour I'm expecting and which behaviour I'm seeing
I expect that a polygon must have at least three vertices.  If I try to finish a polygon with two vertices, I expect the "Finish" button to not work (just like it behaves when I click finish with only one vertex).  Instead, I can finish a two-vertex polygon by clicking the "Finish" button on the drawing toolbar.

## Minimal example reproducing the issue
This is an MWE taken directly from the Leaflet.Draw docs: https://jsfiddle.net/zpvzkhfg/

**Comment by xivVerge** [comment]
I had the same issue and fixed it by updating the check in the completeShape function in Draw.Polyline.js as follows:

```
if (this._markers.length <= 1 || !this._shapeIsValid()) {
	return;
}
```

**Comment by jbccollins** [comment]
@xivVerge pr maybe?
