### ISSUE TITLE
Edit handlers broken for L.Polyline on 0.4.13

### ISSUE THREAD

**Issue by romelperez** [Leaflet/Leaflet.draw#810]
- [x] I'm reporting a bug, not asking for help

----

## How to reproduce

- Leaflet version I'm using: 1.2.0
- Leaflet Draw version I'm using: 0.4.13
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: Mac
- Create an instance of `L.Polygon` or `L.Polyline`
- Add it to the map
- Enable edit mode with `polygon.editing.enable()`

## What behaviour I'm expecting and which behaviour I'm seeing

Use should be able to edit `L.Polyline` and `L.Polygon` with the edit handlers attached to them. For example:

```js
const mymap = L.map('myMapElement', mapOptions);
const polygon = new L.Polygon([
  [200, 200],
  [500, 200],
  [500, 500],
  [200, 500]
]);
polygon.addTo(mymap);
polygon.editing.enable();
```

## Minimal example reproducing the issue

The [Leaflet Draw edit handlers example for Leaflet 1.x](https://leaflet.github.io/Leaflet.draw/docs/examples/edithandlers.html) has the example with the error

## The error

```js
Uncaught TypeError: Cannot read property 'className' of undefined
    at NewClass.addHooks (Edit.Poly.js:140)
    at Edit.Poly.js:42
    at NewClass._eachVertexHandler (Edit.Poly.js:33)
    at NewClass.addHooks (Edit.Poly.js:41)
    at NewClass.<anonymous> (Edit.Poly.js:506)
    at NewClass.fire (leaflet-src.js:588)
    at NewClass._layerAdd (leaflet-src.js:3548)
    at NewClass.whenReady (leaflet-src.js:3323)
    at NewClass.addLayer (leaflet-src.js:3600)
    at edithandlers.html:40
```

## The hint

I went back to Leaflet Draw version **0.4.12** and it works, with the same example. So a commit between those version broke the support.

**Comment by TPABHuKOB** [comment]
Reproduced with leaflet 1.3 and latest leaflet-draw
examples with ***.editing.enable(); fails with error
```
Uncaught TypeError: Cannot read property 'className' of undefined 
at NewClass.addHooks (Edit.Poly.js:140)
```

**Comment by romelperez** [comment]
Yes, this has been also reported here: https://github.com/Leaflet/Leaflet.draw/issues/804
