### ISSUE TITLE
New release needed to fix outdated sprite

### ISSUE THREAD

**Issue by brunob** [Leaflet/Leaflet.draw#814]
- [x] I'm reporting a bug, not asking for help

Tag 0.4.11 contains an outdated version of the sprite https://github.com/Leaflet/Leaflet.draw/blob/v0.4.11/dist/images/spritesheet.png since https://github.com/Leaflet/Leaflet.draw/pull/725 has been merged before this release. This produce a nice visual bug on the toolbar, a new release can fix that easily :)

![sprite](https://user-images.githubusercontent.com/418064/34643457-cabc138c-f324-11e7-8a80-f37552db76de.png)

**Comment by ddproxy** [comment]
0.4.12 and 0.4.13 have been available for some time...

0.4.14 and 1.0 have been released today that include that resolution.

**Comment by brunob** [comment]
You can aslo close #771 @ddproxy ;)
