### ISSUE TITLE
Can't edit a circle

### ISSUE THREAD

**Issue by LeoMaldonado** [Leaflet/Leaflet.draw#815]
- [x] I'm reporting a bug, not asking for help
- [x] I've looked at the [documentation](http://leaflet.github.io/Leaflet.draw/dist/reference-0.4.1.html) to make sure the behaviour is documented and expected
- [x] I'm sure this is a Leaflet Draw code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: 1.2.0
- Leaflet Draw version I'm using: 0.4.13
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: MacOS High Sierra
- Create a circle
- Edit this circle

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

Editing the radius of any circle created, the new radius is not applied
http://leaflet.github.io/Leaflet.draw/docs/examples/full.html

I've attached a gif explaining the problem:
![d](https://user-images.githubusercontent.com/1688902/34694352-ecc708a8-f4ad-11e7-807d-c3b81e1a4623.gif)

I have created a simple project installing Leaflet.Draw via npm and this simple project had the same behavior as the full example in the link. My local project consists of a `index.html`:
```
<!DOCTYPE html>
<html>
<body>
    <div id='map' style="width:900px;height:900px"></div>
</body>
<script src="node_modules/leaflet/dist/leaflet.js"></script>
<link rel="stylesheet" type="text/css" href="node_modules/leaflet/dist/leaflet.css">
<script src="node_modules/leaflet-draw/dist/leaflet.draw.js"></script>
<link rel="stylesheet" type="text/css" href="node_modules/leaflet-draw/dist/leaflet.draw.css">
<script src="index.js"></script>
</html>
```

and a `index.js`:
```
var map = L.map('map').setView([51.505, -0.09], 13);
L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);
// FeatureGroup is to store editable layers
var drawnItems = new L.FeatureGroup();
map.addLayer(drawnItems);
var drawControl = new L.Control.Draw({
    edit: {
        featureGroup: drawnItems
    }
});
map.addControl(drawControl);

map.on(L.Draw.Event.CREATED, function (e) {
    var type = e.layerType;
    var layer = e.layer;
    drawnItems.addLayer(layer);
});
map.on('draw:edited', function (e) {
    var layers = e.layers;
    layers.eachLayer(function (layer) {
        drawnItems.addLayer(layer);
    });
});
```

**Comment by ChaudhryAtif** [comment]
I'm facing this issue as well. I'm able to drag the circle using the middle handler, but not able to resize it.

**Comment by GustavoZatorre** [comment]
https://github.com/Leaflet/Leaflet.draw/releases/tag/v0.4.11 is solved

**Comment by ChaudhryAtif** [comment]
@GustavoZatorre I have this issue in 0.4.13

**Comment by joshkopecek** [comment]
Can confirm this occurs in 0.4.13.
Upgrading to 1.0.0 or downgrading to 0.4.11 solves the problem for me.

**Comment by LeoMaldonado** [comment]
In 1.0.0 version it is working fine. Thank You.
