### ISSUE TITLE
Cannot read property 'updateContent' of undefined

### ISSUE THREAD

**Issue by joshkopecek** [Leaflet/Leaflet.draw#822]
- [x] I'm reporting a bug, not asking for help
- [x] I've looked at the [documentation](http://leaflet.github.io/Leaflet.draw/dist/reference-0.4.1.html) to make sure the behaviour is documented and expected
- [x] I'm sure this is a Leaflet Draw code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: 1.2.0
- Leaflet Draw version I'm using: 1.0.0
- Browser (with version) I'm using: Chrome 63.0.3239.132
- OS/Platform (with version) I'm using: macOS 10.13.2
1. Set up a map with Leaflet + Leaflet.draw
1. Set up a circle in drawnItems
1. Manually enable editing (not using the toolbar)
1. Try to resize it

## What behaviour I'm expecting and which behaviour I'm seeing
Should be able to manually edit shapes (I control the editing behaviour so users can only edit one shape at a time), but get this ```updateContent``` error

## Minimal example reproducing the issue
- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

This [jsfiddle](https://jsfiddle.net/joshkopecek/fw5xmh1g/2/) reproduces the problem faithfully. Check the console log for the error - it's due to line 35 in [this file](https://github.com/Leaflet/Leaflet.draw/blob/c6af99b761c5d9900bf5a3e2e1d8827bbde29542/src/edit/handler/Edit.Circle.js).
The problem here is that ```_editTooltip``` hasn't been set up because noone clicked the pencil 'edit' button in the toolbar, since the edit state is triggered manually.
A simple ```if (this._map.hasOwnProperty('_editTooltip')) {…``` here would fix this, but I don't know if you want to cater for this eventuality?

**Comment by joshkopecek** [comment]
FYI I made a temporary fix by adding this **hack** to the setup
``` js
map._editTooltip = {
    updateContent: foo => null
}
```

**Comment by ddproxy** [comment]
@joshkopecek Thank you for this issue, as you've pointed out - it's not a normal process to trigger editing a geometry programatically. However, this is a valid bug. 1.0.1 has been release to check for the tooltip before attempting to modify it. Let me know if that resolves the issue :)

**Comment by joshkopecek** [comment]
@ddproxy I've been using this for a while - it's very useful functionality for me to be able to enable/disable editing on individual shapes.

Huge thanks for the commit. Much appreciated, I can take my ugly hack out now :-)

The [examples for edit handlers](https://leaflet.github.io/Leaflet.draw/docs/examples/edithandlers.html) makes use of this this functionality, although that example shows a ```Uncaught TypeError: Cannot read property 'className' of undefined```

**Comment by ddproxy** [comment]
I also enable/disable editing programmatically. I ended up maintaining this package because I got a bit too close to the source. While it's not complete, there's a fancy rewrite using Leaflet.Editable over in the 2.0.0-fork branch that is aiming at being more friendly for plugins (and this type of use).
