### ISSUE TITLE
Request : One .js file please

### ISSUE THREAD

**Issue by answerquest** [Leaflet/Leaflet.draw#841]
Hi, this is not a bug, but a request from an end user point of view. 

Most leaflet plugins have one .js and .css to include, and typically are also hosted on some CDN so that developers can just add the lines to get working. I could not find in the [documentation](https://leaflet.github.io/Leaflet.draw/docs/leaflet-draw-latest.html) similar instructions of that kind. After many trials, I finally took the full demo example, copied all the script includes in the header. It's a whopping **_29 .js files_**! There's ample scope for messing things up here. Also, with no CDN path defined, it's trouble for people working on CMS's.

So, requesting dev's to make as an option for people who want all the features or who don't want to bother picking and choosing features, one single .js file to include.

**Comment by siimots** [comment]
Quick search found that several CDNs are available.
I haven't tested if they are latest and work as expected.
Definitely room for improvement in documentation.

https://cdnjs.com/libraries/leaflet.draw
https://unpkg.com/leaflet-draw@latest/dist/leaflet.draw.js

**Comment by answerquest** [comment]
Hello @siimots , sorry I hadn't checked in on this again. Did now, and it worked, thanks a bunch!
I only had to copy the script tags of the bottom two: `leaflet.draw.js` and `leaflet.draw.css` . Here's one in action: [draw n download](https://answerquest.github.io/draw.html)
