### ISSUE TITLE
Uncaught TypeError: this.callInitHooks is not a function

### ISSUE THREAD

**Issue by DrPDash** [Leaflet/Leaflet.draw#934]
- [x ] I'm reporting a bug, not asking for help
- [ x] I've looked at the [documentation](http://leaflet.github.io/Leaflet.draw/dist/reference-0.4.1.html) to make sure the behaviour is documented and expected
- [x ] I'm sure this is a Leaflet Draw code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: 1.4.0
- Leaflet Draw version I'm using: 0.4.12
- Browser (with version) I'm using: Chrome Version 74.0.3729.157 (Official Build) (64-bit)
- OS/Platform (with version) I'm using: Windows 8.1
- step 1
- step 2

## What behaviour I'm expecting and which behaviour I'm seeing
Expecting to see as in: http://leaflet.github.io/Leaflet.draw/docs/examples/full.html
Getting error (in Chrome console): 

			    Uncaught TypeError: this.callInitHooks is not a function
			    at Function.e [as Draw] (leaflet.js:5)
			    at HTMLDocument.<anonymous>

			    at l (jquery-3.3.1.min.js:2)
			    at c (jquery-3.3.1.min.js:2)

## Minimal example reproducing the issue
I am replicating the example given at: 
http://leaflet.github.io/Leaflet.draw/docs/examples/full.html

The simplest code looks like:
			    //    Draw Tools

			    var drawnItems = new L.FeatureGroup();
			    map.addLayer(drawnItems);
			    ctlDraw = L.Control.Draw({
			        edit: {
			            featureGroup: drawnItems,
			            poly: {
			                allowIntersection: false
			            }
			        },
			        position: 'topright',
			        draw: {
			            polygon: {
			                allowIntersection: false,
			                showArea: true
			            }
			        }
			    }).addTo(map);

			    map.on(L.Draw.Event.CREATED, function (event) {
			        var layer = event.layer;
			        drawnItems.addLayer(layer);
			    });
- [x ] this example is as simple as possible
- [x ] this example does not rely on any third party code

Using [jsfiddle](https://jsfiddle.net/ddproxy/mvp7hgou/) or another example site.

**Comment by DrPDash** [comment]
After a thorough search over the internet, it seems like there are different versions here and on CDN and following some examples, this was resolved, i.e., it works now. I am closing the request. Thanks

**Comment by JavaScript1** [comment]
请问您是如何解决掉这个问题的

**Comment by shayneoneill** [comment]
Was a solution ever found, or is this a "wont fix"?. 

Also please don't ask a question, declare you found an answer without saying what it is, and closing it. Thats just bad manners.

**Comment by DrPDash** [comment]
This has been so long that I don't recall the issue right away. But the 'jsfiddle' link on my prev comment shows a working example. And, whatever the issue was, just sourcing from one of the several CDNs solved the issue.
So, @shayneoneill if you need some assistance in this friendly shared resource community, please request instead of policing - this is bad manners. One cannot wake up after 10 months and preach.  Thanks
