### ISSUE TITLE
without links to src files, no toolbar ?

### ISSUE THREAD

**Issue by KolamInstitute** [Leaflet/Leaflet.draw#98]
Hi,
i try to use the plugin, but, if i link only the .js and .css, there is no toolbar ?
Do i miss something ?

in the example folder, the links include all the source files, not only the lib...why ?
please, help me to understand, thx

**Comment by mhd753** [comment]
@jacobtoye, I wonder why there is no documentation regarding the installation. I have the same bad user experience. Trying to install the plugin with no luck in which to include a bunch of files for only one thing (Leaflet Draw). :((
