### ISSUE TITLE
Polyline dblclick issue in Firefox

### ISSUE THREAD

**Issue by miko866** [Leaflet/Leaflet.draw#991]
- [x] I've looked at the [documentation](http://leaflet.github.io/Leaflet.draw/dist/reference-0.4.1.html) to make sure the behaviour is documented and expected
- [x] I'm sure this is a Leaflet Draw code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: 1.6.0
- Leaflet Draw version I'm using: 1.0.4
- Browser (with version) I'm using: Firefox 77.0.1
- OS/Platform (with version) I'm using: MacOS 10.14.6
- Vue.js: 2.6.10
- Vue2Leaflet: 2.1.1
- leaflet-polylinedecorator: 1.6.0

## What behaviour I'm expecting and which behaviour I'm seeing
For creating a polyline by double-clicking on the last point, a leaflet-decorator(custom arrowhead) should be added to this polyline. 
But in Firefox, double-clicking on the last point just completes the polyline and my double-click function is ignored. No arrow will be added to the end of the polyline.
Everything works as it should in other browsers but not in Firefox. 

## Minimal example reproducing the issue
https://codesandbox.io/s/nice-sammet-q0zr3

- [x] this example is as simple as possible

**Comment by bation** [comment]
I face the problem as well ，but my brower is chrome，firefox is good in drawing polyline.  I fixed the problem by downgrade leaflet to 1.3.1

**Comment by miko866** [comment]
@bation thanks for your advice but I can't do downgrade from leaflet 1.6.0 to leaflet 1.3.1, that is no solution for me.

**Comment by johnd0e** [comment]
@miko866 
Try this solution: https://github.com/Leaflet/Leaflet.draw/issues/955#issuecomment-601190466

**Comment by miko866** [comment]
> @johnd0e
> Try this solution: [#955 (comment)](https://github.com/Leaflet/Leaflet.draw/issues/955#issuecomment-601190466)

Super thank you its works.
